import TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.PaperInterface

/-!
# Axiom audit for the cubic-stabilization reviewer interface

The commands print the kernel-reported axiom dependencies of every terminal
currently exported by the reviewer interface.
-/

#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_mixed_coefficient_identity
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.packet_multiplicity_eq_of_preserving_chain
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.packet_multiplicity_birational_in_dimension_four
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankTwoProjectiveBundle_packet_transport
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.irrational_of_nonzero_packet
