import TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.PaperInterface

/-!
# Axiom audit for the cubic-stabilization reviewer interface

The commands print the kernel-reported axiom dependencies of every terminal
currently exported by the reviewer interface.
-/

#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_mixed_coefficient_identity
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_midpoint_exponents
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_cross_coefficient_decomposition
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_weightedPair_decomposition_of_midpoint
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_finiteMatrix_generation_of_pairwise_midpoint
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_finiteMatrix_generated_iff_pairwise_midpoint_of_dvr
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_graphCoordinate_block_identity
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_dualForm_adjoint_iff
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_slopeCommutator_expansion
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_crossDepth_intersection_and_midpoint
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_crossDepth_eq_of_effectiveSlopeDifference_eq
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_crossDepth_eq_of_dvr_scalar_lifts
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.graphCoefficient_unitCrossDepth
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.squareZero_sum_pow_eq_factorial_mul_squarefreeProductSum
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_allDegree_squareZeroAssembly
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.primeDenominatorMember_all_implies_mem
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankOne_allDegree_integralProductMember_of_primeDenominators
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.sixAxisGram_unit_and_augmentation_eigenvalues
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.sixAxisGram_integralSmithReduction
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.sixAxisSmith_unit_line_and_depth_one_at_two_three
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.sixAxisPolarization_parameters_unique
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.sixAxisLocalChart_orthogonal_block
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_projectiveLine_packets
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_selfAdjointGraph_isotropic_halfDimension
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_f4Frobenius_fixed_and_exchanged
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_f4TraceDeterminant_maximalIsotropic
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_exoticStabilizer_algebraicCore
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_abstractExceptionalGroup
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.principalGluing_f4Frobenius_oddNormalizer
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.framedSixthMultiplicity
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.framedSixthMultiplicity_polynomial_pow
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.framedSixthMultiplicity_polynomial_list_prod
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.cubicPacket_indicial_factorization_and_framed_eigenvalues
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.strictNovikovAdmissibleData
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.proLaurentGaugeSystem
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.proLaurentCharacteristicPolynomialSystem
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.framedMonodromy_characteristicPolynomial_baseChange_and_gauge
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.numericalNovikov_finiteFiber_exact
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.numericalNovikov_coefficientPushforward_apply
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.formalBaseShift_characteristicPolynomial_of_matrixInput
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.strictNovikov_injective_taggedMonomial
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.packet_multiplicity_eq_of_preserving_chain
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.packet_multiplicity_eq_of_typed_weak_factorization
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.packet_multiplicity_birational_in_dimension_four
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.rankTwoProjectiveBundle_packet_transport
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.irrational_of_nonzero_packet
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.cubicThreefold_oneStep_irrational_of_packet_inputs
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.genusEight_packet_eq_two_of_flop_inputs
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationEpilogue.genusEight_oneStep_irrational_of_flop_inputs
