import TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.PaperInterface

/-!
# Axiom audit

These commands report the kernel dependencies of the proved comparison
lemmas exported by the reviewer interface.
-/

#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.FixedPhaseReader.CrossedEdge.defect_eq_normal_smul
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.FixedPhaseReader.actualProjectedRow_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.LawfulReaderIndex.Endpoint.compatibility
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ComponentReader.Reader.actualDefect_sourceRealization
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ComponentReader.Reader.actualProjectedRow_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ComponentReader.Reader.actualProjectedRow_eq_zero_on_actualSource
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CrossedEdgeComposition.compositeDefect_eq
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CrossedEdgeComposition.specialize_compositeDefect_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.defectOperator_intertwines
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.imageMap_comp
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.imageEquiv
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.imageMap_preserves_row
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_natural
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_via_imageEquiv
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_eq_zero_of_imageMap_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_eq_zero_of_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_eq_zero_of_reverse_comparison
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ModelCrossedCoordinates.Coordinates.projectedVariation_sourceToIncomingImage
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.incomingImageMap_surjective_of_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.incomingImageSpan_eq_top_of_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_incomingImageSpan_eq_top
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_specializedValues
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_normalFactor
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_incomingImageMap_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedMonodromyDiagram.SemilinearMorphism.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedLocalSystem.SemilinearHorizontal.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedLocalSystem.SemilinearHorizontal.projectedVariation_eq_zero_of_normalFactor
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.DescentPacket.fixed_of_stable_singleton
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.DescentPacket.unaryPacketEquivariantEquiv
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.DescentPacket.regular_not_equivariantly_equivalent_fixedThree
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.HorizontalReader.Reader.modelVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.HorizontalReader.Reader.actualVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.TraitHorizontalReader.Reader.specializedModelVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.TraitHorizontalReader.Reader.actualVariation_eq_zero
