import TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.PaperInterface

/-!
# Axiom audit

These commands report the kernel dependencies of the proved comparison
lemmas exported by the reviewer interface.
-/

#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.FixedPhaseReader.CrossedEdge.defect_eq_normal_smul
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.FixedPhaseReader.CrossedEdge.crossedMap_movingMap_jointly_injective_of_fullMap_injective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.FixedPhaseReader.actualProjectedRow_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.LawfulReaderIndex.Endpoint.compatibility
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ComponentReader.Reader.actualDefect_sourceRealization
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ComponentReader.Reader.actualProjectedRow_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ComponentReader.Reader.actualProjectedRow_eq_zero_on_actualSource
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CrossedEdgeComposition.compositeDefect_eq
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CrossedEdgeComposition.specialize_compositeDefect_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.defectOperator_intertwines
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.imageMap_comp
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.imageEquiv
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MonodromyImage.imageMap_preserves_row
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_natural
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_via_imageEquiv
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_eq_zero_of_imageMap_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_eq_zero_of_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ProjectedVariation.projectedVariation_eq_zero_of_reverse_comparison
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ModelCrossedCoordinates.Coordinates.projectedVariation_sourceToIncomingImage
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ModelCrossedCoordinates.Coordinates.ofParts
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ModelCrossedCoordinates.Coordinates.sourceValue_eq_zero_of_crossedMap_eq_zero_of_movingMap_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ModelCrossedCoordinates.Coordinates.sourceToIncomingImage_eq_zero_of_crossedMap_eq_zero_of_movingMap_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.ModelCrossedCoordinates.Coordinates.crossedMap_movingMap_jointly_injective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SplitCrossedCoordinates.SplitMovingTarget.ofFullMapEquivalence
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SplitCrossedCoordinates.SplitMovingTarget.coordinates
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SplitCrossedCoordinates.SplitMovingTarget.targetMonodromy_involutive
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.ambientRange_eq_variationRange
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.canCoversVariation_iff_ambientRange_eq_variationRange
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.canCoversVariation_of_can_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.variationToAmbientRangeOfCanCoverage_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.ambientRange_eq_variationRange_of_packetDefectCoversVariation
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.ambientRange_eq_variationRange_of_packetDefectBijective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.variationToAmbientRange_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.variationToAmbientRangeOfPacketCoverage_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.packetDefect_injective_of_fixedVectors_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoverage.Diagram.ambientRange_eq_variationRange_of_fixedVectors_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoordinates.FixedReceiverCertificate.toCoordinates
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoordinates.FixedReceiverCertificate.projectedVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoordinates.FixedReceiverWindowCertificate.toFixedReceiverCertificate
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoordinates.FixedReceiverWindowCertificate.projectedVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.CanVariationCoordinates.ScaledFixedReceiverWindowCertificate.projectedVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.incomingImageMap_surjective_of_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.incomingImageSpan_eq_top_of_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_incomingImageSpan_eq_top
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_specializedValues
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_normalFactor
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.Specialization.projectedVariation_eq_zero_of_incomingImageMap_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.ScaledSpecialization.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.ScaledSpecialization.projectedVariation_eq_zero_of_normalFactor
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SemilinearVariation.ScaledSpecialization.targetSquare_eq_on_incomingImage
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedMonodromyDiagram.ScaledSemilinearMorphism.transportRowScaled
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedMonodromyDiagram.ScaledSemilinearMorphism.transportRowScaled_map_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedMonodromyDiagram.SemilinearMorphism.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedMonodromyDiagram.SemilinearMorphism.transport_map_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedLocalSystem.SemilinearHorizontal.projectedVariation_specializes
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.MarkedLocalSystem.SemilinearHorizontal.projectedVariation_eq_zero_of_normalFactor
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SelectedLocalSystemReader.DiagramIdentification.selectedMorphism_map
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SelectedLocalSystemReader.selectedGaugeMorphism_map_surjective
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.DescentPacket.fixed_of_stable_singleton
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.DescentPacket.unaryPacketEquivariantEquiv
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.DescentPacket.regular_not_equivariantly_equivalent_fixedThree
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.HorizontalReader.Reader.modelVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.HorizontalReader.Reader.actualVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.TraitHorizontalReader.Reader.specializedModelVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.TraitHorizontalReader.Reader.actualVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.TraitHorizontalReader.ScaledReader.actualVariation_eq_zero
#print axioms TavisRuddFiniteGeom.Papers.CubicStabilizationIrrationality.Comparison.SelectedLocalSystemReader.ScaledGaugeReader.ofMarkedLocalSystemOfSurjective
