import RelativeConicArcs.Q25ResidualTransportData.T_036_C_037_086_V_00
import RelativeConicArcs.Q25RowCompositionData.C_0070_0074
import RelativeConicArcs.Q25RowCompositionData.C_0115_0119
import RelativeConicArcs.Q25RowCompositionData.C_0195_0199
import RelativeConicArcs.Q25RowCompositionData.C_0275_0279
import RelativeConicArcs.Q25RowCompositionData.C_0340_0344
import RelativeConicArcs.Q25RowCompositionData.C_0420_0424
import RelativeConicArcs.Q25RowCompositionData.C_0495_0499
import RelativeConicArcs.Q25RowCompositionData.C_0515_0519

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (36,58) through (36,68), aligned to T_036_C_037_086_V_00
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB036C058_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C058Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0070A Q25RowCompositionData.class0070B
        Q25RowCompositionData.class0070C := by
  rfl

theorem residualTransportB036C058_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C058Payload.canonicalConfig).card := by
  rw [residualTransportB036C058_canonicalClassLink]
  exact Q25RowCompositionData.class0070LegalOrbitSet_card_ge_32

theorem residualTransportB036C059_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C059Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0116A Q25RowCompositionData.class0116B
        Q25RowCompositionData.class0116C := by
  rfl

theorem residualTransportB036C059_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C059Payload.canonicalConfig).card := by
  rw [residualTransportB036C059_canonicalClassLink]
  exact Q25RowCompositionData.class0116LegalOrbitSet_card_ge_32

theorem residualTransportB036C062_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C062Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0342A Q25RowCompositionData.class0342B
        Q25RowCompositionData.class0342C := by
  rfl

theorem residualTransportB036C062_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C062Payload.canonicalConfig).card := by
  rw [residualTransportB036C062_canonicalClassLink]
  exact Q25RowCompositionData.class0342LegalOrbitSet_card_ge_32

theorem residualTransportB036C063_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C063Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0420A Q25RowCompositionData.class0420B
        Q25RowCompositionData.class0420C := by
  rfl

theorem residualTransportB036C063_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C063Payload.canonicalConfig).card := by
  rw [residualTransportB036C063_canonicalClassLink]
  exact Q25RowCompositionData.class0420LegalOrbitSet_card_ge_32

theorem residualTransportB036C064_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C064Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0495A Q25RowCompositionData.class0495B
        Q25RowCompositionData.class0495C := by
  rfl

theorem residualTransportB036C064_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C064Payload.canonicalConfig).card := by
  rw [residualTransportB036C064_canonicalClassLink]
  exact Q25RowCompositionData.class0495LegalOrbitSet_card_ge_32

theorem residualTransportB036C065_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C065Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0195A Q25RowCompositionData.class0195B
        Q25RowCompositionData.class0195C := by
  rfl

theorem residualTransportB036C065_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C065Payload.canonicalConfig).card := by
  rw [residualTransportB036C065_canonicalClassLink]
  exact Q25RowCompositionData.class0195LegalOrbitSet_card_ge_32

theorem residualTransportB036C067_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C067Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0515A Q25RowCompositionData.class0515B
        Q25RowCompositionData.class0515C := by
  rfl

theorem residualTransportB036C067_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C067Payload.canonicalConfig).card := by
  rw [residualTransportB036C067_canonicalClassLink]
  exact Q25RowCompositionData.class0515LegalOrbitSet_card_ge_32

theorem residualTransportB036C068_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB036C068Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0279A Q25RowCompositionData.class0279B
        Q25RowCompositionData.class0279C := by
  rfl

theorem residualTransportB036C068_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB036C068Payload.canonicalConfig).card := by
  rw [residualTransportB036C068_canonicalClassLink]
  exact Q25RowCompositionData.class0279LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
