import RelativeConicArcs.Q25ResidualTransportData.T_034_C_135_184_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0025_0029
import RelativeConicArcs.Q25RowCompositionData.C_0075_0079
import RelativeConicArcs.Q25RowCompositionData.C_0805_0809
import RelativeConicArcs.Q25RowCompositionData.C_0920_0924
import RelativeConicArcs.Q25RowCompositionData.C_0980_0984
import RelativeConicArcs.Q25RowCompositionData.C_1105_1109

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 6 class links (34,165) through (34,182), aligned to T_034_C_135_184_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB034C165_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB034C165Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0809A Q25RowCompositionData.class0809B
        Q25RowCompositionData.class0809C := by
  rfl

theorem residualTransportB034C165_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB034C165Payload.canonicalConfig).card := by
  rw [residualTransportB034C165_canonicalClassLink]
  exact Q25RowCompositionData.class0809LegalOrbitSet_card_ge_32

theorem residualTransportB034C166_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB034C166Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0984A Q25RowCompositionData.class0984B
        Q25RowCompositionData.class0984C := by
  rfl

theorem residualTransportB034C166_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB034C166Payload.canonicalConfig).card := by
  rw [residualTransportB034C166_canonicalClassLink]
  exact Q25RowCompositionData.class0984LegalOrbitSet_card_ge_32

theorem residualTransportB034C169_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB034C169Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0924A Q25RowCompositionData.class0924B
        Q25RowCompositionData.class0924C := by
  rfl

theorem residualTransportB034C169_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB034C169Payload.canonicalConfig).card := by
  rw [residualTransportB034C169_canonicalClassLink]
  exact Q25RowCompositionData.class0924LegalOrbitSet_card_ge_32

theorem residualTransportB034C171_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB034C171Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1107A Q25RowCompositionData.class1107B
        Q25RowCompositionData.class1107C := by
  rfl

theorem residualTransportB034C171_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB034C171Payload.canonicalConfig).card := by
  rw [residualTransportB034C171_canonicalClassLink]
  exact Q25RowCompositionData.class1107LegalOrbitSet_card_ge_32

theorem residualTransportB034C181_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB034C181Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0078A Q25RowCompositionData.class0078B
        Q25RowCompositionData.class0078C := by
  rfl

theorem residualTransportB034C181_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB034C181Payload.canonicalConfig).card := by
  rw [residualTransportB034C181_canonicalClassLink]
  exact Q25RowCompositionData.class0078LegalOrbitSet_card_ge_32

theorem residualTransportB034C182_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB034C182Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0027A Q25RowCompositionData.class0027B
        Q25RowCompositionData.class0027C := by
  rfl

theorem residualTransportB034C182_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB034C182Payload.canonicalConfig).card := by
  rw [residualTransportB034C182_canonicalClassLink]
  exact Q25RowCompositionData.class0027LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
