import RelativeConicArcs.Q25ResidualTransportData.T_032_C_083_132_V_01
import RelativeConicArcs.Q25RowCompositionData.C_0720_0724
import RelativeConicArcs.Q25RowCompositionData.C_0755_0759
import RelativeConicArcs.Q25RowCompositionData.C_0780_0784
import RelativeConicArcs.Q25RowCompositionData.C_0895_0899
import RelativeConicArcs.Q25RowCompositionData.C_0925_0929
import RelativeConicArcs.Q25RowCompositionData.C_1015_1019
import RelativeConicArcs.Q25RowCompositionData.C_1095_1099
import RelativeConicArcs.Q25RowCompositionData.C_1155_1159

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (32,98) through (32,116), aligned to T_032_C_083_132_V_01
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB032C098_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C098Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1099A Q25RowCompositionData.class1099B
        Q25RowCompositionData.class1099C := by
  rfl

theorem residualTransportB032C098_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C098Payload.canonicalConfig).card := by
  rw [residualTransportB032C098_canonicalClassLink]
  exact Q25RowCompositionData.class1099LegalOrbitSet_card_ge_32

theorem residualTransportB032C099_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C099Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1157A Q25RowCompositionData.class1157B
        Q25RowCompositionData.class1157C := by
  rfl

theorem residualTransportB032C099_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C099Payload.canonicalConfig).card := by
  rw [residualTransportB032C099_canonicalClassLink]
  exact Q25RowCompositionData.class1157LegalOrbitSet_card_ge_32

theorem residualTransportB032C108_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C108Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0724A Q25RowCompositionData.class0724B
        Q25RowCompositionData.class0724C := by
  rfl

theorem residualTransportB032C108_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C108Payload.canonicalConfig).card := by
  rw [residualTransportB032C108_canonicalClassLink]
  exact Q25RowCompositionData.class0724LegalOrbitSet_card_ge_32

theorem residualTransportB032C109_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C109Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0755A Q25RowCompositionData.class0755B
        Q25RowCompositionData.class0755C := by
  rfl

theorem residualTransportB032C109_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C109Payload.canonicalConfig).card := by
  rw [residualTransportB032C109_canonicalClassLink]
  exact Q25RowCompositionData.class0755LegalOrbitSet_card_ge_32

theorem residualTransportB032C110_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C110Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0784A Q25RowCompositionData.class0784B
        Q25RowCompositionData.class0784C := by
  rfl

theorem residualTransportB032C110_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C110Payload.canonicalConfig).card := by
  rw [residualTransportB032C110_canonicalClassLink]
  exact Q25RowCompositionData.class0784LegalOrbitSet_card_ge_32

theorem residualTransportB032C112_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C112Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0898A Q25RowCompositionData.class0898B
        Q25RowCompositionData.class0898C := by
  rfl

theorem residualTransportB032C112_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C112Payload.canonicalConfig).card := by
  rw [residualTransportB032C112_canonicalClassLink]
  exact Q25RowCompositionData.class0898LegalOrbitSet_card_ge_32

theorem residualTransportB032C114_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C114Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1018A Q25RowCompositionData.class1018B
        Q25RowCompositionData.class1018C := by
  rfl

theorem residualTransportB032C114_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C114Payload.canonicalConfig).card := by
  rw [residualTransportB032C114_canonicalClassLink]
  exact Q25RowCompositionData.class1018LegalOrbitSet_card_ge_32

theorem residualTransportB032C116_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB032C116Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0926A Q25RowCompositionData.class0926B
        Q25RowCompositionData.class0926C := by
  rfl

theorem residualTransportB032C116_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB032C116Payload.canonicalConfig).card := by
  rw [residualTransportB032C116_canonicalClassLink]
  exact Q25RowCompositionData.class0926LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
