import RelativeConicArcs.Q25ResidualTransportData.T_046_C_097_146_V_00
import RelativeConicArcs.Q25RowCompositionData.C_0695_0699
import RelativeConicArcs.Q25RowCompositionData.C_0725_0729
import RelativeConicArcs.Q25RowCompositionData.C_0730_0734
import RelativeConicArcs.Q25RowCompositionData.C_0810_0814
import RelativeConicArcs.Q25RowCompositionData.C_0905_0909
import RelativeConicArcs.Q25RowCompositionData.C_0925_0929
import RelativeConicArcs.Q25RowCompositionData.C_0965_0969
import RelativeConicArcs.Q25RowCompositionData.C_1025_1029

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (46,97) through (46,116), aligned to T_046_C_097_146_V_00
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB046C097_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C097Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0696A Q25RowCompositionData.class0696B
        Q25RowCompositionData.class0696C := by
  rfl

theorem residualTransportB046C097_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C097Payload.canonicalConfig).card := by
  rw [residualTransportB046C097_canonicalClassLink]
  exact Q25RowCompositionData.class0696LegalOrbitSet_card_ge_32

theorem residualTransportB046C099_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C099Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0725A Q25RowCompositionData.class0725B
        Q25RowCompositionData.class0725C := by
  rfl

theorem residualTransportB046C099_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C099Payload.canonicalConfig).card := by
  rw [residualTransportB046C099_canonicalClassLink]
  exact Q25RowCompositionData.class0725LegalOrbitSet_card_ge_32

theorem residualTransportB046C108_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C108Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0733A Q25RowCompositionData.class0733B
        Q25RowCompositionData.class0733C := by
  rfl

theorem residualTransportB046C108_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C108Payload.canonicalConfig).card := by
  rw [residualTransportB046C108_canonicalClassLink]
  exact Q25RowCompositionData.class0733LegalOrbitSet_card_ge_32

theorem residualTransportB046C112_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C112Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0906A Q25RowCompositionData.class0906B
        Q25RowCompositionData.class0906C := by
  rfl

theorem residualTransportB046C112_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C112Payload.canonicalConfig).card := by
  rw [residualTransportB046C112_canonicalClassLink]
  exact Q25RowCompositionData.class0906LegalOrbitSet_card_ge_32

theorem residualTransportB046C113_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C113Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0967A Q25RowCompositionData.class0967B
        Q25RowCompositionData.class0967C := by
  rfl

theorem residualTransportB046C113_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C113Payload.canonicalConfig).card := by
  rw [residualTransportB046C113_canonicalClassLink]
  exact Q25RowCompositionData.class0967LegalOrbitSet_card_ge_32

theorem residualTransportB046C114_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C114Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1026A Q25RowCompositionData.class1026B
        Q25RowCompositionData.class1026C := by
  rfl

theorem residualTransportB046C114_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C114Payload.canonicalConfig).card := by
  rw [residualTransportB046C114_canonicalClassLink]
  exact Q25RowCompositionData.class1026LegalOrbitSet_card_ge_32

theorem residualTransportB046C115_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C115Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0811A Q25RowCompositionData.class0811B
        Q25RowCompositionData.class0811C := by
  rfl

theorem residualTransportB046C115_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C115Payload.canonicalConfig).card := by
  rw [residualTransportB046C115_canonicalClassLink]
  exact Q25RowCompositionData.class0811LegalOrbitSet_card_ge_32

theorem residualTransportB046C116_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB046C116Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0928A Q25RowCompositionData.class0928B
        Q25RowCompositionData.class0928C := by
  rfl

theorem residualTransportB046C116_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB046C116Payload.canonicalConfig).card := by
  rw [residualTransportB046C116_canonicalClassLink]
  exact Q25RowCompositionData.class0928LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
