import RelativeConicArcs.Q25ResidualTransportData.T_048_C_099_148_V_01
import RelativeConicArcs.Q25RowCompositionData.C_0270_0274
import RelativeConicArcs.Q25RowCompositionData.C_0565_0569
import RelativeConicArcs.Q25RowCompositionData.C_0585_0589
import RelativeConicArcs.Q25RowCompositionData.C_0640_0644
import RelativeConicArcs.Q25RowCompositionData.C_0865_0869
import RelativeConicArcs.Q25RowCompositionData.C_0985_0989
import RelativeConicArcs.Q25RowCompositionData.C_1100_1104
import RelativeConicArcs.Q25RowCompositionData.C_1140_1144

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (48,118) through (48,135), aligned to T_048_C_099_148_V_01
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `c0ab5f00f995d8e80f295c243ba0d8aee3b659ac12ccb309a2a1f6adbb84d5bd`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB048C118_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C118Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0868A Q25RowCompositionData.class0868B
        Q25RowCompositionData.class0868C := by
  rfl

theorem residualTransportB048C118_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C118Payload.canonicalConfig).card := by
  rw [residualTransportB048C118_canonicalClassLink]
  exact Q25RowCompositionData.class0868LegalOrbitSet_card_ge_32

theorem residualTransportB048C118_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C118Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C118Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C118_transportValid hsource
    residualTransportB048C118_canonical_card_ge_32

theorem residualTransportB048C119_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C119Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0988A Q25RowCompositionData.class0988B
        Q25RowCompositionData.class0988C := by
  rfl

theorem residualTransportB048C119_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C119Payload.canonicalConfig).card := by
  rw [residualTransportB048C119_canonicalClassLink]
  exact Q25RowCompositionData.class0988LegalOrbitSet_card_ge_32

theorem residualTransportB048C119_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C119Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C119Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C119_transportValid hsource
    residualTransportB048C119_canonical_card_ge_32

theorem residualTransportB048C122_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C122Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1142A Q25RowCompositionData.class1142B
        Q25RowCompositionData.class1142C := by
  rfl

theorem residualTransportB048C122_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C122Payload.canonicalConfig).card := by
  rw [residualTransportB048C122_canonicalClassLink]
  exact Q25RowCompositionData.class1142LegalOrbitSet_card_ge_32

theorem residualTransportB048C122_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C122Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C122Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C122_transportValid hsource
    residualTransportB048C122_canonical_card_ge_32

theorem residualTransportB048C124_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C124Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1100A Q25RowCompositionData.class1100B
        Q25RowCompositionData.class1100C := by
  rfl

theorem residualTransportB048C124_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C124Payload.canonicalConfig).card := by
  rw [residualTransportB048C124_canonicalClassLink]
  exact Q25RowCompositionData.class1100LegalOrbitSet_card_ge_32

theorem residualTransportB048C124_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C124Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C124Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C124_transportValid hsource
    residualTransportB048C124_canonical_card_ge_32

theorem residualTransportB048C131_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C131Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0640A Q25RowCompositionData.class0640B
        Q25RowCompositionData.class0640C := by
  rfl

theorem residualTransportB048C131_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C131Payload.canonicalConfig).card := by
  rw [residualTransportB048C131_canonicalClassLink]
  exact Q25RowCompositionData.class0640LegalOrbitSet_card_ge_32

theorem residualTransportB048C131_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C131Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C131Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C131_transportValid hsource
    residualTransportB048C131_canonical_card_ge_32

theorem residualTransportB048C132_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C132Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0569A Q25RowCompositionData.class0569B
        Q25RowCompositionData.class0569C := by
  rfl

theorem residualTransportB048C132_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C132Payload.canonicalConfig).card := by
  rw [residualTransportB048C132_canonicalClassLink]
  exact Q25RowCompositionData.class0569LegalOrbitSet_card_ge_32

theorem residualTransportB048C132_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C132Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C132Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C132_transportValid hsource
    residualTransportB048C132_canonical_card_ge_32

theorem residualTransportB048C134_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C134Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0589A Q25RowCompositionData.class0589B
        Q25RowCompositionData.class0589C := by
  rfl

theorem residualTransportB048C134_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C134Payload.canonicalConfig).card := by
  rw [residualTransportB048C134_canonicalClassLink]
  exact Q25RowCompositionData.class0589LegalOrbitSet_card_ge_32

theorem residualTransportB048C134_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C134Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C134Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C134_transportValid hsource
    residualTransportB048C134_canonical_card_ge_32

theorem residualTransportB048C135_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C135Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0271A Q25RowCompositionData.class0271B
        Q25RowCompositionData.class0271C := by
  rfl

theorem residualTransportB048C135_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C135Payload.canonicalConfig).card := by
  rw [residualTransportB048C135_canonicalClassLink]
  exact Q25RowCompositionData.class0271LegalOrbitSet_card_ge_32

theorem residualTransportB048C135_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C135Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨48, by decide⟩
      Q25ResidualTransportData.residualTransportB048C135Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB048C135_transportValid hsource
    residualTransportB048C135_canonical_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
