import RelativeConicArcs.Q25ResidualTransportData.T_047_C_148_197_V_00
import RelativeConicArcs.Q25RowCompositionData.C_0065_0069
import RelativeConicArcs.Q25RowCompositionData.C_0110_0114
import RelativeConicArcs.Q25RowCompositionData.C_0705_0709
import RelativeConicArcs.Q25RowCompositionData.C_0760_0764
import RelativeConicArcs.Q25RowCompositionData.C_0810_0814
import RelativeConicArcs.Q25RowCompositionData.C_0850_0854
import RelativeConicArcs.Q25RowCompositionData.C_0965_0969
import RelativeConicArcs.Q25RowCompositionData.C_1025_1029

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (47,148) through (47,165), aligned to T_047_C_148_197_V_00
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `c0ab5f00f995d8e80f295c243ba0d8aee3b659ac12ccb309a2a1f6adbb84d5bd`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB047C148_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C148Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0114A Q25RowCompositionData.class0114B
        Q25RowCompositionData.class0114C := by
  rfl

theorem residualTransportB047C148_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C148Payload.canonicalConfig).card := by
  rw [residualTransportB047C148_canonicalClassLink]
  exact Q25RowCompositionData.class0114LegalOrbitSet_card_ge_32

theorem residualTransportB047C148_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C148Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C148Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C148_transportValid hsource
    residualTransportB047C148_canonical_card_ge_32

theorem residualTransportB047C149_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C149Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0068A Q25RowCompositionData.class0068B
        Q25RowCompositionData.class0068C := by
  rfl

theorem residualTransportB047C149_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C149Payload.canonicalConfig).card := by
  rw [residualTransportB047C149_canonicalClassLink]
  exact Q25RowCompositionData.class0068LegalOrbitSet_card_ge_32

theorem residualTransportB047C149_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C149Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C149Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C149_transportValid hsource
    residualTransportB047C149_canonical_card_ge_32

theorem residualTransportB047C156_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C156Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0764A Q25RowCompositionData.class0764B
        Q25RowCompositionData.class0764C := by
  rfl

theorem residualTransportB047C156_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C156Payload.canonicalConfig).card := by
  rw [residualTransportB047C156_canonicalClassLink]
  exact Q25RowCompositionData.class0764LegalOrbitSet_card_ge_32

theorem residualTransportB047C156_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C156Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C156Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C156_transportValid hsource
    residualTransportB047C156_canonical_card_ge_32

theorem residualTransportB047C159_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C159Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0705A Q25RowCompositionData.class0705B
        Q25RowCompositionData.class0705C := by
  rfl

theorem residualTransportB047C159_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C159Payload.canonicalConfig).card := by
  rw [residualTransportB047C159_canonicalClassLink]
  exact Q25RowCompositionData.class0705LegalOrbitSet_card_ge_32

theorem residualTransportB047C159_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C159Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C159Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C159_transportValid hsource
    residualTransportB047C159_canonical_card_ge_32

theorem residualTransportB047C161_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C161Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1028A Q25RowCompositionData.class1028B
        Q25RowCompositionData.class1028C := by
  rfl

theorem residualTransportB047C161_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C161Payload.canonicalConfig).card := by
  rw [residualTransportB047C161_canonicalClassLink]
  exact Q25RowCompositionData.class1028LegalOrbitSet_card_ge_32

theorem residualTransportB047C161_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C161Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C161Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C161_transportValid hsource
    residualTransportB047C161_canonical_card_ge_32

theorem residualTransportB047C162_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C162Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0969A Q25RowCompositionData.class0969B
        Q25RowCompositionData.class0969C := by
  rfl

theorem residualTransportB047C162_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C162Payload.canonicalConfig).card := by
  rw [residualTransportB047C162_canonicalClassLink]
  exact Q25RowCompositionData.class0969LegalOrbitSet_card_ge_32

theorem residualTransportB047C162_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C162Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C162Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C162_transportValid hsource
    residualTransportB047C162_canonical_card_ge_32

theorem residualTransportB047C164_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C164Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0850A Q25RowCompositionData.class0850B
        Q25RowCompositionData.class0850C := by
  rfl

theorem residualTransportB047C164_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C164Payload.canonicalConfig).card := by
  rw [residualTransportB047C164_canonicalClassLink]
  exact Q25RowCompositionData.class0850LegalOrbitSet_card_ge_32

theorem residualTransportB047C164_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C164Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C164Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C164_transportValid hsource
    residualTransportB047C164_canonical_card_ge_32

theorem residualTransportB047C165_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB047C165Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0812A Q25RowCompositionData.class0812B
        Q25RowCompositionData.class0812C := by
  rfl

theorem residualTransportB047C165_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB047C165Payload.canonicalConfig).card := by
  rw [residualTransportB047C165_canonicalClassLink]
  exact Q25RowCompositionData.class0812LegalOrbitSet_card_ge_32

theorem residualTransportB047C165_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C165Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨47, by decide⟩
      Q25ResidualTransportData.residualTransportB047C165Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB047C165_transportValid hsource
    residualTransportB047C165_canonical_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
