import RelativeConicArcs.Q25ResidualTransportData.T_048_C_199_248_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0695_0699
import RelativeConicArcs.Q25RowCompositionData.C_0785_0789
import RelativeConicArcs.Q25RowCompositionData.C_0840_0844
import RelativeConicArcs.Q25RowCompositionData.C_0895_0899
import RelativeConicArcs.Q25RowCompositionData.C_0925_0929
import RelativeConicArcs.Q25RowCompositionData.C_0955_0959
import RelativeConicArcs.Q25RowCompositionData.C_1015_1019

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 7 class links (48,237) through (48,247), aligned to T_048_C_199_248_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB048C237_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C237Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0925A Q25RowCompositionData.class0925B
        Q25RowCompositionData.class0925C := by
  rfl

theorem residualTransportB048C237_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C237Payload.canonicalConfig).card := by
  rw [residualTransportB048C237_canonicalClassLink]
  exact Q25RowCompositionData.class0925LegalOrbitSet_card_ge_32

theorem residualTransportB048C240_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C240Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0958A Q25RowCompositionData.class0958B
        Q25RowCompositionData.class0958C := by
  rfl

theorem residualTransportB048C240_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C240Payload.canonicalConfig).card := by
  rw [residualTransportB048C240_canonicalClassLink]
  exact Q25RowCompositionData.class0958LegalOrbitSet_card_ge_32

theorem residualTransportB048C241_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C241Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0899A Q25RowCompositionData.class0899B
        Q25RowCompositionData.class0899C := by
  rfl

theorem residualTransportB048C241_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C241Payload.canonicalConfig).card := by
  rw [residualTransportB048C241_canonicalClassLink]
  exact Q25RowCompositionData.class0899LegalOrbitSet_card_ge_32

theorem residualTransportB048C242_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C242Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0842A Q25RowCompositionData.class0842B
        Q25RowCompositionData.class0842C := by
  rfl

theorem residualTransportB048C242_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C242Payload.canonicalConfig).card := by
  rw [residualTransportB048C242_canonicalClassLink]
  exact Q25RowCompositionData.class0842LegalOrbitSet_card_ge_32

theorem residualTransportB048C243_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C243Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0785A Q25RowCompositionData.class0785B
        Q25RowCompositionData.class0785C := by
  rfl

theorem residualTransportB048C243_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C243Payload.canonicalConfig).card := by
  rw [residualTransportB048C243_canonicalClassLink]
  exact Q25RowCompositionData.class0785LegalOrbitSet_card_ge_32

theorem residualTransportB048C244_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C244Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1019A Q25RowCompositionData.class1019B
        Q25RowCompositionData.class1019C := by
  rfl

theorem residualTransportB048C244_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C244Payload.canonicalConfig).card := by
  rw [residualTransportB048C244_canonicalClassLink]
  exact Q25RowCompositionData.class1019LegalOrbitSet_card_ge_32

theorem residualTransportB048C247_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB048C247Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0695A Q25RowCompositionData.class0695B
        Q25RowCompositionData.class0695C := by
  rfl

theorem residualTransportB048C247_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB048C247Payload.canonicalConfig).card := by
  rw [residualTransportB048C247_canonicalClassLink]
  exact Q25RowCompositionData.class0695LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
