import RelativeConicArcs.Q25ResidualTransportData.T_059_C_160_209_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0000_0004
import RelativeConicArcs.Q25RowCompositionData.C_0140_0144

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (59,191) through (59,208), aligned to T_059_C_160_209_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `c0ab5f00f995d8e80f295c243ba0d8aee3b659ac12ccb309a2a1f6adbb84d5bd`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB059C191_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C191Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0141A Q25RowCompositionData.class0141B
        Q25RowCompositionData.class0141C := by
  rfl

theorem residualTransportB059C191_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C191Payload.canonicalConfig).card := by
  rw [residualTransportB059C191_canonicalClassLink]
  exact Q25RowCompositionData.class0141LegalOrbitSet_card_ge_32

theorem residualTransportB059C191_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C191Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C191Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C191_transportValid hsource
    residualTransportB059C191_canonical_card_ge_32

theorem residualTransportB059C192_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C192Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0142A Q25RowCompositionData.class0142B
        Q25RowCompositionData.class0142C := by
  rfl

theorem residualTransportB059C192_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C192Payload.canonicalConfig).card := by
  rw [residualTransportB059C192_canonicalClassLink]
  exact Q25RowCompositionData.class0142LegalOrbitSet_card_ge_32

theorem residualTransportB059C192_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C192Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C192Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C192_transportValid hsource
    residualTransportB059C192_canonical_card_ge_32

theorem residualTransportB059C193_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C193Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0141A Q25RowCompositionData.class0141B
        Q25RowCompositionData.class0141C := by
  rfl

theorem residualTransportB059C193_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C193Payload.canonicalConfig).card := by
  rw [residualTransportB059C193_canonicalClassLink]
  exact Q25RowCompositionData.class0141LegalOrbitSet_card_ge_32

theorem residualTransportB059C193_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C193Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C193Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C193_transportValid hsource
    residualTransportB059C193_canonical_card_ge_32

theorem residualTransportB059C194_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C194Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0140A Q25RowCompositionData.class0140B
        Q25RowCompositionData.class0140C := by
  rfl

theorem residualTransportB059C194_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C194Payload.canonicalConfig).card := by
  rw [residualTransportB059C194_canonicalClassLink]
  exact Q25RowCompositionData.class0140LegalOrbitSet_card_ge_32

theorem residualTransportB059C194_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C194Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C194Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C194_transportValid hsource
    residualTransportB059C194_canonical_card_ge_32

theorem residualTransportB059C196_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C196Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0143A Q25RowCompositionData.class0143B
        Q25RowCompositionData.class0143C := by
  rfl

theorem residualTransportB059C196_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C196Payload.canonicalConfig).card := by
  rw [residualTransportB059C196_canonicalClassLink]
  exact Q25RowCompositionData.class0143LegalOrbitSet_card_ge_32

theorem residualTransportB059C196_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C196Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C196Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C196_transportValid hsource
    residualTransportB059C196_canonical_card_ge_32

theorem residualTransportB059C197_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C197Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0144A Q25RowCompositionData.class0144B
        Q25RowCompositionData.class0144C := by
  rfl

theorem residualTransportB059C197_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C197Payload.canonicalConfig).card := by
  rw [residualTransportB059C197_canonicalClassLink]
  exact Q25RowCompositionData.class0144LegalOrbitSet_card_ge_32

theorem residualTransportB059C197_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C197Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C197Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C197_transportValid hsource
    residualTransportB059C197_canonical_card_ge_32

theorem residualTransportB059C198_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C198Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0143A Q25RowCompositionData.class0143B
        Q25RowCompositionData.class0143C := by
  rfl

theorem residualTransportB059C198_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C198Payload.canonicalConfig).card := by
  rw [residualTransportB059C198_canonicalClassLink]
  exact Q25RowCompositionData.class0143LegalOrbitSet_card_ge_32

theorem residualTransportB059C198_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C198Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C198Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C198_transportValid hsource
    residualTransportB059C198_canonical_card_ge_32

theorem residualTransportB059C208_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB059C208Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0000A Q25RowCompositionData.class0000B
        Q25RowCompositionData.class0000C := by
  rfl

theorem residualTransportB059C208_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB059C208Payload.canonicalConfig).card := by
  rw [residualTransportB059C208_canonicalClassLink]
  exact Q25RowCompositionData.class0000LegalOrbitSet_card_ge_32

theorem residualTransportB059C208_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C208Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨59, by decide⟩
      Q25ResidualTransportData.residualTransportB059C208Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB059C208_transportValid hsource
    residualTransportB059C208_canonical_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
