import RelativeConicArcs.Q25ResidualTransportData.T_064_C_165_214_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0000_0004
import RelativeConicArcs.Q25RowCompositionData.C_0045_0049
import RelativeConicArcs.Q25RowCompositionData.C_0330_0334
import RelativeConicArcs.Q25RowCompositionData.C_0410_0414
import RelativeConicArcs.Q25RowCompositionData.C_0535_0539

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 6 class links (64,197) through (64,213), aligned to T_064_C_165_214_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB064C197_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB064C197Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0538A Q25RowCompositionData.class0538B
        Q25RowCompositionData.class0538C := by
  rfl

theorem residualTransportB064C197_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB064C197Payload.canonicalConfig).card := by
  rw [residualTransportB064C197_canonicalClassLink]
  exact Q25RowCompositionData.class0538LegalOrbitSet_card_ge_32

theorem residualTransportB064C199_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB064C199Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0539A Q25RowCompositionData.class0539B
        Q25RowCompositionData.class0539C := by
  rfl

theorem residualTransportB064C199_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB064C199Payload.canonicalConfig).card := by
  rw [residualTransportB064C199_canonicalClassLink]
  exact Q25RowCompositionData.class0539LegalOrbitSet_card_ge_32

theorem residualTransportB064C207_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB064C207Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0049A Q25RowCompositionData.class0049B
        Q25RowCompositionData.class0049C := by
  rfl

theorem residualTransportB064C207_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB064C207Payload.canonicalConfig).card := by
  rw [residualTransportB064C207_canonicalClassLink]
  exact Q25RowCompositionData.class0049LegalOrbitSet_card_ge_32

theorem residualTransportB064C208_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB064C208Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0001A Q25RowCompositionData.class0001B
        Q25RowCompositionData.class0001C := by
  rfl

theorem residualTransportB064C208_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB064C208Payload.canonicalConfig).card := by
  rw [residualTransportB064C208_canonicalClassLink]
  exact Q25RowCompositionData.class0001LegalOrbitSet_card_ge_32

theorem residualTransportB064C212_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB064C212Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0411A Q25RowCompositionData.class0411B
        Q25RowCompositionData.class0411C := by
  rfl

theorem residualTransportB064C212_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB064C212Payload.canonicalConfig).card := by
  rw [residualTransportB064C212_canonicalClassLink]
  exact Q25RowCompositionData.class0411LegalOrbitSet_card_ge_32

theorem residualTransportB064C213_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB064C213Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0333A Q25RowCompositionData.class0333B
        Q25RowCompositionData.class0333C := by
  rfl

theorem residualTransportB064C213_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB064C213Payload.canonicalConfig).card := by
  rw [residualTransportB064C213_canonicalClassLink]
  exact Q25RowCompositionData.class0333LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
