import RelativeConicArcs.Q25ResidualTransportData.T_081_C_082_131_V_00
import RelativeConicArcs.Q25RowCompositionData.C_0765_0769
import RelativeConicArcs.Q25RowCompositionData.C_0795_0799
import RelativeConicArcs.Q25RowCompositionData.C_0850_0854
import RelativeConicArcs.Q25RowCompositionData.C_0905_0909
import RelativeConicArcs.Q25RowCompositionData.C_0910_0914
import RelativeConicArcs.Q25RowCompositionData.C_0970_0974
import RelativeConicArcs.Q25RowCompositionData.C_1030_1034

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (81,109) through (81,116), aligned to T_081_C_082_131_V_00
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `c0ab5f00f995d8e80f295c243ba0d8aee3b659ac12ccb309a2a1f6adbb84d5bd`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB081C109_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C109Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0765A Q25RowCompositionData.class0765B
        Q25RowCompositionData.class0765C := by
  rfl

theorem residualTransportB081C109_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C109Payload.canonicalConfig).card := by
  rw [residualTransportB081C109_canonicalClassLink]
  exact Q25RowCompositionData.class0765LegalOrbitSet_card_ge_32

theorem residualTransportB081C109_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C109Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C109Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C109_transportValid hsource
    residualTransportB081C109_canonical_card_ge_32

theorem residualTransportB081C110_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C110Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0795A Q25RowCompositionData.class0795B
        Q25RowCompositionData.class0795C := by
  rfl

theorem residualTransportB081C110_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C110Payload.canonicalConfig).card := by
  rw [residualTransportB081C110_canonicalClassLink]
  exact Q25RowCompositionData.class0795LegalOrbitSet_card_ge_32

theorem residualTransportB081C110_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C110Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C110Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C110_transportValid hsource
    residualTransportB081C110_canonical_card_ge_32

theorem residualTransportB081C111_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C111Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0851A Q25RowCompositionData.class0851B
        Q25RowCompositionData.class0851C := by
  rfl

theorem residualTransportB081C111_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C111Payload.canonicalConfig).card := by
  rw [residualTransportB081C111_canonicalClassLink]
  exact Q25RowCompositionData.class0851LegalOrbitSet_card_ge_32

theorem residualTransportB081C111_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C111Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C111Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C111_transportValid hsource
    residualTransportB081C111_canonical_card_ge_32

theorem residualTransportB081C112_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C112Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0909A Q25RowCompositionData.class0909B
        Q25RowCompositionData.class0909C := by
  rfl

theorem residualTransportB081C112_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C112Payload.canonicalConfig).card := by
  rw [residualTransportB081C112_canonicalClassLink]
  exact Q25RowCompositionData.class0909LegalOrbitSet_card_ge_32

theorem residualTransportB081C112_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C112Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C112Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C112_transportValid hsource
    residualTransportB081C112_canonical_card_ge_32

theorem residualTransportB081C113_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C113Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0970A Q25RowCompositionData.class0970B
        Q25RowCompositionData.class0970C := by
  rfl

theorem residualTransportB081C113_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C113Payload.canonicalConfig).card := by
  rw [residualTransportB081C113_canonicalClassLink]
  exact Q25RowCompositionData.class0970LegalOrbitSet_card_ge_32

theorem residualTransportB081C113_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C113Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C113Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C113_transportValid hsource
    residualTransportB081C113_canonical_card_ge_32

theorem residualTransportB081C114_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C114Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1030A Q25RowCompositionData.class1030B
        Q25RowCompositionData.class1030C := by
  rfl

theorem residualTransportB081C114_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C114Payload.canonicalConfig).card := by
  rw [residualTransportB081C114_canonicalClassLink]
  exact Q25RowCompositionData.class1030LegalOrbitSet_card_ge_32

theorem residualTransportB081C114_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C114Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C114Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C114_transportValid hsource
    residualTransportB081C114_canonical_card_ge_32

theorem residualTransportB081C115_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C115Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0799A Q25RowCompositionData.class0799B
        Q25RowCompositionData.class0799C := by
  rfl

theorem residualTransportB081C115_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C115Payload.canonicalConfig).card := by
  rw [residualTransportB081C115_canonicalClassLink]
  exact Q25RowCompositionData.class0799LegalOrbitSet_card_ge_32

theorem residualTransportB081C115_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C115Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C115Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C115_transportValid hsource
    residualTransportB081C115_canonical_card_ge_32

theorem residualTransportB081C116_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB081C116Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0912A Q25RowCompositionData.class0912B
        Q25RowCompositionData.class0912C := by
  rfl

theorem residualTransportB081C116_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB081C116Payload.canonicalConfig).card := by
  rw [residualTransportB081C116_canonicalClassLink]
  exact Q25RowCompositionData.class0912LegalOrbitSet_card_ge_32

theorem residualTransportB081C116_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C116Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨81, by decide⟩
      Q25ResidualTransportData.residualTransportB081C116Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB081C116_transportValid hsource
    residualTransportB081C116_canonical_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
