import RelativeConicArcs.Q25ResidualTransportData.T_112_C_213_262_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0950_0954
import RelativeConicArcs.Q25RowCompositionData.C_0955_0959

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 4 class links (112,244) through (112,249), aligned to T_112_C_213_262_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB112C244_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB112C244Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0953A Q25RowCompositionData.class0953B
        Q25RowCompositionData.class0953C := by
  rfl

theorem residualTransportB112C244_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB112C244Payload.canonicalConfig).card := by
  rw [residualTransportB112C244_canonicalClassLink]
  exact Q25RowCompositionData.class0953LegalOrbitSet_card_ge_32

theorem residualTransportB112C247_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB112C247Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0954A Q25RowCompositionData.class0954B
        Q25RowCompositionData.class0954C := by
  rfl

theorem residualTransportB112C247_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB112C247Payload.canonicalConfig).card := by
  rw [residualTransportB112C247_canonicalClassLink]
  exact Q25RowCompositionData.class0954LegalOrbitSet_card_ge_32

theorem residualTransportB112C248_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB112C248Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0955A Q25RowCompositionData.class0955B
        Q25RowCompositionData.class0955C := by
  rfl

theorem residualTransportB112C248_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB112C248Payload.canonicalConfig).card := by
  rw [residualTransportB112C248_canonicalClassLink]
  exact Q25RowCompositionData.class0955LegalOrbitSet_card_ge_32

theorem residualTransportB112C249_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB112C249Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0956A Q25RowCompositionData.class0956B
        Q25RowCompositionData.class0956C := by
  rfl

theorem residualTransportB112C249_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB112C249Payload.canonicalConfig).card := by
  rw [residualTransportB112C249_canonicalClassLink]
  exact Q25RowCompositionData.class0956LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
