import RelativeConicArcs.Q25ResidualTransportData.T_117_C_168_217_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0060_0064
import RelativeConicArcs.Q25RowCompositionData.C_0105_0109
import RelativeConicArcs.Q25RowCompositionData.C_0155_0159
import RelativeConicArcs.Q25RowCompositionData.C_0245_0249
import RelativeConicArcs.Q25RowCompositionData.C_0325_0329
import RelativeConicArcs.Q25RowCompositionData.C_0400_0404
import RelativeConicArcs.Q25RowCompositionData.C_0485_0489

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 7 class links (117,206) through (117,216), aligned to T_117_C_168_217_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB117C206_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C206Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0109A Q25RowCompositionData.class0109B
        Q25RowCompositionData.class0109C := by
  rfl

theorem residualTransportB117C206_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C206Payload.canonicalConfig).card := by
  rw [residualTransportB117C206_canonicalClassLink]
  exact Q25RowCompositionData.class0109LegalOrbitSet_card_ge_32

theorem residualTransportB117C207_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C207Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0063A Q25RowCompositionData.class0063B
        Q25RowCompositionData.class0063C := by
  rfl

theorem residualTransportB117C207_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C207Payload.canonicalConfig).card := by
  rw [residualTransportB117C207_canonicalClassLink]
  exact Q25RowCompositionData.class0063LegalOrbitSet_card_ge_32

theorem residualTransportB117C211_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C211Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0485A Q25RowCompositionData.class0485B
        Q25RowCompositionData.class0485C := by
  rfl

theorem residualTransportB117C211_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C211Payload.canonicalConfig).card := by
  rw [residualTransportB117C211_canonicalClassLink]
  exact Q25RowCompositionData.class0485LegalOrbitSet_card_ge_32

theorem residualTransportB117C213_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C213Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0328A Q25RowCompositionData.class0328B
        Q25RowCompositionData.class0328C := by
  rfl

theorem residualTransportB117C213_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C213Payload.canonicalConfig).card := by
  rw [residualTransportB117C213_canonicalClassLink]
  exact Q25RowCompositionData.class0328LegalOrbitSet_card_ge_32

theorem residualTransportB117C214_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C214Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0245A Q25RowCompositionData.class0245B
        Q25RowCompositionData.class0245C := by
  rfl

theorem residualTransportB117C214_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C214Payload.canonicalConfig).card := by
  rw [residualTransportB117C214_canonicalClassLink]
  exact Q25RowCompositionData.class0245LegalOrbitSet_card_ge_32

theorem residualTransportB117C215_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C215Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0155A Q25RowCompositionData.class0155B
        Q25RowCompositionData.class0155C := by
  rfl

theorem residualTransportB117C215_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C215Payload.canonicalConfig).card := by
  rw [residualTransportB117C215_canonicalClassLink]
  exact Q25RowCompositionData.class0155LegalOrbitSet_card_ge_32

theorem residualTransportB117C216_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB117C216Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0401A Q25RowCompositionData.class0401B
        Q25RowCompositionData.class0401C := by
  rfl

theorem residualTransportB117C216_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB117C216Payload.canonicalConfig).card := by
  rw [residualTransportB117C216_canonicalClassLink]
  exact Q25RowCompositionData.class0401LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
