import RelativeConicArcs.Q25ResidualTransportData.T_138_C_139_188_V_02
import RelativeConicArcs.Q25RowCompositionData.C_0705_0709
import RelativeConicArcs.Q25RowCompositionData.C_0735_0739
import RelativeConicArcs.Q25RowCompositionData.C_0765_0769

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 3 class links (138,185) through (138,187), aligned to T_138_C_139_188_V_02
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB138C185_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB138C185Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0767A Q25RowCompositionData.class0767B
        Q25RowCompositionData.class0767C := by
  rfl

theorem residualTransportB138C185_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB138C185Payload.canonicalConfig).card := by
  rw [residualTransportB138C185_canonicalClassLink]
  exact Q25RowCompositionData.class0767LegalOrbitSet_card_ge_32

theorem residualTransportB138C186_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB138C186Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0709A Q25RowCompositionData.class0709B
        Q25RowCompositionData.class0709C := by
  rfl

theorem residualTransportB138C186_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB138C186Payload.canonicalConfig).card := by
  rw [residualTransportB138C186_canonicalClassLink]
  exact Q25RowCompositionData.class0709LegalOrbitSet_card_ge_32

theorem residualTransportB138C187_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB138C187Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0736A Q25RowCompositionData.class0736B
        Q25RowCompositionData.class0736C := by
  rfl

theorem residualTransportB138C187_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB138C187Payload.canonicalConfig).card := by
  rw [residualTransportB138C187_canonicalClassLink]
  exact Q25RowCompositionData.class0736LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
