import RelativeConicArcs.Q25ResidualTransportData.T_131_C_132_181_V_01
import RelativeConicArcs.Q25RowCompositionData.C_1110_1114
import RelativeConicArcs.Q25RowCompositionData.C_1165_1169
import RelativeConicArcs.Q25RowCompositionData.C_1185_1188

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 3 class links (131,172) through (131,174), aligned to T_131_C_132_181_V_01
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB131C172_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB131C172Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1186A Q25RowCompositionData.class1186B
        Q25RowCompositionData.class1186C := by
  rfl

theorem residualTransportB131C172_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB131C172Payload.canonicalConfig).card := by
  rw [residualTransportB131C172_canonicalClassLink]
  exact Q25RowCompositionData.class1186LegalOrbitSet_card_ge_32

theorem residualTransportB131C173_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB131C173Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1168A Q25RowCompositionData.class1168B
        Q25RowCompositionData.class1168C := by
  rfl

theorem residualTransportB131C173_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB131C173Payload.canonicalConfig).card := by
  rw [residualTransportB131C173_canonicalClassLink]
  exact Q25RowCompositionData.class1168LegalOrbitSet_card_ge_32

theorem residualTransportB131C174_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB131C174Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1111A Q25RowCompositionData.class1111B
        Q25RowCompositionData.class1111C := by
  rfl

theorem residualTransportB131C174_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB131C174Payload.canonicalConfig).card := by
  rw [residualTransportB131C174_canonicalClassLink]
  exact Q25RowCompositionData.class1111LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
