import RelativeConicArcs.Q25ResidualTransportData.T_141_C_192_241_V_01
import RelativeConicArcs.Q25RowCompositionData.C_0205_0209
import RelativeConicArcs.Q25RowCompositionData.C_0290_0294
import RelativeConicArcs.Q25RowCompositionData.C_0300_0304
import RelativeConicArcs.Q25RowCompositionData.C_0375_0379
import RelativeConicArcs.Q25RowCompositionData.C_0380_0384
import RelativeConicArcs.Q25RowCompositionData.C_0525_0529
import RelativeConicArcs.Q25RowCompositionData.C_0600_0604
import RelativeConicArcs.Q25RowCompositionData.C_0675_0679

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (141,213) through (141,222), aligned to T_141_C_192_241_V_01
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB141C213_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C213Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0382A Q25RowCompositionData.class0382B
        Q25RowCompositionData.class0382C := by
  rfl

theorem residualTransportB141C213_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C213Payload.canonicalConfig).card := by
  rw [residualTransportB141C213_canonicalClassLink]
  exact Q25RowCompositionData.class0382LegalOrbitSet_card_ge_32

theorem residualTransportB141C214_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C214Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0301A Q25RowCompositionData.class0301B
        Q25RowCompositionData.class0301C := by
  rfl

theorem residualTransportB141C214_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C214Payload.canonicalConfig).card := by
  rw [residualTransportB141C214_canonicalClassLink]
  exact Q25RowCompositionData.class0301LegalOrbitSet_card_ge_32

theorem residualTransportB141C215_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C215Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0209A Q25RowCompositionData.class0209B
        Q25RowCompositionData.class0209C := by
  rfl

theorem residualTransportB141C215_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C215Payload.canonicalConfig).card := by
  rw [residualTransportB141C215_canonicalClassLink]
  exact Q25RowCompositionData.class0209LegalOrbitSet_card_ge_32

theorem residualTransportB141C217_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C217Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0294A Q25RowCompositionData.class0294B
        Q25RowCompositionData.class0294C := by
  rfl

theorem residualTransportB141C217_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C217Payload.canonicalConfig).card := by
  rw [residualTransportB141C217_canonicalClassLink]
  exact Q25RowCompositionData.class0294LegalOrbitSet_card_ge_32

theorem residualTransportB141C218_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C218Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0528A Q25RowCompositionData.class0528B
        Q25RowCompositionData.class0528C := by
  rfl

theorem residualTransportB141C218_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C218Payload.canonicalConfig).card := by
  rw [residualTransportB141C218_canonicalClassLink]
  exact Q25RowCompositionData.class0528LegalOrbitSet_card_ge_32

theorem residualTransportB141C219_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C219Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0378A Q25RowCompositionData.class0378B
        Q25RowCompositionData.class0378C := by
  rfl

theorem residualTransportB141C219_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C219Payload.canonicalConfig).card := by
  rw [residualTransportB141C219_canonicalClassLink]
  exact Q25RowCompositionData.class0378LegalOrbitSet_card_ge_32

theorem residualTransportB141C221_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C221Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0602A Q25RowCompositionData.class0602B
        Q25RowCompositionData.class0602C := by
  rfl

theorem residualTransportB141C221_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C221Payload.canonicalConfig).card := by
  rw [residualTransportB141C221_canonicalClassLink]
  exact Q25RowCompositionData.class0602LegalOrbitSet_card_ge_32

theorem residualTransportB141C222_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB141C222Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0677A Q25RowCompositionData.class0677B
        Q25RowCompositionData.class0677C := by
  rfl

theorem residualTransportB141C222_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB141C222Payload.canonicalConfig).card := by
  rw [residualTransportB141C222_canonicalClassLink]
  exact Q25RowCompositionData.class0677LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
