import RelativeConicArcs.Q25ResidualTransportData.T_162_C_163_212_V_00
import RelativeConicArcs.Q25RowCompositionData.C_0980_0984
import RelativeConicArcs.Q25RowCompositionData.C_0985_0989

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 8 class links (162,183) through (162,193), aligned to T_162_C_163_212_V_00
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `02da2a29a5ba4c1ef45d7504c65a69defc3ce22ce8ea774129906a46f2726728`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB162C183_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C183Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0982A Q25RowCompositionData.class0982B
        Q25RowCompositionData.class0982C := by
  rfl

theorem residualTransportB162C183_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C183Payload.canonicalConfig).card := by
  rw [residualTransportB162C183_canonicalClassLink]
  exact Q25RowCompositionData.class0982LegalOrbitSet_card_ge_32

theorem residualTransportB162C184_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C184Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0981A Q25RowCompositionData.class0981B
        Q25RowCompositionData.class0981C := by
  rfl

theorem residualTransportB162C184_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C184Payload.canonicalConfig).card := by
  rw [residualTransportB162C184_canonicalClassLink]
  exact Q25RowCompositionData.class0981LegalOrbitSet_card_ge_32

theorem residualTransportB162C185_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C185Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0983A Q25RowCompositionData.class0983B
        Q25RowCompositionData.class0983C := by
  rfl

theorem residualTransportB162C185_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C185Payload.canonicalConfig).card := by
  rw [residualTransportB162C185_canonicalClassLink]
  exact Q25RowCompositionData.class0983LegalOrbitSet_card_ge_32

theorem residualTransportB162C186_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C186Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0985A Q25RowCompositionData.class0985B
        Q25RowCompositionData.class0985C := by
  rfl

theorem residualTransportB162C186_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C186Payload.canonicalConfig).card := by
  rw [residualTransportB162C186_canonicalClassLink]
  exact Q25RowCompositionData.class0985LegalOrbitSet_card_ge_32

theorem residualTransportB162C189_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C189Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0984A Q25RowCompositionData.class0984B
        Q25RowCompositionData.class0984C := by
  rfl

theorem residualTransportB162C189_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C189Payload.canonicalConfig).card := by
  rw [residualTransportB162C189_canonicalClassLink]
  exact Q25RowCompositionData.class0984LegalOrbitSet_card_ge_32

theorem residualTransportB162C190_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C190Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0986A Q25RowCompositionData.class0986B
        Q25RowCompositionData.class0986C := by
  rfl

theorem residualTransportB162C190_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C190Payload.canonicalConfig).card := by
  rw [residualTransportB162C190_canonicalClassLink]
  exact Q25RowCompositionData.class0986LegalOrbitSet_card_ge_32

theorem residualTransportB162C191_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C191Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0989A Q25RowCompositionData.class0989B
        Q25RowCompositionData.class0989C := by
  rfl

theorem residualTransportB162C191_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C191Payload.canonicalConfig).card := by
  rw [residualTransportB162C191_canonicalClassLink]
  exact Q25RowCompositionData.class0989LegalOrbitSet_card_ge_32

theorem residualTransportB162C193_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB162C193Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0988A Q25RowCompositionData.class0988B
        Q25RowCompositionData.class0988C := by
  rfl

theorem residualTransportB162C193_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB162C193Payload.canonicalConfig).card := by
  rw [residualTransportB162C193_canonicalClassLink]
  exact Q25RowCompositionData.class0988LegalOrbitSet_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
