import RelativeConicArcs.Q25ResidualTransportData.T_186_C_237_286_V_00
import RelativeConicArcs.Q25RowCompositionData.C_0885_0889
import RelativeConicArcs.Q25RowCompositionData.C_0950_0954
import RelativeConicArcs.Q25RowCompositionData.C_1070_1074
import RelativeConicArcs.Q25RowCompositionData.C_1115_1119
import RelativeConicArcs.Q25RowCompositionData.C_1170_1174
import RelativeConicArcs.Q25RowCompositionData.C_1180_1184

/-!
# Generated C151 residual canonical-class links

DO NOT EDIT: generated by `notes/2026-07-16-c151-residual-class-link-generator.py`.

* payload: 6 class links (186,240) through (186,249), aligned to T_186_C_237_286_V_00
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* class-link generator SHA256: `c0ab5f00f995d8e80f295c243ba0d8aee3b659ac12ccb309a2a1f6adbb84d5bd`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualClassLinkData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25ResidualCoverData

theorem residualTransportB186C240_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB186C240Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1172A Q25RowCompositionData.class1172B
        Q25RowCompositionData.class1172C := by
  rfl

theorem residualTransportB186C240_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB186C240Payload.canonicalConfig).card := by
  rw [residualTransportB186C240_canonicalClassLink]
  exact Q25RowCompositionData.class1172LegalOrbitSet_card_ge_32

theorem residualTransportB186C240_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C240Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C240Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB186C240_transportValid hsource
    residualTransportB186C240_canonical_card_ge_32

theorem residualTransportB186C242_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB186C242Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1182A Q25RowCompositionData.class1182B
        Q25RowCompositionData.class1182C := by
  rfl

theorem residualTransportB186C242_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB186C242Payload.canonicalConfig).card := by
  rw [residualTransportB186C242_canonicalClassLink]
  exact Q25RowCompositionData.class1182LegalOrbitSet_card_ge_32

theorem residualTransportB186C242_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C242Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C242Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB186C242_transportValid hsource
    residualTransportB186C242_canonical_card_ge_32

theorem residualTransportB186C243_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB186C243Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1119A Q25RowCompositionData.class1119B
        Q25RowCompositionData.class1119C := by
  rfl

theorem residualTransportB186C243_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB186C243Payload.canonicalConfig).card := by
  rw [residualTransportB186C243_canonicalClassLink]
  exact Q25RowCompositionData.class1119LegalOrbitSet_card_ge_32

theorem residualTransportB186C243_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C243Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C243Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB186C243_transportValid hsource
    residualTransportB186C243_canonical_card_ge_32

theorem residualTransportB186C247_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB186C247Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0950A Q25RowCompositionData.class0950B
        Q25RowCompositionData.class0950C := by
  rfl

theorem residualTransportB186C247_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB186C247Payload.canonicalConfig).card := by
  rw [residualTransportB186C247_canonicalClassLink]
  exact Q25RowCompositionData.class0950LegalOrbitSet_card_ge_32

theorem residualTransportB186C247_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C247Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C247Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB186C247_transportValid hsource
    residualTransportB186C247_canonical_card_ge_32

theorem residualTransportB186C248_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB186C248Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class1071A Q25RowCompositionData.class1071B
        Q25RowCompositionData.class1071C := by
  rfl

theorem residualTransportB186C248_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB186C248Payload.canonicalConfig).card := by
  rw [residualTransportB186C248_canonicalClassLink]
  exact Q25RowCompositionData.class1071LegalOrbitSet_card_ge_32

theorem residualTransportB186C248_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C248Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C248Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB186C248_transportValid hsource
    residualTransportB186C248_canonical_card_ge_32

theorem residualTransportB186C249_canonicalClassLink :
    Q25ResidualTransportData.residualTransportB186C249Payload.canonicalConfig =
      normalizedConfig Q25RowCompositionData.class0888A Q25RowCompositionData.class0888B
        Q25RowCompositionData.class0888C := by
  rfl

theorem residualTransportB186C249_canonical_card_ge_32 :
    32 ≤ (legalOrbitSet
      Q25ResidualTransportData.residualTransportB186C249Payload.canonicalConfig).card := by
  rw [residualTransportB186C249_canonicalClassLink]
  exact Q25RowCompositionData.class0888LegalOrbitSet_card_ge_32

theorem residualTransportB186C249_source_card_ge_32
    (hsource : RawCap (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C249Payload.c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨186, by decide⟩
      Q25ResidualTransportData.residualTransportB186C249Payload.c)).card := by
  exact ValidRowPayload.source_card_ge_of_canonical
    Q25ResidualTransportData.residualTransportB186C249_transportValid hsource
    residualTransportB186C249_canonical_card_ge_32

end Q25ResidualClassLinkData
end RelativeConicArcs
