import RelativeConicArcs.Q25ResidualCoverData.Schema

/-!
# Generated C151 residual-cover payload

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-cover-generator.py`
from the independently checked C++ residual-cover stream.  These are payload records,
not semantic certificates; the row-level residual transport bridge is intentionally
handwritten downstream.

* payload: 50 normalized rows (34,135) through (34,184)
* generator SHA256: `70183fc83d291004ce18b8a4a55110ef34bd8baeb531b0465f01f1702116347a`
* enumerator SHA256: `73d442df3be986c1082af8e3498ddd0496c09b86dd24963ea6d887a8f9b7680d`
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* semantic FNV-1a-64: `37b674bfe4316ee6`
* class order: lexicographic C150 internal-orbit canonical triples
-/

namespace RelativeConicArcs
namespace Q25ResidualCoverData

def residualCoverRow034C135_184 : Array ResidualRowPayload := #[
  .bad { c := ⟨135, by decide⟩, i := ⟨2, by decide⟩, j := ⟨5, by decide⟩, k := ⟨6, by decide⟩ },
  .valid { c := ⟨136, by decide⟩, classIndex := ⟨349, by decide⟩, canonicalB := ⟨46, by decide⟩, canonicalC := ⟨62, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 9, legalCount := 37, orbitSize := 400 },
  .bad { c := ⟨137, by decide⟩, i := ⟨2, by decide⟩, j := ⟨3, by decide⟩, k := ⟨6, by decide⟩ },
  .valid { c := ⟨138, by decide⟩, classIndex := ⟨502, by decide⟩, canonicalB := ⟨46, by decide⟩, canonicalC := ⟨64, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 9, legalCount := 41, orbitSize := 400 },
  .valid { c := ⟨139, by decide⟩, classIndex := ⟨184, by decide⟩, canonicalB := ⟨46, by decide⟩, canonicalC := ⟨60, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 9, legalCount := 41, orbitSize := 400 },
  .valid { c := ⟨140, by decide⟩, classIndex := ⟨358, by decide⟩, canonicalB := ⟨62, by decide⟩, canonicalC := ⟨90, by decide⟩, y := GF25.ofNat 17, z := GF25.ofNat 10, legalCount := 40, orbitSize := 400 },
  .valid { c := ⟨141, by decide⟩, classIndex := ⟨512, by decide⟩, canonicalB := ⟨64, by decide⟩, canonicalC := ⟨92, by decide⟩, y := GF25.ofNat 17, z := GF25.ofNat 11, legalCount := 37, orbitSize := 400 },
  .valid { c := ⟨142, by decide⟩, classIndex := ⟨276, by decide⟩, canonicalB := ⟨61, by decide⟩, canonicalC := ⟨94, by decide⟩, y := GF25.ofNat 17, z := GF25.ofNat 12, legalCount := 38, orbitSize := 400 },
  .valid { c := ⟨143, by decide⟩, classIndex := ⟨434, by decide⟩, canonicalB := ⟨63, by decide⟩, canonicalC := ⟨91, by decide⟩, y := GF25.ofNat 17, z := GF25.ofNat 13, legalCount := 39, orbitSize := 400 },
  .valid { c := ⟨144, by decide⟩, classIndex := ⟨192, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨93, by decide⟩, y := GF25.ofNat 17, z := GF25.ofNat 14, legalCount := 43, orbitSize := 400 },
  .bad { c := ⟨145, by decide⟩, i := ⟨1, by decide⟩, j := ⟨2, by decide⟩, k := ⟨7, by decide⟩ },
  .valid { c := ⟨146, by decide⟩, classIndex := ⟨649, by decide⟩, canonicalB := ⟨46, by decide⟩, canonicalC := ⟨72, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 9, legalCount := 37, orbitSize := 400 },
  .bad { c := ⟨147, by decide⟩, i := ⟨2, by decide⟩, j := ⟨5, by decide⟩, k := ⟨7, by decide⟩ },
  .valid { c := ⟨148, by decide⟩, classIndex := ⟨579, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨82, by decide⟩, y := GF25.ofNat 17, z := GF25.ofNat 8, legalCount := 38, orbitSize := 400 },
  .bad { c := ⟨149, by decide⟩, i := ⟨1, by decide⟩, j := ⟨4, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨150, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨151, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨152, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨153, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨154, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨155, by decide⟩, i := ⟨1, by decide⟩, j := ⟨2, by decide⟩, k := ⟨6, by decide⟩ },
  .valid { c := ⟨156, by decide⟩, classIndex := ⟨754, by decide⟩, canonicalB := ⟨31, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 42, orbitSize := 400 },
  .valid { c := ⟨157, by decide⟩, classIndex := ⟨723, by decide⟩, canonicalB := ⟨31, by decide⟩, canonicalC := ⟨108, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 41, orbitSize := 400 },
  .bad { c := ⟨158, by decide⟩, i := ⟨2, by decide⟩, j := ⟨3, by decide⟩, k := ⟨6, by decide⟩ },
  .bad { c := ⟨159, by decide⟩, i := ⟨1, by decide⟩, j := ⟨4, by decide⟩, k := ⟨6, by decide⟩ },
  .bad { c := ⟨160, by decide⟩, i := ⟨2, by decide⟩, j := ⟨4, by decide⟩, k := ⟨6, by decide⟩ },
  .valid { c := ⟨161, by decide⟩, classIndex := ⟨1017, by decide⟩, canonicalB := ⟨31, by decide⟩, canonicalC := ⟨114, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 42, orbitSize := 400 },
  .valid { c := ⟨162, by decide⟩, classIndex := ⟨957, by decide⟩, canonicalB := ⟨31, by decide⟩, canonicalC := ⟨113, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 42, orbitSize := 400 },
  .valid { c := ⟨163, by decide⟩, classIndex := ⟨897, by decide⟩, canonicalB := ⟨31, by decide⟩, canonicalC := ⟨112, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 39, orbitSize := 400 },
  .valid { c := ⟨164, by decide⟩, classIndex := ⟨841, by decide⟩, canonicalB := ⟨31, by decide⟩, canonicalC := ⟨111, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 44, orbitSize := 400 },
  .valid { c := ⟨165, by decide⟩, classIndex := ⟨809, by decide⟩, canonicalB := ⟨110, by decide⟩, canonicalC := ⟨138, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 15, legalCount := 41, orbitSize := 400 },
  .valid { c := ⟨166, by decide⟩, classIndex := ⟨984, by decide⟩, canonicalB := ⟨113, by decide⟩, canonicalC := ⟨136, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 16, legalCount := 41, orbitSize := 400 },
  .bad { c := ⟨167, by decide⟩, i := ⟨2, by decide⟩, j := ⟨4, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨168, by decide⟩, i := ⟨4, by decide⟩, j := ⟨5, by decide⟩, k := ⟨6, by decide⟩ },
  .valid { c := ⟨169, by decide⟩, classIndex := ⟨924, by decide⟩, canonicalB := ⟨112, by decide⟩, canonicalC := ⟨135, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 19, legalCount := 42, orbitSize := 400 },
  .bad { c := ⟨170, by decide⟩, i := ⟨1, by decide⟩, j := ⟨2, by decide⟩, k := ⟨7, by decide⟩ },
  .valid { c := ⟨171, by decide⟩, classIndex := ⟨1107, by decide⟩, canonicalB := ⟨121, by decide⟩, canonicalC := ⟨147, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 21, legalCount := 41, orbitSize := 400 },
  .bad { c := ⟨172, by decide⟩, i := ⟨2, by decide⟩, j := ⟨5, by decide⟩, k := ⟨6, by decide⟩ },
  .bad { c := ⟨173, by decide⟩, i := ⟨2, by decide⟩, j := ⟨5, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨174, by decide⟩, i := ⟨1, by decide⟩, j := ⟨4, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨175, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨176, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨177, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨178, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨179, by decide⟩, i := ⟨1, by decide⟩, j := ⟨6, by decide⟩, k := ⟨7, by decide⟩ },
  .bad { c := ⟨180, by decide⟩, i := ⟨1, by decide⟩, j := ⟨2, by decide⟩, k := ⟨6, by decide⟩ },
  .valid { c := ⟨181, by decide⟩, classIndex := ⟨78, by decide⟩, canonicalB := ⟨49, by decide⟩, canonicalC := ⟨58, by decide⟩, y := GF25.ofNat 15, z := GF25.ofNat 24, legalCount := 42, orbitSize := 400 },
  .valid { c := ⟨182, by decide⟩, classIndex := ⟨27, by decide⟩, canonicalB := ⟨49, by decide⟩, canonicalC := ⟨57, by decide⟩, y := GF25.ofNat 15, z := GF25.ofNat 24, legalCount := 42, orbitSize := 400 },
  .bad { c := ⟨183, by decide⟩, i := ⟨4, by decide⟩, j := ⟨5, by decide⟩, k := ⟨6, by decide⟩ },
  .bad { c := ⟨184, by decide⟩, i := ⟨1, by decide⟩, j := ⟨4, by decide⟩, k := ⟨6, by decide⟩ },
]

end Q25ResidualCoverData
end RelativeConicArcs
