import WeightedRules.TableProgram
import WeightedRules.IncrementalReflection
import WeightedRules.OutputConvergence

/-!
# Round conventions on domain 6: producer against synchronous iterate

Generated by `generate_round_convention.py` from `domain-6.json`, itself written by
the producer's `lean_boundary_fixtures` generator. Every source has domain
6, one binary input relation `edge`, one unary derived relation `dist`
with the rule `dist(y) :- dist(x), edge(x, y)`, and the fact `dist(0) = 0`; the
grounding has 43 scalar coordinates. All tables are read from the fixture
file by the elaborator; nothing numeric is transcribed here except the round
counts named in the statements.

For each case, kernel reduction establishes three facts about the producer's
numbers. First, the round count returned with the from-zero certificate is the
least index at which the synchronous iterate from the zero valuation equals
the certified values: the certificate is accepted at that count and rejected at
the preceding one. Second, the sweep count returned by the producer's
incremental update from the held solution is the least replay count at which
the warm iterate from the old values equals the new values, and it lies within
the rule-output bound. Third, three single mutations of each certificate, a
unit perturbation of one finite coordinate, a swap of two distinct values and
a dropped entry, are rejected by the same checker.
-/

namespace WeightedRules.RoundConvention

set_option maxRecDepth 32768
set_option maxHeartbeats 4000000

/-- Case `case0`: the producer's grounding of the base source. -/
def programSix0 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "grounding", "products"])

/-- Case `case0`: the certified from-zero values. -/
def valuesSix0 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "certificate", "values"])

example : checkCertificate programSix0 5 valuesSix0 = true := by decide +kernel
example : checkCertificate programSix0 4 valuesSix0 = false := by decide +kernel

/-- Case `case0`: the producer's grounding of the improved source. -/
def improvedSix0 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "improvement", "grounding", "products"])

/-- Case `case0`: the values after the incremental update. -/
def improvedValuesSix0 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "improvement", "values"])

example : checkImprovementCertificate programSix0 improvedSix0 valuesSix0 5 improvedValuesSix0 = true := by
  decide +kernel
example : checkImprovementCertificate programSix0 improvedSix0 valuesSix0 4 improvedValuesSix0 = false := by
  decide +kernel
example : 5 ≤ ruleOutputBound improvedSix0 := by decide +kernel

example : checkCertificate programSix0 5
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix0 5
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix0 5
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case0", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case1`: the producer's grounding of the base source. -/
def programSix1 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "grounding", "products"])

/-- Case `case1`: the certified from-zero values. -/
def valuesSix1 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "certificate", "values"])

example : checkCertificate programSix1 3 valuesSix1 = true := by decide +kernel
example : checkCertificate programSix1 2 valuesSix1 = false := by decide +kernel

/-- Case `case1`: the producer's grounding of the improved source. -/
def improvedSix1 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "improvement", "grounding", "products"])

/-- Case `case1`: the values after the incremental update. -/
def improvedValuesSix1 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "improvement", "values"])

example : checkImprovementCertificate programSix1 improvedSix1 valuesSix1 3 improvedValuesSix1 = true := by
  decide +kernel
example : checkImprovementCertificate programSix1 improvedSix1 valuesSix1 2 improvedValuesSix1 = false := by
  decide +kernel
example : 3 ≤ ruleOutputBound improvedSix1 := by decide +kernel

example : checkCertificate programSix1 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix1 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix1 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case1", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case2`: the producer's grounding of the base source. -/
def programSix2 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "grounding", "products"])

/-- Case `case2`: the certified from-zero values. -/
def valuesSix2 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "certificate", "values"])

example : checkCertificate programSix2 5 valuesSix2 = true := by decide +kernel
example : checkCertificate programSix2 4 valuesSix2 = false := by decide +kernel

/-- Case `case2`: the producer's grounding of the improved source. -/
def improvedSix2 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "improvement", "grounding", "products"])

/-- Case `case2`: the values after the incremental update. -/
def improvedValuesSix2 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "improvement", "values"])

example : checkImprovementCertificate programSix2 improvedSix2 valuesSix2 3 improvedValuesSix2 = true := by
  decide +kernel
example : checkImprovementCertificate programSix2 improvedSix2 valuesSix2 2 improvedValuesSix2 = false := by
  decide +kernel
example : 3 ≤ ruleOutputBound improvedSix2 := by decide +kernel

example : checkCertificate programSix2 5
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix2 5
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix2 5
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case2", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case3`: the producer's grounding of the base source. -/
def programSix3 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "grounding", "products"])

/-- Case `case3`: the certified from-zero values. -/
def valuesSix3 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "certificate", "values"])

example : checkCertificate programSix3 4 valuesSix3 = true := by decide +kernel
example : checkCertificate programSix3 3 valuesSix3 = false := by decide +kernel

/-- Case `case3`: the producer's grounding of the improved source. -/
def improvedSix3 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "improvement", "grounding", "products"])

/-- Case `case3`: the values after the incremental update. -/
def improvedValuesSix3 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "improvement", "values"])

example : checkImprovementCertificate programSix3 improvedSix3 valuesSix3 3 improvedValuesSix3 = true := by
  decide +kernel
example : checkImprovementCertificate programSix3 improvedSix3 valuesSix3 2 improvedValuesSix3 = false := by
  decide +kernel
example : 3 ≤ ruleOutputBound improvedSix3 := by decide +kernel

example : checkCertificate programSix3 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix3 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix3 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case3", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case4`: the producer's grounding of the base source. -/
def programSix4 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "grounding", "products"])

/-- Case `case4`: the certified from-zero values. -/
def valuesSix4 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "certificate", "values"])

example : checkCertificate programSix4 3 valuesSix4 = true := by decide +kernel
example : checkCertificate programSix4 2 valuesSix4 = false := by decide +kernel

/-- Case `case4`: the producer's grounding of the improved source. -/
def improvedSix4 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "improvement", "grounding", "products"])

/-- Case `case4`: the values after the incremental update. -/
def improvedValuesSix4 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "improvement", "values"])

example : checkImprovementCertificate programSix4 improvedSix4 valuesSix4 4 improvedValuesSix4 = true := by
  decide +kernel
example : checkImprovementCertificate programSix4 improvedSix4 valuesSix4 3 improvedValuesSix4 = false := by
  decide +kernel
example : 4 ≤ ruleOutputBound improvedSix4 := by decide +kernel

example : checkCertificate programSix4 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix4 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix4 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case4", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case5`: the producer's grounding of the base source. -/
def programSix5 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "grounding", "products"])

/-- Case `case5`: the certified from-zero values. -/
def valuesSix5 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "certificate", "values"])

example : checkCertificate programSix5 4 valuesSix5 = true := by decide +kernel
example : checkCertificate programSix5 3 valuesSix5 = false := by decide +kernel

/-- Case `case5`: the producer's grounding of the improved source. -/
def improvedSix5 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "improvement", "grounding", "products"])

/-- Case `case5`: the values after the incremental update. -/
def improvedValuesSix5 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "improvement", "values"])

example : checkImprovementCertificate programSix5 improvedSix5 valuesSix5 3 improvedValuesSix5 = true := by
  decide +kernel
example : checkImprovementCertificate programSix5 improvedSix5 valuesSix5 2 improvedValuesSix5 = false := by
  decide +kernel
example : 3 ≤ ruleOutputBound improvedSix5 := by decide +kernel

example : checkCertificate programSix5 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix5 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix5 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case5", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case6`: the producer's grounding of the base source. -/
def programSix6 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "grounding", "products"])

/-- Case `case6`: the certified from-zero values. -/
def valuesSix6 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "certificate", "values"])

example : checkCertificate programSix6 4 valuesSix6 = true := by decide +kernel
example : checkCertificate programSix6 3 valuesSix6 = false := by decide +kernel

/-- Case `case6`: the producer's grounding of the improved source. -/
def improvedSix6 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "improvement", "grounding", "products"])

/-- Case `case6`: the values after the incremental update. -/
def improvedValuesSix6 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "improvement", "values"])

example : checkImprovementCertificate programSix6 improvedSix6 valuesSix6 3 improvedValuesSix6 = true := by
  decide +kernel
example : checkImprovementCertificate programSix6 improvedSix6 valuesSix6 2 improvedValuesSix6 = false := by
  decide +kernel
example : 3 ≤ ruleOutputBound improvedSix6 := by decide +kernel

example : checkCertificate programSix6 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix6 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix6 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case6", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case7`: the producer's grounding of the base source. -/
def programSix7 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "grounding", "products"])

/-- Case `case7`: the certified from-zero values. -/
def valuesSix7 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "certificate", "values"])

example : checkCertificate programSix7 3 valuesSix7 = true := by decide +kernel
example : checkCertificate programSix7 2 valuesSix7 = false := by decide +kernel

/-- Case `case7`: the producer's grounding of the improved source. -/
def improvedSix7 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "improvement", "grounding", "products"])

/-- Case `case7`: the values after the incremental update. -/
def improvedValuesSix7 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "improvement", "values"])

example : checkImprovementCertificate programSix7 improvedSix7 valuesSix7 4 improvedValuesSix7 = true := by
  decide +kernel
example : checkImprovementCertificate programSix7 improvedSix7 valuesSix7 3 improvedValuesSix7 = false := by
  decide +kernel
example : 4 ≤ ruleOutputBound improvedSix7 := by decide +kernel

example : checkCertificate programSix7 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix7 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix7 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case7", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case8`: the producer's grounding of the base source. -/
def programSix8 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "grounding", "products"])

/-- Case `case8`: the certified from-zero values. -/
def valuesSix8 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "certificate", "values"])

example : checkCertificate programSix8 4 valuesSix8 = true := by decide +kernel
example : checkCertificate programSix8 3 valuesSix8 = false := by decide +kernel

/-- Case `case8`: the producer's grounding of the improved source. -/
def improvedSix8 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "improvement", "grounding", "products"])

/-- Case `case8`: the values after the incremental update. -/
def improvedValuesSix8 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "improvement", "values"])

example : checkImprovementCertificate programSix8 improvedSix8 valuesSix8 3 improvedValuesSix8 = true := by
  decide +kernel
example : checkImprovementCertificate programSix8 improvedSix8 valuesSix8 2 improvedValuesSix8 = false := by
  decide +kernel
example : 3 ≤ ruleOutputBound improvedSix8 := by decide +kernel

example : checkCertificate programSix8 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix8 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix8 4
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case8", "rejected", "swap"])) = false := by
  decide +kernel

/-- Case `case9`: the producer's grounding of the base source. -/
def programSix9 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "grounding", "products"])

/-- Case `case9`: the certified from-zero values. -/
def valuesSix9 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "certificate", "values"])

example : checkCertificate programSix9 3 valuesSix9 = true := by decide +kernel
example : checkCertificate programSix9 2 valuesSix9 = false := by decide +kernel

/-- Case `case9`: the producer's grounding of the improved source. -/
def improvedSix9 : Program Cost 43 := programOfTables 43
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "improvement", "grounding", "inputs"])
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "improvement", "grounding", "products"])

/-- Case `case9`: the values after the incremental update. -/
def improvedValuesSix9 : List Cost := costList
  (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "improvement", "values"])

example : checkImprovementCertificate programSix9 improvedSix9 valuesSix9 4 improvedValuesSix9 = true := by
  decide +kernel
example : checkImprovementCertificate programSix9 improvedSix9 valuesSix9 3 improvedValuesSix9 = false := by
  decide +kernel
example : 4 ≤ ruleOutputBound improvedSix9 := by decide +kernel

example : checkCertificate programSix9 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "rejected", "drop"])) = false := by
  decide +kernel

example : checkCertificate programSix9 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "rejected", "perturb"])) = false := by
  decide +kernel

example : checkCertificate programSix9 3
    (costList (nat_table_from_json "../fixtures/round-convention/domain-6.json" at ["cases", "case9", "rejected", "swap"])) = false := by
  decide +kernel

end WeightedRules.RoundConvention
