import RelativeConicArcs.Q25ClassBoundData.Bridge
import RelativeConicArcs.Q25RowCompositionData.C_0360_0364
import RelativeConicArcs.Q25RowCompositionData.C_0365_0369

/-!
# Generated C151 residual-class lower bounds

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-cover-generator.py`.
Each leaf combines a literal `classNNNNAllowed` cardinality check with its existing
sound `RowCompositionCertificate`; no upper exactness claim is used.

* payload: class lower bounds 360 through 369
* generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* enumerator SHA256: `73d442df3be986c1082af8e3498ddd0496c09b86dd24963ea6d887a8f9b7680d`
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* minimum class IDs: `0065,0267,0445,0772,1002`
-/

namespace RelativeConicArcs
namespace Q25ClassBoundData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open Q25RowCompositionData

theorem class0360Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0360Allowed).card := by
  decide

theorem class0360LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0360A class0360B class0360C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0360Allowed_card_ge_33 class0360RowCertificate

theorem class0361Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0361Allowed).card := by
  decide

theorem class0361LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0361A class0361B class0361C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0361Allowed_card_ge_33 class0361RowCertificate

theorem class0362Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0362Allowed).card := by
  decide

theorem class0362LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0362A class0362B class0362C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0362Allowed_card_ge_33 class0362RowCertificate

theorem class0363Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0363Allowed).card := by
  decide

theorem class0363LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0363A class0363B class0363C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0363Allowed_card_ge_33 class0363RowCertificate

theorem class0364Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0364Allowed).card := by
  decide

theorem class0364LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0364A class0364B class0364C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0364Allowed_card_ge_33 class0364RowCertificate

theorem class0365Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0365Allowed).card := by
  decide

theorem class0365LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0365A class0365B class0365C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0365Allowed_card_ge_33 class0365RowCertificate

theorem class0366Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0366Allowed).card := by
  decide

theorem class0366LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0366A class0366B class0366C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0366Allowed_card_ge_33 class0366RowCertificate

theorem class0367Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0367Allowed).card := by
  decide

theorem class0367LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0367A class0367B class0367C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0367Allowed_card_ge_33 class0367RowCertificate

theorem class0368Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0368Allowed).card := by
  decide

theorem class0368LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0368A class0368B class0368C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0368Allowed_card_ge_33 class0368RowCertificate

theorem class0369Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0369Allowed).card := by
  decide

theorem class0369LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0369A class0369B class0369C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0369Allowed_card_ge_33 class0369RowCertificate

end Q25ClassBoundData
end RelativeConicArcs
