import RelativeConicArcs.Q25ClassBoundData.Bridge
import RelativeConicArcs.Q25RowCompositionData.C_0510_0514
import RelativeConicArcs.Q25RowCompositionData.C_0515_0519

/-!
# Generated C151 residual-class lower bounds

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-cover-generator.py`.
Each leaf combines a literal `classNNNNAllowed` cardinality check with its existing
sound `RowCompositionCertificate`; no upper exactness claim is used.

* payload: class lower bounds 510 through 519
* generator SHA256: `70183fc83d291004ce18b8a4a55110ef34bd8baeb531b0465f01f1702116347a`
* enumerator SHA256: `73d442df3be986c1082af8e3498ddd0496c09b86dd24963ea6d887a8f9b7680d`
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* minimum class IDs: `0065,0267,0445,0772,1002`
-/

namespace RelativeConicArcs
namespace Q25ClassBoundData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open Q25RowCompositionData

theorem class0510Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0510Allowed).card := by
  decide

theorem class0510LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0510A class0510B class0510C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0510Allowed_card_ge_33 class0510RowCertificate

theorem class0511Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0511Allowed).card := by
  decide

theorem class0511LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0511A class0511B class0511C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0511Allowed_card_ge_33 class0511RowCertificate

theorem class0512Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0512Allowed).card := by
  decide

theorem class0512LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0512A class0512B class0512C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0512Allowed_card_ge_33 class0512RowCertificate

theorem class0513Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0513Allowed).card := by
  decide

theorem class0513LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0513A class0513B class0513C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0513Allowed_card_ge_33 class0513RowCertificate

theorem class0514Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0514Allowed).card := by
  decide

theorem class0514LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0514A class0514B class0514C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0514Allowed_card_ge_33 class0514RowCertificate

theorem class0515Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0515Allowed).card := by
  decide

theorem class0515LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0515A class0515B class0515C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0515Allowed_card_ge_33 class0515RowCertificate

theorem class0516Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0516Allowed).card := by
  decide

theorem class0516LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0516A class0516B class0516C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0516Allowed_card_ge_33 class0516RowCertificate

theorem class0517Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0517Allowed).card := by
  decide

theorem class0517LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0517A class0517B class0517C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0517Allowed_card_ge_33 class0517RowCertificate

theorem class0518Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0518Allowed).card := by
  decide

theorem class0518LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0518A class0518B class0518C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0518Allowed_card_ge_33 class0518RowCertificate

theorem class0519Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0519Allowed).card := by
  decide

theorem class0519LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0519A class0519B class0519C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0519Allowed_card_ge_33 class0519RowCertificate

end Q25ClassBoundData
end RelativeConicArcs
