import RelativeConicArcs.Q25ClassBoundData.Bridge
import RelativeConicArcs.Q25RowCompositionData.C_0730_0734
import RelativeConicArcs.Q25RowCompositionData.C_0735_0739

/-!
# Generated C151 residual-class lower bounds

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-cover-generator.py`.
Each leaf combines a literal `classNNNNAllowed` cardinality check with its existing
sound `RowCompositionCertificate`; no upper exactness claim is used.

* payload: class lower bounds 730 through 739
* generator SHA256: `70183fc83d291004ce18b8a4a55110ef34bd8baeb531b0465f01f1702116347a`
* enumerator SHA256: `73d442df3be986c1082af8e3498ddd0496c09b86dd24963ea6d887a8f9b7680d`
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* minimum class IDs: `0065,0267,0445,0772,1002`
-/

namespace RelativeConicArcs
namespace Q25ClassBoundData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open Q25RowCompositionData

theorem class0730Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0730Allowed).card := by
  decide

theorem class0730LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0730A class0730B class0730C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0730Allowed_card_ge_33 class0730RowCertificate

theorem class0731Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0731Allowed).card := by
  decide

theorem class0731LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0731A class0731B class0731C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0731Allowed_card_ge_33 class0731RowCertificate

theorem class0732Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0732Allowed).card := by
  decide

theorem class0732LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0732A class0732B class0732C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0732Allowed_card_ge_33 class0732RowCertificate

theorem class0733Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0733Allowed).card := by
  decide

theorem class0733LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0733A class0733B class0733C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0733Allowed_card_ge_33 class0733RowCertificate

theorem class0734Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0734Allowed).card := by
  decide

theorem class0734LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0734A class0734B class0734C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0734Allowed_card_ge_33 class0734RowCertificate

theorem class0735Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0735Allowed).card := by
  decide

theorem class0735LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0735A class0735B class0735C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0735Allowed_card_ge_33 class0735RowCertificate

theorem class0736Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0736Allowed).card := by
  decide

theorem class0736LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0736A class0736B class0736C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0736Allowed_card_ge_33 class0736RowCertificate

theorem class0737Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0737Allowed).card := by
  decide

theorem class0737LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0737A class0737B class0737C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0737Allowed_card_ge_33 class0737RowCertificate

theorem class0738Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0738Allowed).card := by
  decide

theorem class0738LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0738A class0738B class0738C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0738Allowed_card_ge_33 class0738RowCertificate

theorem class0739Allowed_card_ge_33 :
    33 ≤ (maskOrbitSet class0739Allowed).card := by
  decide

theorem class0739LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet (normalizedConfig class0739A class0739B class0739C)).card :=
  card_legalOrbitSet_ge_of_rowCertificate
    class0739Allowed_card_ge_33 class0739RowCertificate

end Q25ClassBoundData
end RelativeConicArcs
