import RelativeConicArcs.Q25ResidualDispatchData.D_R_142_C_143_192
import RelativeConicArcs.Q25RowCompositionStrictData.C_0720_0724
import RelativeConicArcs.Q25RowCompositionStrictData.C_0745_0749
import RelativeConicArcs.Q25RowCompositionStrictData.C_0765_0769
import RelativeConicArcs.Q25RowCompositionStrictData.C_0800_0804
import RelativeConicArcs.Q25RowCompositionStrictData.C_0825_0829
import RelativeConicArcs.Q25RowCompositionStrictData.C_0830_0834
import RelativeConicArcs.Q25RowCompositionStrictData.C_0880_0884
import RelativeConicArcs.Q25RowCompositionStrictData.C_0915_0919
import RelativeConicArcs.Q25RowCompositionStrictData.C_0935_0939
import RelativeConicArcs.Q25RowCompositionStrictData.C_0940_0944
import RelativeConicArcs.Q25RowCompositionStrictData.C_0975_0979
import RelativeConicArcs.Q25RowCompositionStrictData.C_1005_1009
import RelativeConicArcs.Q25RowCompositionStrictData.C_1060_1064
import RelativeConicArcs.Q25RowCompositionStrictData.C_1065_1069
import RelativeConicArcs.Q25RowCompositionStrictData.C_1090_1094
import RelativeConicArcs.Q25RowCompositionStrictData.C_1095_1099
import RelativeConicArcs.Q25RowCompositionStrictData.C_1115_1119
import RelativeConicArcs.Q25RowCompositionStrictData.C_1150_1154
import RelativeConicArcs.Q25RowCompositionStrictData.C_1170_1174
import RelativeConicArcs.Q25RowCompositionStrictData.C_1175_1179
import RelativeConicArcs.Q25ExhaustionBridge

/-!
# Generated C151 per-row exhaustion disjunctions

DO NOT EDIT: generated by `notes/2026-07-18-c151-exhaustion-conclusion-generator.py`.

* payload: 50 per-row exhaustion disjunctions in R_142_C_143_192
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* mask-stream digest: `7b81e34650fd7f1607332cd6845a56e477a01e80b832dab06fbfcbcc0cbd55e0`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* strict-bound generator SHA256: `ae3000367fb9ddc8a3f8e9d23a42af768259428444563d1620e281a4d2244e56`
* exhaustion-conclusion generator SHA256: `c11d9ad4b6a684cf1a89b398e8ed41dfd4dbd233f49d7b6d93ef073ba600fef0`
-/


namespace RelativeConicArcs
namespace Q25ExhaustionConclusionData

open Q25Coordinates Q25MinimumMask Q25ResidualCoverData Q25ResidualEquality

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem concludeExhR_142_C_143_192 (i : Fin 50)
    (hraw : RawCap (rowConfig ⟨142, by decide⟩
      (residualCoverRow142C143_192[i]).c)) :
    33 ≤ (legalOrbitSet (rowConfig ⟨142, by decide⟩
      (residualCoverRow142C143_192[i]).c)).card ∨
      IsMinimumResidualClass (rowConfig ⟨142, by decide⟩
        (residualCoverRow142C143_192[i]).c) := by
  have hvalid := Q25ResidualDispatchData.dispatchR_142_C_143_192 i
  fin_cases i
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0749LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0721LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0825LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1060LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0939LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0881LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0833LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1006LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1066LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0944LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1179LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1174LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1118LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0917LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0803LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0977LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1091LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1151LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class1096LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0769LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim

end Q25ExhaustionConclusionData
end RelativeConicArcs
