import RelativeConicArcs.Q25ResidualDispatchData.D_R_144_C_195_244
import RelativeConicArcs.Q25RowCompositionStrictData.C_0030_0034
import RelativeConicArcs.Q25RowCompositionStrictData.C_0090_0094
import RelativeConicArcs.Q25RowCompositionStrictData.C_0130_0134
import RelativeConicArcs.Q25RowCompositionStrictData.C_0140_0144
import RelativeConicArcs.Q25RowCompositionStrictData.C_0210_0214
import RelativeConicArcs.Q25RowCompositionStrictData.C_0295_0299
import RelativeConicArcs.Q25RowCompositionStrictData.C_0305_0309
import RelativeConicArcs.Q25RowCompositionStrictData.C_0380_0384
import RelativeConicArcs.Q25RowCompositionStrictData.C_0450_0454
import RelativeConicArcs.Q25RowCompositionStrictData.C_0455_0459
import RelativeConicArcs.Q25RowCompositionStrictData.C_0470_0474
import RelativeConicArcs.Q25RowCompositionStrictData.C_0545_0549
import RelativeConicArcs.Q25RowCompositionStrictData.C_0590_0594
import RelativeConicArcs.Q25RowCompositionStrictData.C_0600_0604
import RelativeConicArcs.Q25RowCompositionStrictData.C_0605_0609
import RelativeConicArcs.Q25RowCompositionStrictData.C_0620_0624
import RelativeConicArcs.Q25RowCompositionStrictData.C_0665_0669
import RelativeConicArcs.Q25RowCompositionStrictData.C_0675_0679
import RelativeConicArcs.Q25RowCompositionStrictData.C_0690_0694
import RelativeConicArcs.Q25RowCompositionStrictData.C_0795_0799
import RelativeConicArcs.Q25RowCompositionStrictData.C_0905_0909
import RelativeConicArcs.Q25RowCompositionStrictData.C_0970_0974
import RelativeConicArcs.Q25ExhaustionBridge

/-!
# Generated C151 per-row exhaustion disjunctions

DO NOT EDIT: generated by `notes/2026-07-18-c151-exhaustion-conclusion-generator.py`.

* payload: 50 per-row exhaustion disjunctions in R_144_C_195_244
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* mask-stream digest: `7b81e34650fd7f1607332cd6845a56e477a01e80b832dab06fbfcbcc0cbd55e0`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* strict-bound generator SHA256: `ae3000367fb9ddc8a3f8e9d23a42af768259428444563d1620e281a4d2244e56`
* exhaustion-conclusion generator SHA256: `c11d9ad4b6a684cf1a89b398e8ed41dfd4dbd233f49d7b6d93ef073ba600fef0`
-/


namespace RelativeConicArcs
namespace Q25ExhaustionConclusionData

open Q25Coordinates Q25MinimumMask Q25ResidualCoverData Q25ResidualEquality

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem concludeExhR_144_C_195_244 (i : Fin 50)
    (hraw : RawCap (rowConfig ⟨144, by decide⟩
      (residualCoverRow144C195_244[i]).c)) :
    33 ≤ (legalOrbitSet (rowConfig ⟨144, by decide⟩
      (residualCoverRow144C195_244[i]).c)).card ∨
      IsMinimumResidualClass (rowConfig ⟨144, by decide⟩
        (residualCoverRow144C195_244[i]).c) := by
  have hvalid := Q25ResidualDispatchData.dispatchR_144_C_195_244 i
  fin_cases i
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0909LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0971LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0797LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0141LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0094LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0214LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0458LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0381LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0210LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0452LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0295LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0604LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0678LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0606LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0548LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0309LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0471LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0691LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0592LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0620LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0667LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0033LegalOrbitSet_card_ge_33)
  · exact Or.inl (ValidRowPayload.source_card_ge_of_canonical hvalid hraw
      Q25RowCompositionStrictData.class0131LegalOrbitSet_card_ge_33)
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim
  · exact (BadRowPayload.not_rawCap hvalid hraw).elim

end Q25ExhaustionConclusionData
end RelativeConicArcs
