import RelativeConicArcs.Gates.AMELUAggregate

/-!
# Axiom audit for MDS--CSS AME local-unitary results

This audit covers the length-generic rigidity, topological symmetry and
transversal terminals together with the six-party dictionary,
admitted-pencil classification, marginal-moment separator, fixed-party
logical phase, four-copy separator, and transport-divisor terminals.  The
finite graph cardinalities use exhaustive native evaluation; all other
listed declarations are checked without native evaluation.
-/

open RelativeConicArcs.AMELU

#print axioms isMDSCode2m_iff_projection_bijective
#print axioms isMDSCode2m_dualCode
#print axioms genericShorteningGenerator
#print axioms genericShorteningLocalLabel_bijective
#print axioms diagonalTensorFlattening_pure_iff_coordinateAxis
#print axioms coordinateAxes_preserved_of_diagonalTensor_equivalent
#print axioms genericEqualPhaseState_three
#print axioms genericLocallyUnitaryEquivalent_three
#print axioms genericMarginalWeylCoefficient_equalPhaseState_cases
#print axioms genericReindexedMarginalArray_eq_diagonal
#print axioms genericMarginalWeylCoordinates_eq_of_localAction_eq
#print axioms familyFactor_coordinateAxes_of_diagonal_equivalent
#print axioms generic_all_isClifford_of_localAction_equalPhaseState
#print axioms generic_all_isClifford_of_permutedLocalAction_equalPhaseState
#print axioms genericLocallyUnitaryEquivalent_equalPhaseState_implies_genericLocallyCliffordEquivalent
#print axioms locallyUnitaryEquivalent_equalPhaseState_implies_locallyCliffordEquivalent_from_generic
#print axioms locallyUnitaryEquivalent_admitted_nonGRS_pencil_iff_pencilZ_eq_from_generic
#print axioms projectiveClifford_finite
#print axioms projectiveGenericProductUnitaryAutomorphism_finite
#print axioms projectiveGenericPermutedProductUnitaryAutomorphism_finite
#print axioms projectiveGenericProductUnitaryAutomorphismGroup_finite
#print axioms projectiveGenericPermutedProductUnitaryAutomorphismGroup_finite
#print axioms genericProductUnitaryContinuousProjectivization
#print axioms genericPermutedProductUnitaryContinuousProjectivization
#print axioms connectedComponent_genericIdentityAutomorphism_eq_scalarPhases
#print axioms connectedComponent_genericPermutedIdentityAutomorphism_eq_scalarPhases
#print axioms cliffordScalarSubgroup_isClosed
#print axioms intrinsicCliffordAdjointSignature_t2Space
#print axioms intrinsicCliffordAdjointSignature_discrete
#print axioms genericScalarPhaseSubgroup_isClosed
#print axioms genericPermutedScalarPhaseSubgroup_isClosed
#print axioms genericScalarPhaseContinuousInclusion
#print axioms genericPermutedScalarPhaseContinuousInclusion
#print axioms genericScalarPhase_projectivization_mulExact
#print axioms genericPermutedScalarPhase_projectivization_mulExact
#print axioms projectiveGenericProductUnitaryAutomorphismGroup_discrete
#print axioms projectiveGenericPermutedProductUnitaryAutomorphismGroup_discrete
#print axioms connectedComponent_genericProductUnitaryAutomorphism_eq_scalarCoset
#print axioms connectedComponent_genericPermutedProductUnitaryAutomorphism_eq_scalarCoset
#print axioms genericProductUnitaryAutomorphism_finite_component_cover
#print axioms genericPermutedProductUnitaryAutomorphism_finite_component_cover
#print axioms genericAutomorphismIntrinsicSignatureContinuousHom
#print axioms genericPermutedAutomorphismIntrinsicSignatureContinuousHom
#print axioms genericAutomorphismIntrinsicSignatureHom_ker
#print axioms genericPermutedAutomorphismIntrinsicSignatureHom_ker
#print axioms projectiveGenericAutomorphismEquivRealizedAdjointSignature
#print axioms projectiveGenericPermutedAutomorphismEquivRealizedAdjointSignature
#print axioms projectiveFixedPartyToPermutedAutomorphismHom_injective
#print axioms projectiveFixedParty_permutationProjection_mulExact
#print axioms genericPartyPermutationExtension_splits_iff
#print axioms GroupExtension.outerAction_eq_sectionClass
#print axioms GroupExtension.sectionAction_mul
#print axioms GroupExtension.factorSet_associativity
#print axioms GroupExtension.factorSet_change
#print axioms GroupExtension.factorSet_trivializable_iff_splitting
#print axioms GroupExtension.factorSet_trivializable_iff
#print axioms genericPartyPermutationFactorSet_associativity
#print axioms genericPartyPermutationFactorSet_change
#print axioms genericPartyPermutationFactorSet_trivializable_iff_splits
#print axioms oneLegQuantumMDSParameters_singletonEquality
#print axioms isMDSCode2m_oneLegQuantumMDSParameters
#print axioms coordinateAxes_reflected_by_linearEquiv
#print axioms IsCliffordMatrix.conjTranspose
#print axioms IsCliffordMatrix.conjugate
#print axioms IsCliffordMatrix.transpose
#print axioms IsUnitaryMatrix.transpose
#print axioms inverseTransposeWitness_of_isUnitaryMatrix
#print axioms encoderConversion_inverseTranspose_chosenLeg
#print axioms encoderConversion_inverseTranspose_and_physical_isClifford
#print axioms encoderConversion_logical_and_physical_isClifford
#print axioms genericCSSLabel_lowerDualityShear
#print axioms genericCSSLabel_upperDualityShear
#print axioms grs_projectiveTransversal_eq_affineSpecialLinear
#print axioms affineSpecialLinearOrder_seven

#print axioms isMDSCode634_arcKernel
#print axioms isAME_equalPhaseState_arcKernel
#print axioms projectivelyEquivalent_equalPhaseState_locallyCliffordEquivalent
#print axioms tensorWeylAction_equalPhaseState_of_mem_cssLabelSpace
#print axioms cssLabelSpace_isPauliLagrangian
#print axioms mem_cssSupportedLabelSpace_iff_support_subset
#print axioms equalPhaseState_hasMinimalComputationalSupport
#print axioms isAME_equalPhaseState_iff_isMDSCode634

#print axioms pencilZ_eq_iff_samePencilYOrbit
#print axioms admitted_nonGRS_pencil_classified_by_z
#print axioms locallyUnitaryEquivalent_equalPhaseState_implies_locallyCliffordEquivalent
#print axioms locallyUnitaryEquivalent_admitted_nonGRS_pencil_iff_pencilZ_eq

#print axioms card_marginalTriples
#print axioms card_marginalStars
#print axioms card_perfectMatchings
#print axioms rankFourMultiplicity_eq_sixty_add_concurrency
#print axioms not_locallyUnitaryEquivalent_of_ten_vs_atMostSix_concurrences

#print axioms fixedPartyKernel_eq_specialLinear_or_splitTorus
#print axioms contractionMatchingRank_normalizeContractionPattern
#print axioms contractionRankOrbitSum_permuteContractionPattern
#print axioms q13_zFour_not_locallyUnitaryEquivalent_zTwelve

#print axioms negativeSignedCyclePolynomial_factor
#print axioms positiveSignedCyclePolynomial_factor
#print axioms axialCyclePolynomial_factor
#print axioms reducedTransportDivisor_eq_zero_iff_three_factors
#print axioms reducedTransportDivisor_eq_zero_iff_z
#print axioms signedTransportFactor_sub_two_mul_axial
#print axioms reducedTransportDivisor_eq_zero_iff_axial_of_charSeven
#print axioms TransportCycleCoverInputs.negativeSigned_det_factor
#print axioms TransportCycleCoverInputs.positiveSigned_det_factor
#print axioms TransportCycleCoverInputs.axial_det_factor
#print axioms TransportRankBridgeInputs.matchingRank_eq_twenty_of_transportRank_eq_eight
#print axioms TransportRankBridgeInputs.matchingRank_eq_twentyOne_of_transportRank_eq_nine
#print axioms TransportOrbitGeometryInputs.card_axial_union_negative
#print axioms TransportOrbitGeometryInputs.card_axial_union_positive
