import RelativeConicArcs.Gates.AMELUAggregate

/-!
# Axiom audit for stabilizer-AME rigidity, atlases, and MDS--CSS applications

This audit covers the arbitrary-additive supported-label, minimum-support
atlas, and rigidity terminals; the length-generic equal-phase MDS--CSS
rigidity, topological symmetry, and transversal terminals; and the six-party
dictionary, admitted-pencil classification, marginal-moment separator,
fixed-party logical phase, extension-field pencil-sector algebra, four-copy
separator, and transport-divisor terminals.  The
finite graph cardinalities use exhaustive native evaluation; all other
listed declarations are checked without native evaluation.
-/

open RelativeConicArcs.AMELU

#print axioms isMDSCode2m_iff_projection_bijective
#print axioms isMDSCode2m_dualCode
#print axioms genericShorteningGenerator
#print axioms genericShorteningLocalLabel_bijective
#print axioms diagonalTensorFlattening_pure_iff_coordinateAxis
#print axioms coordinateAxes_preserved_of_diagonalTensor_equivalent
#print axioms stabilizerAME_kernelToLocal_bijective
#print axioms stabilizerKernelLocalProjection_injective_of_supportAtMost
#print axioms stabilizerAME_halfParty_kernelToLocal_bijective_of_finrank
#print axioms stabilizerKernelLocalProjection_existsUnique
#print axioms AMESupportedSubspaceProfile.erase_sup_erase_eq
#print axioms AMESupportedSubspaceProfile.space_eq_minimumSupportSpan
#print axioms AMESupportedSubspaceProfile.minimumSupportSpan_univ_eq_top
#print axioms stabilizerAME_finrank_ker_eq_local
#print axioms AdditiveStabilizerProjector.minimumSupportSpan_univ_eq_top
#print axioms AdditiveStabilizerProjector.supportedLocalProjection_bijective
#print axioms AdditiveStabilizerProjector.minimumSupportTransition_apply_supportedLabel
#print axioms AdditiveStabilizerProjector.minimumSupportAtlasEquivalent_refl
#print axioms AdditiveStabilizerProjector.MinimumSupportAtlasEquivalent.trans
#print axioms AdditiveStabilizerProjector.MinimumSupportAtlasEquivalent.symm
#print axioms AdditiveStabilizerProjector.reindexedMarginalArray_eq_diagonal
#print axioms AdditiveStabilizerState.reindexedMarginalArray_eq_diagonal
#print axioms additiveStabilizer_reindexedMarginalArray_intertwining
#print axioms additiveStabilizer_marginal_party_isClifford
#print axioms additiveStabilizer_all_isClifford_of_localAction
#print axioms additiveStabilizer_all_isClifford_of_permutedLocalAction
#print axioms additiveStabilizer_locallyUnitaryEquivalent_implies_locallyCliffordEquivalent
#print axioms HolonomyAtlas.transition_intertwines_iff_commute_holonomy
#print axioms HolonomyAtlas.compatibleGaugeEquivHolonomyCentralizer
#print axioms HolonomyAtlas.compatibleGaugesInSubgroupEquiv
#print axioms HolonomyAtlas.compatibleGaugesInNormalSubgroupEquiv
#print axioms genericEqualPhaseState_three
#print axioms genericLocallyUnitaryEquivalent_three
#print axioms genericMarginalWeylCoefficient_equalPhaseState_cases
#print axioms genericReindexedMarginalArray_eq_diagonal
#print axioms genericMarginalWeylCoordinates_eq_of_localAction_eq
#print axioms familyFactor_coordinateAxes_of_diagonal_equivalent
#print axioms all_isClifford_of_fullWeylDiagonal_intertwining
#print axioms generic_all_isClifford_of_localAction_equalPhaseState
#print axioms generic_all_isClifford_of_permutedLocalAction_equalPhaseState
#print axioms genericLocallyUnitaryEquivalent_equalPhaseState_implies_genericLocallyCliffordEquivalent
#print axioms locallyUnitaryEquivalent_equalPhaseState_implies_locallyCliffordEquivalent_from_generic
#print axioms locallyUnitaryEquivalent_admitted_nonGRS_pencil_iff_pencilZ_eq_from_generic
#print axioms projectiveClifford_finite
#print axioms projectiveGenericProductUnitaryAutomorphism_finite
#print axioms projectiveGenericPermutedProductUnitaryAutomorphism_finite
#print axioms projectiveGenericProductUnitaryAutomorphismGroup_finite
#print axioms projectiveGenericPermutedProductUnitaryAutomorphismGroup_finite
#print axioms genericProductUnitaryContinuousProjectivization
#print axioms genericPermutedProductUnitaryContinuousProjectivization
#print axioms connectedComponent_genericIdentityAutomorphism_eq_scalarPhases
#print axioms connectedComponent_genericPermutedIdentityAutomorphism_eq_scalarPhases
#print axioms cliffordScalarSubgroup_isClosed
#print axioms intrinsicCliffordAdjointSignature_t2Space
#print axioms intrinsicCliffordAdjointSignature_discrete
#print axioms genericScalarPhaseSubgroup_isClosed
#print axioms genericPermutedScalarPhaseSubgroup_isClosed
#print axioms genericScalarPhaseContinuousInclusion
#print axioms genericPermutedScalarPhaseContinuousInclusion
#print axioms genericScalarPhase_projectivization_mulExact
#print axioms genericPermutedScalarPhase_projectivization_mulExact
#print axioms projectiveGenericProductUnitaryAutomorphismGroup_discrete
#print axioms projectiveGenericPermutedProductUnitaryAutomorphismGroup_discrete
#print axioms connectedComponent_genericProductUnitaryAutomorphism_eq_scalarCoset
#print axioms connectedComponent_genericPermutedProductUnitaryAutomorphism_eq_scalarCoset
#print axioms genericProductUnitaryAutomorphism_finite_component_cover
#print axioms genericPermutedProductUnitaryAutomorphism_finite_component_cover
#print axioms genericAutomorphismIntrinsicSignatureContinuousHom
#print axioms genericPermutedAutomorphismIntrinsicSignatureContinuousHom
#print axioms genericAutomorphismIntrinsicSignatureHom_ker
#print axioms genericPermutedAutomorphismIntrinsicSignatureHom_ker
#print axioms projectiveGenericAutomorphismEquivRealizedAdjointSignature
#print axioms projectiveGenericPermutedAutomorphismEquivRealizedAdjointSignature
#print axioms projectiveFixedPartyToPermutedAutomorphismHom_injective
#print axioms projectiveFixedParty_permutationProjection_mulExact
#print axioms genericPartyPermutationExtension_splits_iff
#print axioms GroupExtension.outerAction_eq_sectionClass
#print axioms GroupExtension.sectionAction_mul
#print axioms GroupExtension.factorSet_associativity
#print axioms GroupExtension.factorSet_change
#print axioms GroupExtension.factorSet_trivializable_iff_splitting
#print axioms GroupExtension.factorSet_trivializable_iff
#print axioms genericPartyPermutationFactorSet_associativity
#print axioms genericPartyPermutationFactorSet_change
#print axioms genericPartyPermutationFactorSet_trivializable_iff_splits
#print axioms GroupExtension.Splitting.trivializingCochain_coboundary
#print axioms GroupExtension.Splitting.semidirectProductEquiv
#print axioms GroupExtension.Splitting.existsUnique_inl_mul_splitting
#print axioms GroupExtension.Splitting.natCard_middle
#print axioms GroupExtension.Splitting.inl_conj_eq_inv
#print axioms GroupExtension.Splitting.invertingInvolutionWitness
#print axioms genericPartyPermutationGroupExtensionSplitting
#print axioms genericPartyPermutationTrivializingCochain_coboundary
#print axioms genericPartyPermutationSemidirectProductEquiv
#print axioms genericPartyPermutation_natCard
#print axioms oneLegQuantumMDSParameters_singletonEquality
#print axioms isMDSCode2m_oneLegQuantumMDSParameters
#print axioms coordinateAxes_reflected_by_linearEquiv
#print axioms IsCliffordMatrix.conjTranspose
#print axioms IsCliffordMatrix.conjugate
#print axioms IsCliffordMatrix.transpose
#print axioms IsUnitaryMatrix.transpose
#print axioms inverseTransposeWitness_of_isUnitaryMatrix
#print axioms encoderConversion_inverseTranspose_chosenLeg
#print axioms encoderConversion_inverseTranspose_and_physical_isClifford
#print axioms encoderConversion_logical_and_physical_isClifford
#print axioms genericCSSLabel_lowerDualityShear
#print axioms genericCSSLabel_upperDualityShear
#print axioms fixedPartyProjectiveTransversal_eq_affineSpecialLinear_or_splitTorus
#print axioms diagonallyIsodual_fixedPartyProjectiveTransversal_dichotomy
#print axioms diagonalMultiplier_ne_zero_at
#print axioms diagonalMultiplierSpace_finrank_le_one
#print axioms diagonalMultiplierSpace_self_eq_span_one
#print axioms diagonalDualityMultiplierSpace_finrank_eq_zero_or_one
#print axioms GenericDiagonalDuality.diagonalMultiplierBilinForm_eq_zero
#print axioms genericDiagonalDualityOfMultiplier
#print axioms isDiagonallyIsodual_iff_finrank_eq_one
#print axioms not_isDiagonallyIsodual_iff_finrank_eq_zero
#print axioms diagonalDualityNullity_fixedPartyProjectiveTransversal_dichotomy
#print axioms offDiagonalBlock_fixedPartyProjectiveTransversal_eq_affineSpecialLinear
#print axioms diagonalDuality_existsUnique_unit_smul_eq
#print axioms diagonalDuality_multiplier_ratio_eq
#print axioms grs_projectiveTransversal_eq_affineSpecialLinear
#print axioms affineSpecialLinearOrder_seven

#print axioms isMDSCode634_arcKernel
#print axioms isAME_equalPhaseState_arcKernel
#print axioms projectivelyEquivalent_equalPhaseState_locallyCliffordEquivalent
#print axioms tensorWeylAction_equalPhaseState_of_mem_cssLabelSpace
#print axioms pauliSymplecticToDual_injective
#print axioms exists_pauliLabel_pairing_eq_dual
#print axioms cssLabelSpace_isPauliLagrangian
#print axioms mem_cssSupportedLabelSpace_iff_support_subset
#print axioms equalPhaseState_hasMinimalComputationalSupport
#print axioms isAME_equalPhaseState_iff_isMDSCode634
#print axioms tensorWeylAction_X_equalPhaseState_eq_translated
#print axioms translatedEqualPhaseState_eq_iff
#print axioms stateInnerProduct_translatedEqualPhaseState_eq_zero
#print axioms tensorWeylAction_Z_translatedEqualPhaseState
#print axioms supportedArcSyndrome_bijective_of_card_three
#print axioms existsUnique_arcSyndrome_supported_on_three
#print axioms existsUnique_arcSyndrome_weight_three_on_support

#print axioms pencilZ_eq_iff_samePencilYOrbit
#print axioms admitted_nonGRS_pencil_classified_by_z
#print axioms locallyUnitaryEquivalent_equalPhaseState_implies_locallyCliffordEquivalent
#print axioms locallyUnitaryEquivalent_admitted_nonGRS_pencil_iff_pencilZ_eq
#print axioms pencilFrameRatio_crossDifference
#print axioms pencilFrameRatio_eq_iff
#print axioms twistedPencilGaleDivisor_refl
#print axioms pencilGalePairing_multiplier
#print axioms pencilGalePairing_multiplier_zero_iff
#print axioms twistedPencil_sectors_disjoint
#print axioms map_pencilGRSQuartic
#print axioms map_pencilA
#print axioms map_pencilB
#print axioms map_pencilZ
#print axioms admitted_nonGRS_map_iff

#print axioms card_marginalTriples
#print axioms card_marginalStars
#print axioms card_perfectMatchings
#print axioms rankFourMultiplicity_eq_sixty_add_concurrency
#print axioms not_locallyUnitaryEquivalent_of_ten_vs_atMostSix_concurrences

#print axioms fixedPartyKernel_eq_specialLinear_or_splitTorus
#print axioms splitTorusWeylBlock_isSpecialLinear
#print axioms splitTorusWeylBlock_mul_self
#print axioms splitTorusWeylBlock_mul_splitTorusBlock
#print axioms contractionMatchingRank_normalizeContractionPattern
#print axioms contractionRankOrbitSum_permuteContractionPattern
#print axioms q13_zFour_not_locallyUnitaryEquivalent_zTwelve

#print axioms negativeSignedCyclePolynomial_factor
#print axioms positiveSignedCyclePolynomial_factor
#print axioms axialCyclePolynomial_factor
#print axioms reducedTransportDivisor_eq_zero_iff_three_factors
#print axioms reducedTransportDivisor_eq_zero_iff_z
#print axioms signedTransportFactor_sub_two_mul_axial
#print axioms reducedTransportDivisor_eq_zero_iff_axial_of_charSeven
#print axioms TransportCycleCoverInputs.negativeSigned_det_factor
#print axioms TransportCycleCoverInputs.positiveSigned_det_factor
#print axioms TransportCycleCoverInputs.axial_det_factor
#print axioms TransportRankBridgeInputs.matchingRank_eq_twenty_of_transportRank_eq_eight
#print axioms TransportRankBridgeInputs.matchingRank_eq_twentyOne_of_transportRank_eq_nine
#print axioms TransportOrbitGeometryInputs.card_axial_union_negative
#print axioms TransportOrbitGeometryInputs.card_axial_union_positive
