import RelativeConicArcs.CarrierArcBound

/-!
# Square-root carrier cardinality verification boundary

This import-only module checks the kernel of coordinate-hyperplane restriction, exact degree growth
for finite products, the affine degree bound obtained by dehomogenizing a homogeneous binary form,
bounded-degree detection and exact-threshold classification by pairwise relatively prime degree-one
divisors, nonsquareness of squarefree nonunits, and the composition of linewise roots with these
statements into carrier-cardinality and threshold identities.

It does not assert the projective incidence hypotheses that produce the line divisors, the
squarefree dual-factor product, or that compatibility at the nodes makes each linewise residual
divisible by the restricted product of the preceding line equations.
-/

#print axioms RelativeConicArcs.fintypeProd_X_sub_C_dvd_of_injective_roots
#print axioms RelativeConicArcs.fintypeProd_X_sub_C_dvd_sub_of_injective_eval_eq
#print axioms RelativeConicArcs.homogenize_fintypeProd_X_sub_C_dvd_homogenize_sub_of_injective_eval_eq
#print axioms RelativeConicArcs.natDegree_dehomogenize_le_of_isHomogeneous
#print axioms RelativeConicArcs.homogenize_fintypeProd_X_sub_C_dvd_sub_of_isHomogeneous_eval_eq
#print axioms RelativeConicArcs.homogenize_fintypeProd_X_sub_C_eq_prod_homogenize
#print axioms RelativeConicArcs.prod_eq_C_prod_mul_homogenize_fintypeProd_X_sub_C
#print axioms RelativeConicArcs.prod_dvd_of_homogenize_fintypeProd_X_sub_C_dvd_of_proportional
#print axioms RelativeConicArcs.prod_dvd_sub_of_proportional_homogenizedNodeFactors_of_isHomogeneous_eval_eq
#print axioms RelativeConicArcs.firstCoordinateHyperplaneRestriction_eq_zero_iff_dvd
#print axioms RelativeConicArcs.firstCoordinateHyperplaneRestriction_surjective
#print axioms RelativeConicArcs.coordinateTransformedHyperplaneRestriction_eq_zero_iff_dvd
#print axioms RelativeConicArcs.coordinateTransformedHyperplaneRestriction_surjective
#print axioms RelativeConicArcs.exists_single_correction_of_surjective_of_residual_dvd
#print axioms RelativeConicArcs.exists_finset_extension_of_residual_dvd_restrictedEquationProduct
#print axioms RelativeConicArcs.exists_finset_coordinateTransformed_extension_of_residual_dvd
#print axioms RelativeConicArcs.exists_finset_extension_of_single_correction
#print axioms RelativeConicArcs.totalDegree_fintypeProd_of_ne_zero
#print axioms RelativeConicArcs.totalDegree_fintypeProd_eq_card_of_degree_one
#print axioms RelativeConicArcs.eq_zero_of_pairwise_isRelPrime_dvd_of_totalDegree_lt_card
#print axioms RelativeConicArcs.exists_eq_C_mul_fintypeProd_of_pairwise_isRelPrime_dvd_of_totalDegree_le_card
#print axioms RelativeConicArcs.not_exists_eq_sq_of_squarefree_of_not_isUnit
#print axioms RelativeConicArcs.not_exists_fintypeProd_eq_sq_of_pairwise_isRelPrime_of_squarefree
#print axioms RelativeConicArcs.card_le_of_linewiseSquareRoots_extend_and_jointlyDetect
#print axioms RelativeConicArcs.exists_extendedRoot_difference_eq_C_mul_lineProduct
#print axioms RelativeConicArcs.exists_coordinateTransformed_extendedRoot_difference_eq_C_mul_lineProduct
#print axioms RelativeConicArcs.card_le_of_linewiseSquareRoots_extend_of_lineProductDetection
