import RelativeConicArcs.ChowRestrictionDescent

/-!
# Polynomial restriction and Frobenius-descent verification boundary

This import-only module checks homogeneous linear substitution, restriction of a finite product of
linear factors, the coefficient formula and affine-node factorization for a restricted
plane-linear equation, injectivity of affine nodes under pairwise avoidance, simultaneous
factorization of an incident line family, derivation of restricted nonvanishing from avoidance
when every index has a distinct companion, representative rescaling, the proportional
paired-factor identity and its square-scalar correction, automatic correction over perfect
exponent-characteristic-two coefficient rings, and descent of extended linewise roots through a
jointly detecting restriction family.

It does not assert the projective incidence hypotheses that produce a factor pairing, an
interpolation theorem for compatible linewise roots, or joint detection for a particular family
of projective lines and a particular degree bound.
-/

#print axioms RelativeConicArcs.exists_ne_zero_scale_binaryCoefficients_of_determinant_eq_zero
#print axioms RelativeConicArcs.exists_ne_zero_scale_homogeneousLinearPolynomial_of_binary_determinant_eq_zero
#print axioms RelativeConicArcs.homogenize_X_sub_C_eq_homogeneousLinearPolynomial_affineNode
#print axioms RelativeConicArcs.exists_ne_zero_scale_homogeneousLinearPolynomial_eq_C_mul_homogenize_X_sub_C
#print axioms RelativeConicArcs.planeLineRestriction_homogeneousLinearPolynomial
#print axioms RelativeConicArcs.planeLineRestrictedCoefficients_affinePoint
#print axioms RelativeConicArcs.planeLineRestrictedCoefficients_ne_zero_of_affinePoint_ne_zero
#print axioms RelativeConicArcs.injective_affineNode_of_pairwise_avoids_incidentPoint
#print axioms RelativeConicArcs.exists_ne_zero_scale_planeLineRestriction_homogeneousLinearPolynomial_eq_C_mul_homogenize_X_sub_C
#print axioms RelativeConicArcs.exists_ne_zero_scale_planeLineRestriction_eq_C_mul_homogenize_X_sub_C_of_affinePoint
#print axioms RelativeConicArcs.exists_scale_planeLineRestriction_eq_C_mul_homogenize_X_sub_C_of_affinePoints
#print axioms RelativeConicArcs.injective_affineNode_and_exists_scale_planeLineRestriction_eq_C_mul_homogenize_X_sub_C_of_pairwise_avoids
#print axioms RelativeConicArcs.planeLineRestriction_X
#print axioms RelativeConicArcs.homogeneousLinearPolynomial_scale
#print axioms RelativeConicArcs.dualLinearFactorProduct_rescale
#print axioms RelativeConicArcs.exists_dualLinearFactorProduct_rescale_eq_sq_of_exists_eq_sq
#print axioms RelativeConicArcs.exists_dualLinearFactorProduct_rescale_eq_sq_iff
#print axioms RelativeConicArcs.planeLineRestriction_homogeneousLinearPolynomial_scale
#print axioms RelativeConicArcs.planeLineRestriction_dualLinearFactorProduct
#print axioms RelativeConicArcs.prod_eq_sq_of_equiv_sum
#print axioms RelativeConicArcs.prod_eq_scaleProduct_mul_sq_of_equiv_sum
#print axioms RelativeConicArcs.prod_eq_sq_of_equiv_sum_of_scaleProduct_sq
#print axioms RelativeConicArcs.planeLineRestriction_dualLinearFactorProduct_eq_sq_of_pairing
#print axioms RelativeConicArcs.planeLineRestriction_dualLinearFactorProduct_eq_scaleProduct_mul_sq_of_pairing
#print axioms RelativeConicArcs.planeLineRestriction_dualLinearFactorProduct_eq_sq_of_proportionalPairing
#print axioms RelativeConicArcs.exists_planeLineRestriction_dualLinearFactorProduct_eq_sq_of_proportionalPairing
#print axioms RelativeConicArcs.globalSquareRoot_restricts
#print axioms RelativeConicArcs.exists_globalSquareRoot_of_jointlyDetected_extendedRoots
#print axioms RelativeConicArcs.isInSquareFrobeniusImage_of_jointlyDetected_extendedRoots
