import RelativeConicArcs.ClebschProjectiveTradeReduction
import RelativeConicArcs.ClebschLucasCoefficientBasis
import RelativeConicArcs.ClebschLucasPolynomialFactorization
import RelativeConicArcs.ClebschFiniteRootWeightSlice
import RelativeConicArcs.ClebschFiniteRootRecurrenceBridge
import RelativeConicArcs.ClebschOuterParityWeights
import RelativeConicArcs.ClebschRootDefect
import RelativeConicArcs.ClebschFirstFrobeniusSection
import RelativeConicArcs.ClebschDetectingModuleVanishings
import RelativeConicArcs.ClebschAffineExtensionContraction
import RelativeConicArcs.ClebschAffineContractionCohomology
import RelativeConicArcs.ClebschDetectingIntertwiners
import RelativeConicArcs.ClebschDividedPowerTopSlices
import RelativeConicArcs.ClebschPolynomialTopSliceDetection
import RelativeConicArcs.ClebschPolyhedralInvariantAverages
import RelativeConicArcs.ClebschOuterParityInjection
import RelativeConicArcs.ClebschRegularMatching
import RelativeConicArcs.ClebschDihedralReflectionParity
import RelativeConicArcs.ClebschOrbitOrderReduction
import RelativeConicArcs.ClebschBalancedOrbitEndgame
import RelativeConicArcs.ClebschRankThreeBalancedEndgame
import RelativeConicArcs.ClebschArithmeticGluing
import RelativeConicArcs.ClebschFixedLineRadialTranslation

/-!
# Structural audit for the all-field conic-matching argument

This gate follows the mathematical order of the quadratic-trade proof.  It
checks the pullback splitting diagram, the Lucas coefficient basis and parity,
the finite-field root defect, the four-weight Frobenius section, the detector
coefficients, evaluation--coevaluation contraction and coboundary descent,
regular matching and dihedral parity reductions, exceptional-order endgame,
and the exact `q = 5, 7, 11` endpoint data.

It also checks the table-free fixed-line algebra: radial translation preserves the top and moment
data and changes one outer constant affinely; between two parameters with nonzero outer constant
the presented evaluation space is unchanged, so the three Radical--Hadamard hypotheses are imposed
at the reference parameter alone and derived at every other noncoalescent parameter; and exactly
`|K| - 2` nonmatching noncoalescent parameters remain.  The geometric identification of the
evaluation spaces with the presented top-space, constant-function, and radial-level generators is
an input, not a conclusion, of this file.

The gate distinguishes kernel-checked implications from classical
representation and subgroup identifications.  In particular, importing this
file alone does not identify the coefficient recurrence space with a concrete
finite-group Hom space or prove Dickson's maximal-subgroup theorem.
-/

#check RelativeConicArcs.ClebschProjectiveTradeReduction.kernel_or_split_pullback
#check RelativeConicArcs.ClebschLucasCoefficientBasis.satisfiesDigitRecurrences_iff_exists_scalar_digitTensorCoefficient
#check RelativeConicArcs.ClebschLucasPolynomialFactorization.coeff_expandedProduct_digitValue
#check RelativeConicArcs.ClebschFiniteRootWeightSlice.finiteRootInvariant_iff_exists_scalar_alternatingBinomial
#check RelativeConicArcs.ClebschFiniteRootRecurrenceBridge.finiteRootInvariant_iff_satisfiesOneDigitRecurrence
#check RelativeConicArcs.ClebschOuterParityWeights.odd_weight_eq_q_sub_one_or_one_sub_q
#check RelativeConicArcs.ClebschRootDefect.finiteCoordinate_vanishing_factorization
#check RelativeConicArcs.ClebschFirstFrobeniusSection.upper_C_sub_B
#check RelativeConicArcs.ClebschDetectingModuleVanishings.steinberg_head_above_quadratic_ceiling
#check RelativeConicArcs.ClebschDetectingModuleVanishings.characteristic_three_scalar_eq_zero
#check RelativeConicArcs.ClebschAffineExtensionContraction.contractedCochain_eq
#check RelativeConicArcs.ClebschAffineContractionCohomology.contraction_maps_coboundary
#check RelativeConicArcs.ClebschDetectingIntertwiners.eq_zero_of_two_generator_relations
#check RelativeConicArcs.ClebschDividedPowerTopSlices.twoLeafCoefficient_ne_zero
#check RelativeConicArcs.ClebschPolynomialTopSliceDetection.general_top_slice_map_eq_zero
#check RelativeConicArcs.ClebschPolyhedralInvariantAverages.icosahedral_average_eq_one
#check RelativeConicArcs.ClebschOuterParityInjection.fourWeightConstruction_injective_of_middleDifference
#check RelativeConicArcs.ClebschRegularMatching.leftRegularEquivariant_perfectMatching_iff
#check RelativeConicArcs.ClebschDihedralReflectionParity.exists_two_mul_add_one_dvd_iff_odd
#check RelativeConicArcs.ClebschBalancedOrbitEndgame.exceptionalSplit_regularMatching_iff
#check RelativeConicArcs.ClebschRankThreeBalancedEndgame.certifiedBalancedSheets_endpoint_and_uniquePartner
#check RelativeConicArcs.ClebschArithmeticGluing.rankThree_split_fused_trichotomy
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.topConfigurations_first_secondMoments_invariant
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.outerRadialConstantAt_sub
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.RadialEvaluationFamily.evaluationSpace_eq_reference
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.hadamardSquare_eq_equalSheetSum_of_noncoalescent
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.annihilates_hadamardSquare_iff_eq_sheetSignLine_of_noncoalescent
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.card_nonmatchingNoncoalescentParameters
#check RelativeConicArcs.ClebschFixedLineRadialTranslation.nonmatchingNoncoalescentParameters_tradeLine_and_card

#print axioms RelativeConicArcs.ClebschProjectiveTradeReduction.kernel_or_split_pullback
#print axioms RelativeConicArcs.ClebschLucasCoefficientBasis.satisfiesDigitRecurrences_iff_exists_scalar_digitTensorCoefficient
#print axioms RelativeConicArcs.ClebschLucasPolynomialFactorization.coeff_expandedProduct_digitValue
#print axioms RelativeConicArcs.ClebschFiniteRootWeightSlice.finiteRootInvariant_iff_exists_scalar_alternatingBinomial
#print axioms RelativeConicArcs.ClebschFiniteRootRecurrenceBridge.finiteRootInvariant_iff_satisfiesOneDigitRecurrence
#print axioms RelativeConicArcs.ClebschOuterParityWeights.odd_weight_eq_q_sub_one_or_one_sub_q
#print axioms RelativeConicArcs.ClebschRootDefect.finiteCoordinate_vanishing_factorization
#print axioms RelativeConicArcs.ClebschFirstFrobeniusSection.upper_C_sub_B
#print axioms RelativeConicArcs.ClebschDetectingModuleVanishings.steinberg_head_above_quadratic_ceiling
#print axioms RelativeConicArcs.ClebschDetectingModuleVanishings.characteristic_three_scalar_eq_zero
#print axioms RelativeConicArcs.ClebschAffineExtensionContraction.contractedCochain_eq
#print axioms RelativeConicArcs.ClebschAffineContractionCohomology.contraction_maps_coboundary
#print axioms RelativeConicArcs.ClebschDetectingIntertwiners.eq_zero_of_two_generator_relations
#print axioms RelativeConicArcs.ClebschDividedPowerTopSlices.twoLeafCoefficient_ne_zero
#print axioms RelativeConicArcs.ClebschPolynomialTopSliceDetection.general_top_slice_map_eq_zero
#print axioms RelativeConicArcs.ClebschPolyhedralInvariantAverages.icosahedral_average_eq_one
#print axioms RelativeConicArcs.ClebschOuterParityInjection.fourWeightConstruction_injective_of_middleDifference
#print axioms RelativeConicArcs.ClebschRegularMatching.leftRegularEquivariant_perfectMatching_iff
#print axioms RelativeConicArcs.ClebschDihedralReflectionParity.exists_two_mul_add_one_dvd_iff_odd
#print axioms RelativeConicArcs.ClebschBalancedOrbitEndgame.exceptionalSplit_regularMatching_iff
#print axioms RelativeConicArcs.ClebschRankThreeBalancedEndgame.certifiedBalancedSheets_endpoint_and_uniquePartner
#print axioms RelativeConicArcs.ClebschArithmeticGluing.rankThree_split_fused_trichotomy
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.topConfigurations_first_secondMoments_invariant
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.outerRadialConstantAt_sub
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.RadialEvaluationFamily.evaluationSpace_eq_reference
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.hadamardSquare_eq_equalSheetSum_of_noncoalescent
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.annihilates_hadamardSquare_iff_eq_sheetSignLine_of_noncoalescent
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.card_nonmatchingNoncoalescentParameters
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.nonmatchingNoncoalescentParameters_tradeLine_and_card
