import RelativeConicArcs.Gates.ClebschArithmeticGluing
import RelativeConicArcs.Gates.ClebschHilbertSymmetry
import RelativeConicArcs.Gates.ClebschHyperplaneSquare
import RelativeConicArcs.Gates.ClebschPaperIIStructural

/-!
# Formal boundary for Clebsch factorization

This gate is the registered Lean export boundary for the Clebsch-factorization argument.
It combines four independently checked parts: the structural all-field conic-matching reduction,
the explicit rank-three arithmetic gluing at field orders five, seven, and eleven, Hilbert-symmetry
forcing, and the hyperplane-square annihilator argument.

The 54 declarations below are the exact unique terminal set exposed by this gate.  Importing it
does not supply classical representation-theoretic or subgroup identifications beyond the theorem
types printed here, and it asserts no all-prime extension of the finite endpoint calculations.
The component gate headers state the hypotheses and computational trust route for each part.
-/

#print axioms RelativeConicArcs.ClebschArithmeticGluing.vertexReductions_are_bijective
#print axioms RelativeConicArcs.ClebschArithmeticGluing.a3_two_has_no_root
#print axioms RelativeConicArcs.ClebschArithmeticGluing.b3_two_roots
#print axioms RelativeConicArcs.ClebschArithmeticGluing.h3_five_roots
#print axioms RelativeConicArcs.ClebschArithmeticGluing.h3_golden_roots
#print axioms RelativeConicArcs.ClebschArithmeticGluing.reduced_vertex_polynomials_split
#print axioms RelativeConicArcs.ClebschArithmeticGluing.matchingEdgeLists_encode_frozen_matchings
#print axioms RelativeConicArcs.ClebschArithmeticGluing.frozen_matching_mates_are_fixedPointFree_involutions
#print axioms RelativeConicArcs.ClebschArithmeticGluing.a3_matching_is_fused
#print axioms RelativeConicArcs.ClebschArithmeticGluing.b3_reductions_induce_split_matchings
#print axioms RelativeConicArcs.ClebschArithmeticGluing.silverTransporter_swaps_matchings
#print axioms RelativeConicArcs.ClebschArithmeticGluing.goldenTransporter_swaps_matchings
#print axioms RelativeConicArcs.ClebschArithmeticGluing.coxeterSquare_orbits
#print axioms RelativeConicArcs.ClebschArithmeticGluing.coxeterSquare_orders_and_square_determinants
#print axioms RelativeConicArcs.ClebschArithmeticGluing.projective_group_orders
#print axioms RelativeConicArcs.ClebschArithmeticGluing.a3_fused_stabilizer_and_orbit
#print axioms RelativeConicArcs.ClebschArithmeticGluing.b3_split_stabilizers_and_orbits
#print axioms RelativeConicArcs.ClebschArithmeticGluing.h3_certificate_literal_checks
#print axioms RelativeConicArcs.ClebschArithmeticGluing.h3_stabilizer_generation_word_data
#print axioms RelativeConicArcs.ClebschArithmeticGluing.transporters_are_outer
#print axioms RelativeConicArcs.ClebschArithmeticGluing.rankThree_split_fused_trichotomy
#print axioms RelativeConicArcs.ClebschArithmeticGluing.stabilizer_eq_character_kernel
#print axioms RelativeConicArcs.ClebschArithmeticGluing.sheetCharacter_eq_of_kernel_eq
#print axioms RelativeConicArcs.HilbertSymmetry.socleDegree_eq_three
#print axioms RelativeConicArcs.HilbertSymmetry.value_three_eq_one
#print axioms RelativeConicArcs.HyperplaneSquare.cubicAnnihilator_eq_zero
#print axioms RelativeConicArcs.ClebschProjectiveTradeReduction.kernel_or_split_pullback
#print axioms RelativeConicArcs.ClebschLucasCoefficientBasis.satisfiesDigitRecurrences_iff_exists_scalar_digitTensorCoefficient
#print axioms RelativeConicArcs.ClebschLucasPolynomialFactorization.coeff_expandedProduct_digitValue
#print axioms RelativeConicArcs.ClebschFiniteRootWeightSlice.finiteRootInvariant_iff_exists_scalar_alternatingBinomial
#print axioms RelativeConicArcs.ClebschFiniteRootRecurrenceBridge.finiteRootInvariant_iff_satisfiesOneDigitRecurrence
#print axioms RelativeConicArcs.ClebschOuterParityWeights.odd_weight_eq_q_sub_one_or_one_sub_q
#print axioms RelativeConicArcs.ClebschRootDefect.finiteCoordinate_vanishing_factorization
#print axioms RelativeConicArcs.ClebschFirstFrobeniusSection.upper_C_sub_B
#print axioms RelativeConicArcs.ClebschDetectingModuleVanishings.steinberg_head_above_quadratic_ceiling
#print axioms RelativeConicArcs.ClebschDetectingModuleVanishings.characteristic_three_scalar_eq_zero
#print axioms RelativeConicArcs.ClebschAffineExtensionContraction.contractedCochain_eq
#print axioms RelativeConicArcs.ClebschAffineContractionCohomology.contraction_maps_coboundary
#print axioms RelativeConicArcs.ClebschDetectingIntertwiners.eq_zero_of_two_generator_relations
#print axioms RelativeConicArcs.ClebschDividedPowerTopSlices.twoLeafCoefficient_ne_zero
#print axioms RelativeConicArcs.ClebschPolynomialTopSliceDetection.general_top_slice_map_eq_zero
#print axioms RelativeConicArcs.ClebschPolyhedralInvariantAverages.icosahedral_average_eq_one
#print axioms RelativeConicArcs.ClebschOuterParityInjection.fourWeightConstruction_injective_of_middleDifference
#print axioms RelativeConicArcs.ClebschRegularMatching.leftRegularEquivariant_perfectMatching_iff
#print axioms RelativeConicArcs.ClebschDihedralReflectionParity.exists_two_mul_add_one_dvd_iff_odd
#print axioms RelativeConicArcs.ClebschBalancedOrbitEndgame.exceptionalSplit_regularMatching_iff
#print axioms RelativeConicArcs.ClebschRankThreeBalancedEndgame.certifiedBalancedSheets_endpoint_and_uniquePartner
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.topConfigurations_first_secondMoments_invariant
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.outerRadialConstantAt_sub
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.RadialEvaluationFamily.evaluationSpace_eq_reference
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.hadamardSquare_eq_equalSheetSum_of_noncoalescent
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.annihilates_hadamardSquare_iff_eq_sheetSignLine_of_noncoalescent
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.card_nonmatchingNoncoalescentParameters
#print axioms RelativeConicArcs.ClebschFixedLineRadialTranslation.nonmatchingNoncoalescentParameters_tradeLine_and_card
