import RelativeConicArcs.ArrangementWeightedAdjoint
import RelativeConicArcs.ClebschWeightedAdjointB3

/-!
# Import-only gate for weighted two-adjoint arrangement-code results

This gate exports the conditional incidence/depth profile identities, the explicit finite-field
evaluation and injectivity bridge, and checked `A3/F_5`, `B3/F_11`, and `H3/F_11` coefficient-weight
distributions with attained minimum weights.  It is deliberately separate from the
replacement-spine gate.
-/

#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.SectionProfile.weightedDepth_add_card
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.lineSection_card_add_mirrorCount
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CodeProfile.depthPolynomial_eq_mirror_add_punctured
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CodeProfile.puncturedDepthPolynomial_coeff
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CodeProfile.wordWeight_eq_weightAtDepth
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CodeProfile.hammingEnumerator_eq_weightedDepthSum
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CodeProfile.minimumDistance_of_maxDepth
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.projectiveEvaluationWord_injective_of_positive
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.affineRayVec5_bijective
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.a3_weightedAdjoint_specialization
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.a3_evaluationCode_weightDistribution
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.a3_evaluationWeight_eq_six_sub_weightedDepth
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.a3_evaluationWord_injective
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.h3_weightedAdjoint_specialization
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.h3_evaluationCode_weightDistribution
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.h3_evaluationWeight_eq_fifteen_sub_weightedDepth
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.h3_evaluationWord_injective
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.b3_weightedAdjoint_certificate
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.b3_evaluationCode_weightDistribution
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.b3_evaluationWeight_eq_fortyFive_sub_weightedDepth
#print axioms RelativeConicArcs.ArrangementWeightedAdjoint.CoxeterModels.b3_evaluationWord_injective
#print axioms RelativeConicArcs.Examples.Q11Coding.affineRayVec_bijective
