import RelativeConicArcs.MatchingFactorizationBalance
import RelativeConicArcs.ProjectiveMultiplicityObstruction
import RelativeConicArcs.TwoSheetCommonQuotient

/-!
# Import gate for matching-factorization balance

This gate exposes the incidence double-counting theorem that turns constant
edge multiplicity into the size formula `qλ`, together with the categorical
obstruction that lifts two projective sheet summands through an epimorphic
quadratic evaluation map.  It also exposes the linear Goursat reduction that
identifies the codimension of a two-sheet evaluation image with the dimension
of the two evaluations' common source quotient.
-/

#print axioms RelativeConicArcs.MatchingFactorizationBalance.stableLine_fullSupport
#print axioms RelativeConicArcs.MatchingFactorizationBalance.card_mul_edgesPerMatching_eq_card_mul_edgeMultiplicity
#print axioms RelativeConicArcs.MatchingFactorizationBalance.sheet_card_eq_q_mul_index
#print axioms RelativeConicArcs.MatchingFactorizationBalance.edgeMultiplicity_eq_one_of_sheet_card_eq_q
#print axioms RelativeConicArcs.MatchingFactorizationBalance.oneFactorization_card_eq_q
#print axioms RelativeConicArcs.MatchingFactorizationBalance.twoOneFactorizationSheets_card_eq_two_mul_q

#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.projectiveMonomorphism_lifts
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.twoProjectiveCopies_lift
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.twoNonprincipalCopies_embed_kernel
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.no_epimorphism_to_twoSheetKernel
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.representation_twoCopies_finrank_le_source
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.representation_excludesTwoCopies_of_finrank_lt
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.representation_no_epimorphism_to_twoSheetKernel
#print axioms RelativeConicArcs.ProjectiveMultiplicityObstruction.representation_no_epimorphism_of_finrank_lt

#print axioms RelativeConicArcs.TwoSheetCommonQuotient.combinedRange_goursat
#print axioms RelativeConicArcs.TwoSheetCommonQuotient.finrank_combinedRange_quotient_eq_finrank_kernelSup_quotient
#print axioms RelativeConicArcs.TwoSheetCommonQuotient.uniqueTrade_iff_commonQuotient_finrank_eq_one
#print axioms RelativeConicArcs.TwoSheetCommonQuotient.two_le_tradeDimension_of_two_le_commonQuotient
#print axioms RelativeConicArcs.TwoSheetCommonQuotient.pairedCopy_injective
#print axioms RelativeConicArcs.TwoSheetCommonQuotient.pairedCopy_range_le_tradeKernel
#print axioms RelativeConicArcs.TwoSheetCommonQuotient.finrank_le_tradeKernel_of_pairedCopy
