import RelativeConicArcs.MatchingPackingCompletionBridge

/-!
# Matching-packing defect verification boundary

This import-only module checks the finite-graph leave and clique-packing completion theorems, the
exact partition of Kneser edges between nonmaximum and maximum concurrence cliques, and the
resulting quantitative transfer from nonexistence of a maximum-clique decomposition to the
integer-normalized prescribed-hole defect.
-/

#print axioms RelativeConicArcs.MatchingPacking.oneBlockShort_leave_isClique
#print axioms
  RelativeConicArcs.CliquePacking.exists_decomposition_of_card_leave_eq_choose
#print axioms RelativeConicArcs.badConcurrenceEdgeCount_add_maximumBlocks
#print axioms RelativeConicArcs.matchingPackingDeficiency_le_scaledDefect
#print axioms RelativeConicArcs.two_mul_half_le_scaledDefect_of_two_le_matchingPackingDeficiency
#print axioms RelativeConicArcs.maximumConcurrenceBlockDeficiency_le_scaledDefect
#print axioms
  RelativeConicArcs.two_mul_half_le_scaledDefect_of_two_le_maximumConcurrenceBlockDeficiency
#print axioms
  RelativeConicArcs.two_le_maximumConcurrenceBlockDeficiency_of_no_decomposition
#print axioms
  RelativeConicArcs.two_mul_half_le_scaledDefect_of_no_disjointness_decomposition
