import RelativeConicArcs.Gates.NinePointHeisenbergPair
import RelativeConicArcs.NinePointHeisenbergUncoveredLocus
import RelativeConicArcs.NinePointHeisenbergLineProfile
import RelativeConicArcs.NinePointHeisenbergChordProfile
import RelativeConicArcs.NinePointHeisenbergStabilizer
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex0
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex1
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex2
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex3
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex4
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex5
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex6
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex7
import RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex8
import RelativeConicArcs.NinePointHeisenbergStabilizerConclusion
import RelativeConicArcs.NinePointHeisenbergCubicPencilCounts
import RelativeConicArcs.NinePointHeisenbergConicCounts
import RelativeConicArcs.NinePointHeisenbergConicProfile
import RelativeConicArcs.NinePointHeisenbergConicOrbit
import RelativeConicArcs.NinePointHeisenbergConicTypeLow
import RelativeConicArcs.NinePointHeisenbergConicTypeMiddle
import RelativeConicArcs.NinePointHeisenbergConicTypeHigh

#print axioms RelativeConicArcs.NinePointHeisenbergUncoveredLocus.both_sets_are_arcs
#print axioms RelativeConicArcs.NinePointHeisenbergUncoveredLocus.canonical_projective_point_domain
#print axioms RelativeConicArcs.NinePointHeisenbergUncoveredLocus.uncovered_is_exact_ordinary_uncovered_locus
#print axioms RelativeConicArcs.NinePointHeisenbergLineProfile.complete_line_type_profile
#print axioms RelativeConicArcs.NinePointHeisenbergLineProfile.selected_secant_multiplicity_profile
#print axioms RelativeConicArcs.NinePointHeisenbergLineProfile.uncovered_secant_multiplicity_profile
#print axioms RelativeConicArcs.NinePointHeisenbergChordProfile.four_chord_direction_profile
#print axioms RelativeConicArcs.NinePointHeisenbergChordProfile.asymmetric_secant_incidence
#print axioms RelativeConicArcs.NinePointHeisenbergChordProfile.union_is_not_arc
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizer.ordered_frame_count
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizer.matrix_eq_smul_of_coordinate_frame_rays
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizer.determinantThree_eq_det
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizer.displayed_heisenberg_matrices_are_distinct_pair_stabilizers
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex0.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex1.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex2.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex3.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex4.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex5.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex6.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex7.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerFirstIndex8.transporter_profile
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerConclusion.all_stabilizer_prefix_profiles
#print axioms RelativeConicArcs.NinePointHeisenbergStabilizerConclusion.exact_frame_normalized_stabilizer_counts
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.selected_evaluation_minor_nonsingular
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.uncovered_evaluation_minor_nonsingular
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.selected_evaluation_minor_left_inverse
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.uncovered_evaluation_minor_left_inverse
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.selected_coefficients_evaluate_as_selectedCubic
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.uncovered_coefficients_evaluate_as_uncoveredCubic
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.pencilCombination_g
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.pencilCombination_h
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.selected_cubic_unique_up_to_scalar
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencil.uncovered_cubic_unique_up_to_scalar
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencilCounts.rational_pencil_point_count_profile
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencilCounts.rational_pencil_members_are_distinct
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencilCounts.orbit_cubic_point_counts
#print axioms RelativeConicArcs.NinePointHeisenbergCubicPencilCounts.rational_base_locus_is_empty
#print axioms RelativeConicArcs.NinePointHeisenbergConicCounts.five_subset_conic_counts
#print axioms RelativeConicArcs.NinePointHeisenbergConicCounts.each_conic_contains_its_five_subset
#print axioms RelativeConicArcs.NinePointHeisenbergConicCounts.each_five_subset_has_full_evaluation_rank
#print axioms RelativeConicArcs.NinePointHeisenbergConicCounts.five_subset_multiplicity_profile
#print axioms RelativeConicArcs.NinePointHeisenbergConicCensus.determinantThree_eq_det
#print axioms RelativeConicArcs.NinePointHeisenbergConicCensus.determinantFive_eq_det
#print axioms RelativeConicArcs.NinePointHeisenbergConicCensus.sameQuadraticCoefficients_eq_true_iff
#print axioms RelativeConicArcs.NinePointHeisenbergConicTable.conicTable_covers_distinctConics
#print axioms RelativeConicArcs.NinePointHeisenbergConicProfile.complete_conic_profile
#print axioms RelativeConicArcs.NinePointHeisenbergConicProfile.conic_intersection_maxima
#print axioms RelativeConicArcs.NinePointHeisenbergConicOrbit.six_point_conics_have_relative_orbit_profile
#print axioms RelativeConicArcs.NinePointHeisenbergConicOrbit.first_generator_translates_six_point_conics
#print axioms RelativeConicArcs.NinePointHeisenbergConicOrbit.second_generator_translates_six_point_conics
#print axioms RelativeConicArcs.NinePointHeisenbergConicOrbit.six_point_conic_tangent_profile
#print axioms RelativeConicArcs.NinePointHeisenbergConicTypeLow.discriminant_type_agrees_with_secants
#print axioms RelativeConicArcs.NinePointHeisenbergConicTypeMiddle.discriminant_type_agrees_with_secants
#print axioms RelativeConicArcs.NinePointHeisenbergConicTypeHigh.discriminant_type_agrees_with_secants
