import RelativeConicArcs.Gates.PRSBeyondRedundancyFour

/-!
# Axiom audit for projective Reed--Solomon results beyond redundancy four

The commands below audit the paper-adopted algebraic, contraction, arithmetic, certificate-table,
and conditional synthesis terminals exported by
`RelativeConicArcs.Gates.PRSBeyondRedundancyFour`.  Geometric, coding, group-action, and external
certificate semantics occur in theorem hypotheses and structure fields rather than as axioms.
This file adds no declarations.
-/

#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_of_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_iff_not_not_has_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.CoveringRadiusInput.deep_iff_splitFree
#print axioms RelativeConicArcs.PRSFoundation.exceptional_not_deep_of_geometric_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.PersistentFamilies.persistent_card
#print axioms RelativeConicArcs.PRSFoundation.OrbitExhaustionInput.splitFree_iff_mem_persistent
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent_of_exceptional_shallow
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent_of_compatible

#print axioms RelativeConicArcs.PRSRedundancyFive.affine_span_product_mem_hankelKernel
#print axioms RelativeConicArcs.PRSRedundancyFive.affine_pair_infinity_span_product_mem_hankelKernel
#print axioms RelativeConicArcs.PRSRedundancyFive.inHankelKernel_scale_iff
#print axioms RelativeConicArcs.PRSRedundancyFive.isSplitFree_scale_iff
#print axioms RelativeConicArcs.PRSRedundancyFive.isSplitFree_iff_not_liesInThreeColumnSpan
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.family_arithmetic
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.deep_card_osculatingConjugate
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.deep_card_osculatingRational
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.deep_card_characteristicThree
#print axioms RelativeConicArcs.PRSRedundancyFive.redundancyFiveSynthesis
#print axioms RelativeConicArcs.PRSRedundancyFiveCertified.redundancyFiveSynthesisWithCertificate
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_field_orders
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_point_counts
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_orbit_counts
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_orbit_stabilizer
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_histogram_total
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_frobenius_target
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.certified_comparison_band_has_no_sporadic
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.certified_orbit_summaries_agree_with_sporadic_records

#print axioms RelativeConicArcs.PRSPolarInduction.iteratedProjectiveSequenceContraction_map
#print axioms RelativeConicArcs.PRSPolarInduction.sequenceContraction_agrees_with_finite
#print axioms RelativeConicArcs.PRSPolarInduction.PointedKernelLift.lift_splitSquarefreeKernelMember
#print axioms RelativeConicArcs.PRSPolarInduction.mem_modularContractionKernel_iff
#print axioms RelativeConicArcs.PRSPolarInduction.CoherentPolarInput.splitFree_implies_persistent_or_modular
#print axioms RelativeConicArcs.PRSPolarInduction.tangentTranslate_of_cast_eq_zero
#print axioms RelativeConicArcs.PRSPolarInduction.tangentTranslate_surjective
#print axioms RelativeConicArcs.PRSPolarInduction.fifthPower_sigmaInversionOrbitCount
#print axioms RelativeConicArcs.PRSStableComponents.symmetricFactor_plucker
#print axioms RelativeConicArcs.PRSStableComponents.exchangedFactor_plucker
#print axioms RelativeConicArcs.PRSStableComponents.antiInvariantFactor_plucker
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_first_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_second_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_third_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_fourth_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.mem_modularContractionKernel_prod_iff
#print axioms RelativeConicArcs.PRSStableComponents.cyclicPlaneCatalecticant_blocks_cover
#print axioms RelativeConicArcs.PRSStableComponents.cyclicPlaneCatalecticant_no_nonzero_coefficient
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySixHighFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySevenHighFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSeven.PersistentModularFamilyData.classified_card_doubled
#print axioms RelativeConicArcs.PRSRedundancySixSeven.RedundancySixOrbitArithmetic.orbit_count_pairs
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySixAllFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySevenAllFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSevenCertificate.redundancySix_count_exhaustion
#print axioms RelativeConicArcs.PRSRedundancySixSevenCertificate.redundancySeven_count_exhaustion

#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarkerContraction_map
#print axioms RelativeConicArcs.PRSRedundancyEight.projectiveSequenceContraction_comm
#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarkerContraction_swap_first
#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarkerContraction_swap_last
#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarkerContraction_affine_apply
#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarkerContraction_affine_eq_of_elementarySymmetric
#print axioms RelativeConicArcs.PRSRedundancyEight.exact_deletion_and_polar_budgets
#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarker_genusOne_hasseWeil_bound
#print axioms RelativeConicArcs.PRSRedundancyEight.threeMarker_genusOne_hasseWeil_exact_threshold
#print axioms RelativeConicArcs.PRSRedundancyEight.primePowerOrder_at_least_fortyThree
#print axioms RelativeConicArcs.PRSRedundancyEight.finiteFieldOrder_at_least_fortyThree
#print axioms RelativeConicArcs.PRSRedundancyEight.redundancyEightHighFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancyEight.redundancyEightPrimePowerSynthesis
#print axioms RelativeConicArcs.PRSRedundancyEight.redundancyEightFiniteFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancyEight.PersistentFamilyData.classified_card
#print axioms RelativeConicArcs.PRSRedundancyEight.OrbitArithmetic.orbit_count_pairs
#print axioms RelativeConicArcs.PRSRedundancyEight.OrbitArithmetic.seventhPower_sigmaInversionOrbitCount
#print axioms RelativeConicArcs.PRSRedundancyEight.tangentTranslateSeven_of_cast_eq_zero
#print axioms RelativeConicArcs.PRSRedundancyEight.tangentTranslateSeven_surjective
#print axioms RelativeConicArcs.PRSRedundancyEight.CharacteristicSevenCarrierBoundary.proved_boundary

#print axioms RelativeConicArcs.PRSResidualQuadratic.dividedPowerContraction_comm
#print axioms RelativeConicArcs.PRSResidualQuadratic.dividedPowerContraction_twice_apply
#print axioms RelativeConicArcs.PRSResidualQuadratic.first_hankel_identity
#print axioms RelativeConicArcs.PRSResidualQuadratic.second_hankel_identity
#print axioms RelativeConicArcs.PRSResidualQuadratic.residual_discriminant
#print axioms RelativeConicArcs.PRSResidualQuadratic.residual_sum_product_solve_hankel
#print axioms RelativeConicArcs.PRSResidualQuadratic.residual_roots_sum
#print axioms RelativeConicArcs.PRSResidualQuadratic.residual_roots_product
#print axioms RelativeConicArcs.PRSRedundancyNine.ResidualSliceInput.exceptional_has_splitSquarefreeWitness
#print axioms RelativeConicArcs.PRSRedundancyNine.orbit_count_pair
#print axioms RelativeConicArcs.PRSRedundancyNine.PersistentFamilyData.deep_card
#print axioms RelativeConicArcs.PRSRedundancyNine.redundancyNineSynthesis

#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.dividedDiscriminant_eq_residualBranch
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.dividedDiscriminant_eq_tangentQuadric_sq
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.arfRepresentative_specialization
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.residualQuadratic_eq_zero_iff_artinSchreier
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.orderedHessianEquation_scale_parameter
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.orderedHessianEquation_scale_root
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.commonQuadraticPencil_pluecker
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.firstSegreRuling_mem_tangentQuadric
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.secondSegreRuling_mem_tangentQuadric
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.OrderedHessianCarrierData.carrier_and_complementary_boundary
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.orderedHessianLowerCoverStratum
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.splitFree_implies_persistent_or_lucas
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.two_dvd_choose_two_pow
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.consecutiveOverlapIndex_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.mem_degreeFiveLucasCarrier_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.mem_degreeSixLucasCarrier_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.mem_degreeNineLucasCarrier_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.lucasFlagContraction_map
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.doublingModThree_cycle_table
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.doublingModSeven_cycle_table
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.LinearizedRootCoverData.arithmetic_terminal
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.lastPairSum_zero_iff_roots_equal
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.endpointLastPair_artinSchreier
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.EndpointArtinSchreierLiftingData.rational_lifts_iff_traceZero
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.affineFrameGroupOrderThreeOverTwo
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.degreeNineAdditiveWitnessCount_small_controls
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.degreeNineAdditiveWitnessCount_pos
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DegreeNineEndpointAdditiveData.exact_count_and_endpointOrbit_shallow
