import RelativeConicArcs.Gates.PRSBeyondRedundancyFour

/-!
# Axiom audit for projective Reed--Solomon results beyond redundancy four

The commands below audit the paper-adopted algebraic, contraction, arithmetic, certificate-table,
and conditional synthesis terminals exported by
`RelativeConicArcs.Gates.PRSBeyondRedundancyFour`.  Geometric, coding, group-action, and external
certificate semantics occur in theorem hypotheses and structure fields rather than as axioms.
This file adds no declarations.
-/

#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_of_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_iff_not_not_has_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.CoveringRadiusInput.deep_iff_splitFree
#print axioms RelativeConicArcs.PRSFoundation.exceptional_not_deep_of_geometric_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.PersistentFamilies.persistent_card
#print axioms RelativeConicArcs.PRSFoundation.OrbitExhaustionInput.splitFree_iff_mem_persistent
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent_of_exceptional_shallow
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent_of_compatible

#print axioms RelativeConicArcs.PRSUniformCoveringRadius.two_mul_sub_three_le_uniformTransverseThreshold
#print axioms RelativeConicArcs.PRSUniformCoveringRadius.seroussiRothDimensionRange_of_uniformTransverseThreshold
#print axioms RelativeConicArcs.PRSUniformCoveringRadius.SeroussiRothDuerRadiusInput.radiusRange_of_externalSeroussiRothDuer
#print axioms RelativeConicArcs.PRSUniformCoveringRadius.SeroussiRothDuerRadiusInput.radiusRange_six_eight_of_externalSeroussiRothDuer
#print axioms RelativeConicArcs.PRSUniformCoveringRadius.deep_iff_splitFree_of_externalSeroussiRothDuer_uniformTransverseThreshold

#print axioms RelativeConicArcs.PRSRedundancyFive.affine_span_product_mem_hankelKernel
#print axioms RelativeConicArcs.PRSRedundancyFive.affine_pair_infinity_span_product_mem_hankelKernel
#print axioms RelativeConicArcs.PRSRedundancyFive.inHankelKernel_scale_iff
#print axioms RelativeConicArcs.PRSRedundancyFive.isSplitFree_scale_iff
#print axioms RelativeConicArcs.PRSRedundancyFive.isSplitFree_iff_not_liesInThreeColumnSpan
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.family_arithmetic
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.deep_card_osculatingConjugate
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.deep_card_osculatingRational
#print axioms RelativeConicArcs.PRSRedundancyFive.FamilyData.deep_card_characteristicThree
#print axioms RelativeConicArcs.PRSRedundancyFive.redundancyFiveSynthesis
#print axioms RelativeConicArcs.PRSRedundancyFiveCertified.redundancyFiveSynthesisWithCertificate
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_field_orders
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_point_counts
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_orbit_counts
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_orbit_stabilizer
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_histogram_total
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.sporadic_frobenius_target
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.certified_comparison_band_has_no_sporadic
#print axioms RelativeConicArcs.PRSRedundancyFiveCertificate.certified_orbit_summaries_agree_with_sporadic_records

#print axioms RelativeConicArcs.PRSPolarInduction.iteratedProjectiveSequenceContraction_map
#print axioms RelativeConicArcs.PRSPolarInduction.sequenceContraction_agrees_with_finite
#print axioms RelativeConicArcs.PRSPolarInduction.PointedKernelLift.lift_splitSquarefreeKernelMember
#print axioms RelativeConicArcs.PRSPolarInduction.mem_modularContractionKernel_iff
#print axioms RelativeConicArcs.PRSPolarInduction.CoherentPolarInput.splitFree_implies_persistent_or_modular
#print axioms RelativeConicArcs.PRSPolarInduction.tangentTranslate_of_cast_eq_zero
#print axioms RelativeConicArcs.PRSPolarInduction.tangentTranslate_surjective
#print axioms RelativeConicArcs.PRSPolarInduction.fifthPower_sigmaInversionOrbitCount
#print axioms RelativeConicArcs.PRSStableComponents.symmetricFactor_plucker
#print axioms RelativeConicArcs.PRSStableComponents.exchangedFactor_plucker
#print axioms RelativeConicArcs.PRSStableComponents.antiInvariantFactor_plucker
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_first_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_second_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_third_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.coherentFano_fourth_hankelMinor
#print axioms RelativeConicArcs.PRSStableComponents.mem_modularContractionKernel_prod_iff
#print axioms RelativeConicArcs.PRSStableComponents.cyclicPlaneCatalecticant_blocks_cover
#print axioms RelativeConicArcs.PRSStableComponents.cyclicPlaneCatalecticant_no_nonzero_coefficient
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySixHighFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySevenHighFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSeven.PersistentModularFamilyData.classified_card_doubled
#print axioms RelativeConicArcs.PRSRedundancySixSeven.RedundancySixOrbitArithmetic.orbit_count_pairs
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySixAllFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSeven.redundancySevenAllFieldSynthesis
#print axioms RelativeConicArcs.PRSRedundancySixSevenCertificate.redundancySix_count_exhaustion
#print axioms RelativeConicArcs.PRSRedundancySixSevenCertificate.redundancySeven_count_exhaustion
