import RelativeConicArcs.Gates.PRSCharacteristicTwoHessianLucas

/-!
# Axiom audit for characteristic-two divided Hessians and Lucas carriers

The commands below print the dependencies of the public algebraic, contraction, arithmetic,
classification-boundary, and endpoint-orbit terminals.  The imported module has no project-local
axioms, generated evaluator, external oracle, or finite certificate.  Geometry, finite-field
cover semantics, and coding interpretations appear only as explicit hypotheses and structure
fields.
-/

#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.dividedDiscriminant_eq_residualBranch
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.dividedDiscriminant_eq_tangentQuadric_sq
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.arfRepresentative_specialization
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DividedCubic.residualQuadratic_eq_zero_iff_artinSchreier
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.orderedHessianEquation_scale_parameter
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.orderedHessianEquation_scale_root
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.commonQuadraticPencil_pluecker
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.firstSegreRuling_mem_tangentQuadric
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.secondSegreRuling_mem_tangentQuadric
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.OrderedHessianCarrierData.carrier_and_complementary_boundary
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.orderedHessianLowerCoverStratum
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.splitFree_implies_persistent_or_lucas
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.two_dvd_choose_two_pow
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.consecutiveOverlapIndex_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.mem_degreeFiveLucasCarrier_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.mem_degreeSixLucasCarrier_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.mem_degreeNineLucasCarrier_iff
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.lucasFlagContraction_map
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.doublingModThree_cycle_table
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.doublingModSeven_cycle_table
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.LinearizedRootCoverData.arithmetic_terminal
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.lastPairSum_zero_iff_roots_equal
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.endpointLastPair_artinSchreier
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.EndpointArtinSchreierLiftingData.rational_lifts_iff_traceZero
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.affineFrameGroupOrderThreeOverTwo
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.degreeNineAdditiveWitnessCount_small_controls
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.degreeNineAdditiveWitnessCount_pos
#print axioms RelativeConicArcs.PRSCharacteristicTwoHessianLucas.DegreeNineEndpointAdditiveData.exact_count_and_endpointOrbit_shallow
