import RelativeConicArcs.Gates.PRSFoundation

/-!
# Axiom audit for projective Reed--Solomon syndrome foundations

The commands below print the axiom dependencies of the reusable logical theorems exported by
`RelativeConicArcs.Gates.PRSFoundation`; this file adds no declarations.
-/

#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_of_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_iff_not_not_has_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.HankelKernelDictionary.not_splitFree_iff_has_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.CoveringRadiusInput.deep_iff_splitFree
#print axioms RelativeConicArcs.PRSFoundation.WitnessConstructionInput.exceptional_has_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.GeometricWitnessInput.exceptional_has_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.exceptional_not_splitFree_of_compatible_geometric_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.exceptional_not_splitFree_of_geometric_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.exceptional_not_deep_of_compatible_geometric_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.exceptional_not_deep_of_geometric_kernel_member
#print axioms RelativeConicArcs.PRSFoundation.PersistentFamilies.persistent_card
#print axioms RelativeConicArcs.PRSFoundation.OrbitExhaustionInput.splitFree_iff_mem_persistent
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent_of_exceptional_shallow
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent_of_compatible
#print axioms RelativeConicArcs.PRSFoundation.deep_iff_mem_persistent
