import RelativeConicArcs.Q25ResidualConclusionData.C_R_237_C_238_287
import RelativeConicArcs.Q25ResidualConclusionData.C_R_237_C_288_309

/-!
# Generated C151 normalized-row conclusion dispatcher

DO NOT EDIT: generated by
`notes/2026-07-17-c151-residual-conclusion-dispatch-generator.py`.

* payload: all normalized-row conclusions with b = 237
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* conclusion-generator SHA256: `43954385dbbf428ae1450adcb31c7cc353f5f62c1d8295113ea671041b49983c`
* dispatch-generator SHA256: `1af4f75f0c6653f2813020336cd9eb5b176849d362c9cff1f3d8f4a00e16e357`
-/


namespace RelativeConicArcs
namespace Q25ResidualConclusionDispatchData

open Q25Coordinates Q25MinimumMask Q25ResidualCoverData Q25ResidualConclusionData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem concludeB_237 (c : Fin 310) (hbc : 237 < c.val)
    (hraw : RawCap (rowConfig ⟨237, by decide⟩ c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨237, by decide⟩ c)).card := by
  fin_cases c
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · exact concludeR_237_C_238_287 ⟨0, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨1, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨2, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨3, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨4, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨5, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨6, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨7, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨8, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨9, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨10, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨11, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨12, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨13, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨14, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨15, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨16, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨17, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨18, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨19, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨20, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨21, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨22, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨23, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨24, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨25, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨26, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨27, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨28, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨29, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨30, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨31, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨32, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨33, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨34, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨35, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨36, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨37, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨38, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨39, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨40, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨41, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨42, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨43, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨44, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨45, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨46, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨47, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨48, by decide⟩ hraw
  · exact concludeR_237_C_238_287 ⟨49, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨0, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨1, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨2, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨3, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨4, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨5, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨6, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨7, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨8, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨9, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨10, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨11, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨12, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨13, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨14, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨15, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨16, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨17, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨18, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨19, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨20, by decide⟩ hraw
  · exact concludeR_237_C_288_309 ⟨21, by decide⟩ hraw

end Q25ResidualConclusionDispatchData
end RelativeConicArcs
