import RelativeConicArcs.Q25ResidualConclusionData.C_R_254_C_255_304
import RelativeConicArcs.Q25ResidualConclusionData.C_R_254_C_305_309

/-!
# Generated C151 normalized-row conclusion dispatcher

DO NOT EDIT: generated by
`notes/2026-07-17-c151-residual-conclusion-dispatch-generator.py`.

* payload: all normalized-row conclusions with b = 254
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* conclusion-generator SHA256: `43954385dbbf428ae1450adcb31c7cc353f5f62c1d8295113ea671041b49983c`
* dispatch-generator SHA256: `1af4f75f0c6653f2813020336cd9eb5b176849d362c9cff1f3d8f4a00e16e357`
-/


namespace RelativeConicArcs
namespace Q25ResidualConclusionDispatchData

open Q25Coordinates Q25MinimumMask Q25ResidualCoverData Q25ResidualConclusionData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem concludeB_254 (c : Fin 310) (hbc : 254 < c.val)
    (hraw : RawCap (rowConfig ⟨254, by decide⟩ c)) :
    32 ≤ (legalOrbitSet (rowConfig ⟨254, by decide⟩ c)).card := by
  fin_cases c
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · simp at hbc
  · exact concludeR_254_C_255_304 ⟨0, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨1, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨2, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨3, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨4, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨5, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨6, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨7, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨8, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨9, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨10, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨11, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨12, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨13, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨14, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨15, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨16, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨17, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨18, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨19, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨20, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨21, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨22, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨23, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨24, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨25, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨26, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨27, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨28, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨29, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨30, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨31, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨32, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨33, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨34, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨35, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨36, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨37, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨38, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨39, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨40, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨41, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨42, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨43, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨44, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨45, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨46, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨47, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨48, by decide⟩ hraw
  · exact concludeR_254_C_255_304 ⟨49, by decide⟩ hraw
  · exact concludeR_254_C_305_309 ⟨0, by decide⟩ hraw
  · exact concludeR_254_C_305_309 ⟨1, by decide⟩ hraw
  · exact concludeR_254_C_305_309 ⟨2, by decide⟩ hraw
  · exact concludeR_254_C_305_309 ⟨3, by decide⟩ hraw
  · exact concludeR_254_C_305_309 ⟨4, by decide⟩ hraw

end Q25ResidualConclusionDispatchData
end RelativeConicArcs
