import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_144_C_145_194
import RelativeConicArcs.Q25ResidualTransportData.T_144_C_145_194_V_00
import RelativeConicArcs.Q25ResidualTransportData.T_144_C_145_194_V_01
import RelativeConicArcs.Q25ResidualTransportData.T_144_C_145_194_V_02

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: semantic dispatcher for 50 rows in R_144_C_145_194
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* transport FNV-1a-64: `4e503df3c383731d`
-/


namespace RelativeConicArcs
namespace Q25ResidualDispatchData

open Q25ResidualCoverData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem dispatchR_144_C_145_194 (i : Fin 50) :
    (residualCoverRow144C145_194[i]).ValidFor ⟨144, by decide⟩ := by
  fin_cases i <;>
    first
    | exact Q25ResidualTransportData.residualTransportB144C157_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C159_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C160_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C161_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C162_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C163_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C165_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C168_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C171_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C172_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C174_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C181_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C182_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C183_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C184_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C186_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C187_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C190_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB144C192_payloadValidFor
    | decide

end Q25ResidualDispatchData
end RelativeConicArcs
