import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_163_C_164_213
import RelativeConicArcs.Q25ResidualTransportData.T_163_C_164_213_V_00
import RelativeConicArcs.Q25ResidualTransportData.T_163_C_164_213_V_01
import RelativeConicArcs.Q25ResidualTransportData.T_163_C_164_213_V_02

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: semantic dispatcher for 50 rows in R_163_C_164_213
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* transport FNV-1a-64: `4e503df3c383731d`
-/


namespace RelativeConicArcs
namespace Q25ResidualDispatchData

open Q25ResidualCoverData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem dispatchR_163_C_164_213 (i : Fin 50) :
    (residualCoverRow163C164_213[i]).ValidFor ⟨163, by decide⟩ := by
  fin_cases i <;>
    first
    | exact Q25ResidualTransportData.residualTransportB163C182_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C183_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C184_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C185_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C186_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C187_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C189_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C190_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C191_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C194_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C196_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C197_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C206_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C207_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C208_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C211_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB163C212_payloadValidFor
    | decide

end Q25ResidualDispatchData
end RelativeConicArcs
