import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_147_C_198_247
import RelativeConicArcs.Q25ResidualTransportData.T_147_C_198_247_V_00
import RelativeConicArcs.Q25ResidualTransportData.T_147_C_198_247_V_01
import RelativeConicArcs.Q25ResidualTransportData.T_147_C_198_247_V_02

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: semantic dispatcher for 50 rows in R_147_C_198_247
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `3f226f307d84005970f0a7e7f964e135f90545c75f09984305c2b259dadd2026`
* transport FNV-1a-64: `4e503df3c383731d`
-/


namespace RelativeConicArcs
namespace Q25ResidualDispatchData

open Q25ResidualCoverData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem dispatchR_147_C_198_247 (i : Fin 50) :
    (residualCoverRow147C198_247[i]).ValidFor ⟨147, by decide⟩ := by
  fin_cases i <;>
    first
    | exact Q25ResidualTransportData.residualTransportB147C198_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C206_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C208_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C210_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C212_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C213_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C214_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C215_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C216_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C218_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C219_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C224_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C231_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C233_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C234_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C236_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C237_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C238_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C241_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C242_payloadValidFor
    | exact Q25ResidualTransportData.residualTransportB147C243_payloadValidFor
    | decide

end Q25ResidualDispatchData
end RelativeConicArcs
