import RelativeConicArcs.Q25RowCompositionData.C_0350_0354
import RelativeConicArcs.Q25ExhaustionBridge

/-!
# Generated C151 strict canonical-class bounds

DO NOT EDIT: generated by `notes/2026-07-18-c151-strict-class-bound-generator.py`.

* payload: strict bounds for canonical classes 350 through 354
* mask-stream digest: `7b81e34650fd7f1607332cd6845a56e477a01e80b832dab06fbfcbcc0cbd55e0`
* spectrum-script SHA256: `151b34ce6d0e1c0d3d18b9f12623e504ca0095c0bca506c7f657db6ddb410a94`
* strict-bound generator SHA256: `ae3000367fb9ddc8a3f8e9d23a42af768259428444563d1620e281a4d2244e56`
-/

namespace RelativeConicArcs
namespace Q25RowCompositionStrictData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25RowCompositionData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem class0350LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0350A class0350B class0350C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0350A class0350B class0350C)
    class0350ReflectedMaskCertificate.sound
    (by decide)

theorem class0351LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0351A class0351B class0351C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0351A class0351B class0351C)
    class0351ReflectedMaskCertificate.sound
    (by decide)

theorem class0352LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0352A class0352B class0352C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0352A class0352B class0352C)
    class0352ReflectedMaskCertificate.sound
    (by decide)

theorem class0353LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0353A class0353B class0353C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0353A class0353B class0353C)
    class0353ReflectedMaskCertificate.sound
    (by decide)

theorem class0354LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0354A class0354B class0354C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0354A class0354B class0354C)
    class0354ReflectedMaskCertificate.sound
    (by decide)

end Q25RowCompositionStrictData
end RelativeConicArcs
