import RelativeConicArcs.Q25RowCompositionData.C_0585_0589
import RelativeConicArcs.Q25ExhaustionBridge

/-!
# Generated C151 strict canonical-class bounds

DO NOT EDIT: generated by `notes/2026-07-18-c151-strict-class-bound-generator.py`.

* payload: strict bounds for canonical classes 585 through 589
* mask-stream digest: `7b81e34650fd7f1607332cd6845a56e477a01e80b832dab06fbfcbcc0cbd55e0`
* spectrum-script SHA256: `151b34ce6d0e1c0d3d18b9f12623e504ca0095c0bca506c7f657db6ddb410a94`
* strict-bound generator SHA256: `ae3000367fb9ddc8a3f8e9d23a42af768259428444563d1620e281a4d2244e56`
-/

namespace RelativeConicArcs
namespace Q25RowCompositionStrictData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25RowCompositionData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem class0585LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0585A class0585B class0585C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0585A class0585B class0585C)
    class0585ReflectedMaskCertificate.sound
    (by decide)

theorem class0586LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0586A class0586B class0586C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0586A class0586B class0586C)
    class0586ReflectedMaskCertificate.sound
    (by decide)

theorem class0587LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0587A class0587B class0587C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0587A class0587B class0587C)
    class0587ReflectedMaskCertificate.sound
    (by decide)

theorem class0588LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0588A class0588B class0588C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0588A class0588B class0588C)
    class0588ReflectedMaskCertificate.sound
    (by decide)

theorem class0589LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0589A class0589B class0589C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0589A class0589B class0589C)
    class0589ReflectedMaskCertificate.sound
    (by decide)

end Q25RowCompositionStrictData
end RelativeConicArcs
