import RelativeConicArcs.Q25RowCompositionData.C_0765_0769
import RelativeConicArcs.Q25ExhaustionBridge

/-!
# Generated C151 strict canonical-class bounds

DO NOT EDIT: generated by `notes/2026-07-18-c151-strict-class-bound-generator.py`.

* payload: strict bounds for canonical classes 765 through 769
* mask-stream digest: `7b81e34650fd7f1607332cd6845a56e477a01e80b832dab06fbfcbcc0cbd55e0`
* spectrum-script SHA256: `151b34ce6d0e1c0d3d18b9f12623e504ca0095c0bca506c7f657db6ddb410a94`
* strict-bound generator SHA256: `ae3000367fb9ddc8a3f8e9d23a42af768259428444563d1620e281a4d2244e56`
-/

namespace RelativeConicArcs
namespace Q25RowCompositionStrictData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25RowCompositionData

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

theorem class0765LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0765A class0765B class0765C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0765A class0765B class0765C)
    class0765ReflectedMaskCertificate.sound
    (by decide)

theorem class0766LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0766A class0766B class0766C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0766A class0766B class0766C)
    class0766ReflectedMaskCertificate.sound
    (by decide)

theorem class0767LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0767A class0767B class0767C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0767A class0767B class0767C)
    class0767ReflectedMaskCertificate.sound
    (by decide)

theorem class0768LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0768A class0768B class0768C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0768A class0768B class0768C)
    class0768ReflectedMaskCertificate.sound
    (by decide)

theorem class0769LegalOrbitSet_card_ge_33 :
    33 ≤ (legalOrbitSet
      (normalizedConfig class0769A class0769B class0769C)).card :=
  Q25ExhaustionBridge.card_legalOrbitSet_ge_of_sound
    (normalizedConfig_isConjInvariant class0769A class0769B class0769C)
    class0769ReflectedMaskCertificate.sound
    (by decide)

end Q25RowCompositionStrictData
end RelativeConicArcs
