import PassantCodeQ13.Gates.Main

/-!
# Axiom audit for the finite q=13 passant-code leaves

The commands print the actual axiom dependencies of every aggregate native terminal under the
pinned Lean toolchain.  Native evaluation is expected to expose declaration-local axioms.
-/

#print axioms PassantCodeQ13.WeightTen.local_partition
#print axioms PassantCodeQ13.WeightTen.all_isolated_profiles_disjoint
#print axioms PassantCodeQ13.WeightTen.all_cycle_profiles_disjoint
#print axioms PassantCodeQ13.WeightTen.cycle_pair_partition
#print axioms PassantCodeQ13.Rank.incidenceRows_rank
#print axioms PassantCodeQ13.SemanticTransports.recoverCoefficient_basisColumn
#print axioms PassantCodeQ13.SemanticTransports.incidenceColumn_expansion
#print axioms PassantCodeQ13.SemanticTransports.incidenceMap_has_rank_fortyTwo
#print axioms PassantCodeQ13.Gates.Main.incidenceRankAndCodeDimension
#print axioms PassantCodeQ13.AssociationAlgebra.relation_matrix_ranks
#print axioms PassantCodeQ13.AssociationAlgebra.rhoZero_square
#print axioms PassantCodeQ13.AssociationAlgebra.rankThirtySix_squaring_cycle
#print axioms PassantCodeQ13.AssociationTransport.booleanParityProduct_linearize
#print axioms PassantCodeQ13.AssociationTransport.rhoZero_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.rhoNine_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.rhoTen_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.rhoTwelve_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.relation_matrix_identities
#print axioms PassantCodeQ13.AssociationTransport.orbitS4_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.orbitDihedralA_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.orbitDihedralB_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.orbitDihedralC_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.every_minimum_orbit_spans_rhoZero_kernel
#print axioms PassantCodeQ13.MinimumWords.orbitS4_size_and_kernel
#print axioms PassantCodeQ13.MinimumWords.orbitS4_rank
#print axioms PassantCodeQ13.MinimumWords.orbitDihedralA_certificate
#print axioms PassantCodeQ13.MinimumWords.orbitDihedralB_certificate
#print axioms PassantCodeQ13.MinimumWords.orbitDihedralC_certificate
#print axioms PassantCodeQ13.MinimumWords.dihedral_orbits_pairwise_disjoint
#print axioms PassantCodeQ13.MinimumWords.minimumSupportCodes_length
#print axioms PassantCodeQ13.MinimumWords.fixedPoint_weightTwelve_exhaustion
#print axioms PassantCodeQ13.MinimumWords.fixedPoint_slices_are_stabilizer_orbits
#print axioms PassantCodeQ13.MinimumWords.pair_concurrence_recovers_passant_join
#print axioms PassantCodeQ13.MinimumWords.geometric_rows_have_zero_triple_signatures
#print axioms PassantCodeQ13.Gates.Main.weightTenCertificate
#print axioms PassantCodeQ13.Gates.Main.arbitraryWeightTenProfileTransport
#print axioms PassantCodeQ13.Gates.Main.minimumOrbitCertificate
#print axioms PassantCodeQ13.Gates.Main.fixedPointWeightTwelveExhaustion
#print axioms PassantCodeQ13.Gates.Main.fixedPointSlicesAreStabilizerOrbits
#print axioms PassantCodeQ13.Gates.Main.minimumOrbitsSpanRhoZeroKernel
