#!/usr/bin/env python3
"""Rotation orders available to a boundary limit of a del Pezzo mirror.

Setting.  The mirror of a del Pezzo surface of degree at least three is a
Laurent polynomial W = sum_i a_i x^{v_i} whose Newton polygon P is reflexive,
with the origin as its unique interior lattice point and the origin not in the
support (Coates--Corti--Galkin--Kasprzyk, Minkowski polynomials).  A
cocharacter b of the Novikov torus is a height function on the support; the
critical points of W cluster over the cells of the induced regular
subdivision, and over a cell C the leading behaviour is governed by the cell
polynomial W_C = sum_{v_i in C} a_i x^{v_i}.

If the support points of C generate a sublattice of index m in N, then
W_C is an eigenvector of the dual mu_m-action on the torus, so its critical
values are permuted with multiplication by a primitive m-th root of unity, and
the boundary monodromy over C has cycles of length m.  For a cell whose
support points generate N there is no rotation.

Because the support omits only the origin, a cell can have m > 1 only if the
origin lies in its interior: for any other cell the support points are all of
its lattice points, and the lattice points of a lattice polygon generate N.
So at most one cell of a subdivision produces cycles, and its rotation order
is the index of the sublattice spanned by the differences of its lattice
points other than the origin.

This script enumerates reflexive polygons and, inside each, every sub-polygon
containing the origin in its interior, and reports which rotation orders m
occur.  The question at issue is whether any m is divisible by a prime at
least five.

Usage: python3 c925-fable-reflexive-cell-bound.py [BOX]
"""
import itertools
import sys
from math import gcd


def det(u, v):
    return u[0] * v[1] - u[1] * v[0]


def convex_hull(points):
    pts = sorted(set(points))
    if len(pts) <= 2:
        return pts

    def half(seq):
        out = []
        for p in seq:
            while len(out) >= 2 and det(
                (out[-1][0] - out[-2][0], out[-1][1] - out[-2][1]),
                (p[0] - out[-2][0], p[1] - out[-2][1]),
            ) <= 0:
                out.pop()
            out.append(p)
        return out

    lower = half(pts)
    upper = half(reversed(pts))
    return lower[:-1] + upper[:-1]


def inside(hull, p, strict):
    n = len(hull)
    if n < 3:
        return False
    for i in range(n):
        a, b = hull[i], hull[(i + 1) % n]
        cross = det((b[0] - a[0], b[1] - a[1]), (p[0] - a[0], p[1] - a[1]))
        if cross < 0 or (strict and cross == 0):
            return False
    return True


def lattice_points(hull, box):
    return [p for p in itertools.product(range(-box, box + 1), repeat=2)
            if inside(hull, p, strict=False) or p in hull]


def sublattice_index(vectors):
    """Index in Z^2 of the subgroup generated by `vectors` (0 if rank < 2)."""
    a = b = 0          # Hermite form rows
    rows = [list(v) for v in vectors]
    # integer row reduction to Hermite normal form
    basis = []
    for r in rows:
        cur = r[:]
        for bvec in basis:
            if bvec[0] != 0 and cur[0] != 0:
                g = gcd(abs(bvec[0]), abs(cur[0]))
                m1, m2 = cur[0] // g, bvec[0] // g
                cur = [cur[0] * m2 - bvec[0] * m1, cur[1] * m2 - bvec[1] * m1]
        if cur != [0, 0]:
            basis.append(cur)
            basis.sort(key=lambda v: (v[0] == 0, abs(v[0])))
        if len(basis) > 2:
            # reduce pairwise until at most two independent rows remain
            best = None
            for u, v in itertools.combinations(basis, 2):
                d = abs(det(u, v))
                if d and (best is None or d < best[0]):
                    best = (d, u, v)
            if best is None:
                basis = basis[:2]
            else:
                basis = [best[1], best[2]]
    if len(basis) < 2:
        return 0
    a, b = basis[0], basis[1]
    idx = abs(det(a, b))
    # refine: the index is the gcd of all 2x2 minors' lattice, recompute by
    # successive reduction against every vector
    for v in vectors:
        for u in (a, b):
            d = abs(det(u, v))
            if d:
                idx = gcd(idx, d)
    return idx


def index_of_differences(points):
    if len(points) < 2:
        return 0
    base = points[0]
    vecs = [(p[0] - base[0], p[1] - base[1]) for p in points[1:]]
    return sublattice_index(vecs)


def main():
    box = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    grid = list(itertools.product(range(-box, box + 1), repeat=2))
    polygons = {}
    for size in (3, 4, 5, 6):
        for verts in itertools.combinations(grid, size):
            hull = convex_hull(verts)
            if len(hull) != size:
                continue
            pts = lattice_points(hull, box)
            interior = [p for p in pts if inside(hull, p, strict=True)]
            if interior != [(0, 0)]:
                continue
            key = tuple(sorted(pts))
            polygons.setdefault(key, (tuple(hull), tuple(pts)))
    print(f"reflexive polygons enumerated (box {box}, with repeats): {len(polygons)}")
    orders = {}
    worst = {}
    for hull, pts in polygons.values():
        support = [p for p in pts if p != (0, 0)]
        # every sub-polygon containing the origin in its interior
        for r in range(3, len(support) + 1):
            for sub in itertools.combinations(support, r):
                ch = convex_hull(sub)
                if len(ch) < 3 or not inside(ch, (0, 0), strict=True):
                    continue
                cell_support = [p for p in support
                                if inside(ch, p, strict=False) or p in ch]
                m = index_of_differences(cell_support)
                orders[m] = orders.get(m, 0) + 1
                mv = index_of_differences(list(ch))
                worst[mv] = worst.get(mv, 0) + 1
    print("rotation orders m realised by a full-support central cell "
          "(m: how many cells):", dict(sorted(orders.items())))
    print("orders if only the cell's vertices are in the support "
          "(worst case):", dict(sorted(worst.items())))
    bad = sorted(m for m in orders if m >= 5 and any(m % p == 0 for p in (5, 7, 11, 13)))
    print("full-support orders divisible by a prime >= 5:", bad if bad else "none")
    badw = sorted(m for m in worst if any(m % p == 0 for p in (5, 7, 11, 13)))
    print("worst-case orders divisible by a prime >= 5:", badw if badw else "none")


if __name__ == "__main__":
    main()
