#!/usr/bin/env sage
"""Integral ambient-support index for the C904 Fano-sum divisor.

For the certified exotic principal lattice, compute the image of

    Hdg^3(J,Z)_div  -- cup [F+F] = 3 theta --> Hdg^4(J,Z),

where the source is the already-certified saturated lattice generated by
triple products of integral Neron--Severi classes.  Determine the exact
order of the minimal curve class theta^4/4! modulo that image.
"""

from contextlib import redirect_stdout
from io import StringIO
from itertools import combinations, combinations_with_replacement
import sys


_saved_argv = list(sys.argv)
sys.argv = [sys.argv[0], "--export-constants"]
with redirect_stdout(StringIO()):
    load("notes/2026-08-10-c904-minimal-class-divisor-lattice.sage")
sys.argv = _saved_argv


def main():
    _, _, basis, symplectic = principal_lattice("omega", 1)
    positions, linear_map = ns_integrality_matrix(basis)
    _, ns_lattice = congruence_kernel_lattice(linear_map)

    zero = zero_matrix(QQ, 5)
    divisor_forms = []
    for coordinates in ns_lattice.basis_matrix().LLL().rows():
        coefficient = coefficient_matrix(coordinates, positions)
        source_form = block_matrix(
            QQ, [[zero, coefficient], [-coefficient, zero]]
        )
        principal_form = basis * source_form * basis.transpose()
        assert principal_form.denominator() == 1
        divisor_forms.append(two_form(principal_form.change_ring(ZZ)))

    six_indices = list(combinations(range(10), 6))
    triple_rows = []
    for monomial in combinations_with_replacement(range(15), 3):
        value = wedge(wedge(divisor_forms[monomial[0]],
                            divisor_forms[monomial[1]]),
                      divisor_forms[monomial[2]])
        triple_rows.append(vector(
            ZZ, [value.get(indices, 0) for indices in six_indices]
        ))
    triple_lattice = span(ZZ, triple_rows)
    assert triple_lattice.rank() == 50
    assert triple_lattice == triple_lattice.saturation()

    theta = two_form(symplectic)
    eight_indices = list(combinations(range(10), 8))
    image_rows = []
    for row in triple_lattice.basis_matrix().rows():
        source = {
            indices: ZZ(value)
            for indices, value in zip(six_indices, row) if value
        }
        image = wedge(source, theta)
        image_rows.append(vector(
            ZZ, [3 * image.get(indices, 0) for indices in eight_indices]
        ))
    image_lattice = span(ZZ, image_rows)

    theta_squared = wedge(theta, theta)
    theta_fourth = wedge(theta_squared, theta_squared)
    assert all(value % factorial(4) == 0 for value in theta_fourth.values())
    minimal = vector(ZZ, [
        theta_fourth.get(indices, 0) // factorial(4)
        for indices in eight_indices
    ])
    assert minimal in span(QQ, image_rows)
    coordinates = image_lattice.coordinate_vector(minimal)
    order = lcm(value.denominator() for value in coordinates)
    assert order * minimal in image_lattice
    for proper_divisor in divisors(ZZ(order))[:-1]:
        assert proper_divisor * minimal not in image_lattice

    # Also report the corresponding index for theta rather than 3 theta.
    theta_image_rows = [vector(ZZ, [value // 3 for value in row])
                        for row in image_rows]
    theta_image_lattice = span(ZZ, theta_image_rows)
    theta_coordinates = theta_image_lattice.coordinate_vector(minimal)
    theta_order = lcm(value.denominator() for value in theta_coordinates)

    print("C904 Fano-sum ambient-support index")
    print(f"source rank={triple_lattice.rank()}; image rank={image_lattice.rank()}")
    print(f"order modulo theta image={theta_order}")
    print(f"order modulo 3theta=[F+F] image={order}")
    print("PASS")


if __name__ == "__main__":
    main()
