import RelativeConicArcs.Q25LineMaskComposition

/-!
# Generated C151 canonical row-composition certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-shared-line-composition.py`.

* payload: residual classes 390 through 394
* generator SHA256: `d569833d0340c3454299e4e6654d1fa9a67fc249db4f1e4102c59105c6292645`
* compact payload SHA256: `cf4d4903662c4f0cd0edb9a76c6c4427102304a1647df1c90340434ca769bf0a`
* shared line-data SHA256: `a67b4321bce4d034630b311ec249ae5e589a62fd57b580568d38326cc956231d`
* class order: lexicographic C150 internal-orbit canonical triples
-/

namespace RelativeConicArcs
namespace Q25RowCompositionData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open FiniteFields

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

def class0390A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0390B : OrbitCode := orbitCodeOfNumber ⟨62, by decide⟩
def class0390C : OrbitCode := orbitCodeOfNumber ⟨240, by decide⟩

def class0390Allowed : OrbitMask :=
  ![220731254243328, 1896208974484733952, 18068584623320136, 1229521056, 0]

def class0390LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 525, 150, 550, 175],
  ![0, 0, 10, 15, 13, 18, 20, 5],
  ![250, 10, 0, 629, 111, 496, 448, 159],
  ![375, 15, 629, 0, 356, 116, 549, 308],
  ![525, 13, 111, 356, 0, 627, 246, 415],
  ![150, 18, 496, 116, 627, 0, 285, 606],
  ![550, 20, 448, 549, 246, 285, 0, 26],
  ![175, 5, 159, 308, 415, 606, 26, 0]
]

def class0390Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 24, GF25.ofNat 9, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 15, GF25.ofNat 10],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 6, GF25.ofNat 18, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 19],
  ![GF25.ofNat 21, GF25.ofNat 13, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 14, GF25.ofNat 20],
  ![GF25.ofNat 14, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 20, GF25.ofNat 16, GF25.ofNat 1, GF25.ofNat 5],
  ![GF25.ofNat 19, GF25.ofNat 15, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 11, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1]
]

def class0390SecantCertificate :
    SecantCompositionCertificate class0390A class0390B class0390C class0390Allowed where
  lineNumber := class0390LineNumber
  scale := class0390Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0390FreshMaskSafe :
    FreshMaskSafe class0390A class0390B class0390C class0390Allowed := by
  decide

theorem class0390CarrierMaskSafe :
    CarrierMaskSafe class0390A class0390B class0390C class0390Allowed := by
  decide

def class0390RowCertificate :
    RowCompositionCertificate class0390A class0390B class0390C class0390Allowed where
  card_le := by decide
  fresh := class0390FreshMaskSafe
  secants := class0390SecantCertificate
  carrier := class0390CarrierMaskSafe

theorem class0390ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0390A class0390B class0390C) class0390Allowed :=
  class0390RowCertificate.toReflectedMaskCertificate

theorem class0390LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0390A class0390B class0390C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0390A class0390B class0390C)
    class0390ReflectedMaskCertificate

def class0391A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0391B : OrbitCode := orbitCodeOfNumber ⟨62, by decide⟩
def class0391C : OrbitCode := orbitCodeOfNumber ⟨241, by decide⟩

def class0391Allowed : OrbitMask :=
  ![589617405362176, 146951945829613568, 90109412450573520, 3221307620, 0]

def class0391LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 525, 150, 550, 175],
  ![0, 0, 10, 15, 13, 18, 8, 23],
  ![250, 10, 0, 629, 111, 496, 424, 544],
  ![375, 15, 629, 0, 356, 116, 164, 284],
  ![525, 13, 111, 356, 0, 627, 503, 258],
  ![150, 18, 496, 116, 627, 0, 398, 128],
  ![550, 8, 424, 164, 503, 398, 0, 626],
  ![175, 23, 544, 284, 258, 128, 626, 0]
]

def class0391Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 24, GF25.ofNat 9, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 12, GF25.ofNat 13],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 18, GF25.ofNat 17],
  ![GF25.ofNat 6, GF25.ofNat 18, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 11, GF25.ofNat 20],
  ![GF25.ofNat 21, GF25.ofNat 13, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 16],
  ![GF25.ofNat 14, GF25.ofNat 14, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 19, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 5],
  ![GF25.ofNat 19, GF25.ofNat 19, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 14, GF25.ofNat 20, GF25.ofNat 1]
]

def class0391SecantCertificate :
    SecantCompositionCertificate class0391A class0391B class0391C class0391Allowed where
  lineNumber := class0391LineNumber
  scale := class0391Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0391FreshMaskSafe :
    FreshMaskSafe class0391A class0391B class0391C class0391Allowed := by
  decide

theorem class0391CarrierMaskSafe :
    CarrierMaskSafe class0391A class0391B class0391C class0391Allowed := by
  decide

def class0391RowCertificate :
    RowCompositionCertificate class0391A class0391B class0391C class0391Allowed where
  card_le := by decide
  fresh := class0391FreshMaskSafe
  secants := class0391SecantCertificate
  carrier := class0391CarrierMaskSafe

theorem class0391ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0391A class0391B class0391C) class0391Allowed :=
  class0391RowCertificate.toReflectedMaskCertificate

theorem class0391LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0391A class0391B class0391C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0391A class0391B class0391C)
    class0391ReflectedMaskCertificate

def class0392A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0392B : OrbitCode := orbitCodeOfNumber ⟨62, by decide⟩
def class0392C : OrbitCode := orbitCodeOfNumber ⟨243, by decide⟩

def class0392Allowed : OrbitMask :=
  ![723562402938880, 1585482590364499968, 4926955724653988264, 1774715072, 0]

def class0392LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 525, 150, 550, 175],
  ![0, 0, 10, 15, 13, 18, 17, 12],
  ![250, 10, 0, 629, 111, 496, 515, 303],
  ![375, 15, 629, 0, 356, 116, 428, 135],
  ![525, 13, 111, 356, 0, 627, 393, 491],
  ![150, 18, 496, 116, 627, 0, 361, 263],
  ![550, 17, 515, 428, 393, 361, 0, 52],
  ![175, 12, 303, 135, 491, 263, 52, 0]
]

def class0392Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 24, GF25.ofNat 9, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 23],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 7],
  ![GF25.ofNat 6, GF25.ofNat 18, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 23, GF25.ofNat 7],
  ![GF25.ofNat 21, GF25.ofNat 13, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 22, GF25.ofNat 8],
  ![GF25.ofNat 14, GF25.ofNat 12, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 19, GF25.ofNat 17, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 10, GF25.ofNat 1]
]

def class0392SecantCertificate :
    SecantCompositionCertificate class0392A class0392B class0392C class0392Allowed where
  lineNumber := class0392LineNumber
  scale := class0392Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0392FreshMaskSafe :
    FreshMaskSafe class0392A class0392B class0392C class0392Allowed := by
  decide

theorem class0392CarrierMaskSafe :
    CarrierMaskSafe class0392A class0392B class0392C class0392Allowed := by
  decide

def class0392RowCertificate :
    RowCompositionCertificate class0392A class0392B class0392C class0392Allowed where
  card_le := by decide
  fresh := class0392FreshMaskSafe
  secants := class0392SecantCertificate
  carrier := class0392CarrierMaskSafe

theorem class0392ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0392A class0392B class0392C) class0392Allowed :=
  class0392RowCertificate.toReflectedMaskCertificate

theorem class0392LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0392A class0392B class0392C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0392A class0392B class0392C)
    class0392ReflectedMaskCertificate

def class0393A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0393B : OrbitCode := orbitCodeOfNumber ⟨62, by decide⟩
def class0393C : OrbitCode := orbitCodeOfNumber ⟨244, by decide⟩

def class0393Allowed : OrbitMask :=
  ![636690246926336, 577291983836151808, 9313497940638307408, 1149517984, 0]

def class0393LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 525, 150, 550, 175],
  ![0, 0, 10, 15, 13, 18, 7, 22],
  ![250, 10, 0, 629, 111, 496, 592, 448],
  ![375, 15, 629, 0, 356, 116, 308, 212],
  ![525, 13, 111, 356, 0, 627, 197, 601],
  ![150, 18, 496, 116, 627, 0, 226, 557],
  ![550, 7, 592, 308, 197, 226, 0, 78],
  ![175, 22, 448, 212, 601, 557, 78, 0]
]

def class0393Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 24, GF25.ofNat 9, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 19, GF25.ofNat 14],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 2, GF25.ofNat 3],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 3, GF25.ofNat 2],
  ![GF25.ofNat 6, GF25.ofNat 18, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 4, GF25.ofNat 13],
  ![GF25.ofNat 21, GF25.ofNat 13, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 4],
  ![GF25.ofNat 14, GF25.ofNat 11, GF25.ofNat 3, GF25.ofNat 2, GF25.ofNat 1, GF25.ofNat 12, GF25.ofNat 1, GF25.ofNat 10],
  ![GF25.ofNat 19, GF25.ofNat 16, GF25.ofNat 2, GF25.ofNat 3, GF25.ofNat 17, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 1]
]

def class0393SecantCertificate :
    SecantCompositionCertificate class0393A class0393B class0393C class0393Allowed where
  lineNumber := class0393LineNumber
  scale := class0393Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0393FreshMaskSafe :
    FreshMaskSafe class0393A class0393B class0393C class0393Allowed := by
  decide

theorem class0393CarrierMaskSafe :
    CarrierMaskSafe class0393A class0393B class0393C class0393Allowed := by
  decide

def class0393RowCertificate :
    RowCompositionCertificate class0393A class0393B class0393C class0393Allowed where
  card_le := by decide
  fresh := class0393FreshMaskSafe
  secants := class0393SecantCertificate
  carrier := class0393CarrierMaskSafe

theorem class0393ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0393A class0393B class0393C) class0393Allowed :=
  class0393RowCertificate.toReflectedMaskCertificate

theorem class0393LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0393A class0393B class0393C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0393A class0393B class0393C)
    class0393ReflectedMaskCertificate

def class0394A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0394B : OrbitCode := orbitCodeOfNumber ⟨62, by decide⟩
def class0394C : OrbitCode := orbitCodeOfNumber ⟨246, by decide⟩

def class0394Allowed : OrbitMask :=
  ![4200478015488, 885766585221120000, 9295485846110154816, 3309568096, 0]

def class0394LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 525, 150, 550, 175],
  ![0, 0, 10, 15, 13, 18, 6, 21],
  ![250, 10, 0, 629, 111, 496, 39, 592],
  ![375, 15, 629, 0, 356, 116, 212, 44],
  ![525, 13, 111, 356, 0, 627, 148, 62],
  ![150, 18, 496, 116, 627, 0, 67, 508],
  ![550, 6, 39, 212, 148, 67, 0, 103],
  ![175, 21, 592, 44, 62, 508, 103, 0]
]

def class0394Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 24, GF25.ofNat 9, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 21, GF25.ofNat 6],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 14, GF25.ofNat 11],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 16, GF25.ofNat 19],
  ![GF25.ofNat 6, GF25.ofNat 18, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 18, GF25.ofNat 18],
  ![GF25.ofNat 21, GF25.ofNat 13, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 13, GF25.ofNat 13],
  ![GF25.ofNat 14, GF25.ofNat 9, GF25.ofNat 16, GF25.ofNat 14, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 1, GF25.ofNat 10],
  ![GF25.ofNat 19, GF25.ofNat 24, GF25.ofNat 19, GF25.ofNat 11, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 15, GF25.ofNat 1]
]

def class0394SecantCertificate :
    SecantCompositionCertificate class0394A class0394B class0394C class0394Allowed where
  lineNumber := class0394LineNumber
  scale := class0394Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0394FreshMaskSafe :
    FreshMaskSafe class0394A class0394B class0394C class0394Allowed := by
  decide

theorem class0394CarrierMaskSafe :
    CarrierMaskSafe class0394A class0394B class0394C class0394Allowed := by
  decide

def class0394RowCertificate :
    RowCompositionCertificate class0394A class0394B class0394C class0394Allowed where
  card_le := by decide
  fresh := class0394FreshMaskSafe
  secants := class0394SecantCertificate
  carrier := class0394CarrierMaskSafe

theorem class0394ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0394A class0394B class0394C) class0394Allowed :=
  class0394RowCertificate.toReflectedMaskCertificate

theorem class0394LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0394A class0394B class0394C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0394A class0394B class0394C)
    class0394ReflectedMaskCertificate

end Q25RowCompositionData
end RelativeConicArcs
