import RelativeConicArcs.Q25LineMaskComposition

/-!
# Generated C151 canonical row-composition certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-shared-line-composition.py`.

* payload: residual classes 860 through 864
* generator SHA256: `d569833d0340c3454299e4e6654d1fa9a67fc249db4f1e4102c59105c6292645`
* compact payload SHA256: `cf4d4903662c4f0cd0edb9a76c6c4427102304a1647df1c90340434ca769bf0a`
* shared line-data SHA256: `a67b4321bce4d034630b311ec249ae5e589a62fd57b580568d38326cc956231d`
* class order: lexicographic C150 internal-orbit canonical triples
-/

namespace RelativeConicArcs
namespace Q25RowCompositionData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open FiniteFields

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

def class0860A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0860B : OrbitCode := orbitCodeOfNumber ⟨96, by decide⟩
def class0860C : OrbitCode := orbitCodeOfNumber ⟨111, by decide⟩

def class0860Allowed : OrbitMask :=
  ![720885727780405248, 1306, 2900357418177859824, 224124453632671873, 0]

def class0860LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 575, 200, 475, 350],
  ![0, 0, 10, 15, 6, 21, 23, 8],
  ![250, 10, 0, 629, 424, 111, 207, 616],
  ![375, 15, 629, 0, 116, 284, 236, 597],
  ![575, 6, 424, 116, 0, 76, 384, 454],
  ![200, 21, 111, 284, 76, 0, 329, 274],
  ![475, 23, 207, 236, 384, 329, 0, 27],
  ![350, 8, 616, 597, 454, 274, 27, 0]
]

def class0860Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 19, GF25.ofNat 14, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 21, GF25.ofNat 6, GF25.ofNat 11, GF25.ofNat 16],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 22, GF25.ofNat 23],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 8, GF25.ofNat 7],
  ![GF25.ofNat 11, GF25.ofNat 9, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 4, GF25.ofNat 19],
  ![GF25.ofNat 16, GF25.ofNat 24, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 14, GF25.ofNat 4],
  ![GF25.ofNat 7, GF25.ofNat 19, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 1, GF25.ofNat 16, GF25.ofNat 1, GF25.ofNat 20],
  ![GF25.ofNat 22, GF25.ofNat 14, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 11, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 1]
]

def class0860SecantCertificate :
    SecantCompositionCertificate class0860A class0860B class0860C class0860Allowed where
  lineNumber := class0860LineNumber
  scale := class0860Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0860FreshMaskSafe :
    FreshMaskSafe class0860A class0860B class0860C class0860Allowed := by
  decide

theorem class0860CarrierMaskSafe :
    CarrierMaskSafe class0860A class0860B class0860C class0860Allowed := by
  decide

def class0860RowCertificate :
    RowCompositionCertificate class0860A class0860B class0860C class0860Allowed where
  card_le := by decide
  fresh := class0860FreshMaskSafe
  secants := class0860SecantCertificate
  carrier := class0860CarrierMaskSafe

theorem class0860ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0860A class0860B class0860C) class0860Allowed :=
  class0860RowCertificate.toReflectedMaskCertificate

theorem class0860LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0860A class0860B class0860C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0860A class0860B class0860C)
    class0860ReflectedMaskCertificate

def class0861A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0861B : OrbitCode := orbitCodeOfNumber ⟨97, by decide⟩
def class0861C : OrbitCode := orbitCodeOfNumber ⟨111, by decide⟩

def class0861Allowed : OrbitMask :=
  ![9511630880049725440, 1034, 2882421615420772552, 20310732974407811, 0]

def class0861LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 575, 200, 475, 350],
  ![0, 0, 10, 15, 14, 19, 23, 8],
  ![250, 10, 0, 629, 63, 448, 207, 616],
  ![375, 15, 629, 0, 308, 68, 236, 597],
  ![575, 14, 63, 308, 0, 627, 85, 553],
  ![200, 19, 448, 68, 627, 0, 178, 90],
  ![475, 23, 207, 236, 85, 178, 0, 27],
  ![350, 8, 616, 597, 553, 90, 27, 0]
]

def class0861Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 19, GF25.ofNat 14, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 11, GF25.ofNat 16],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 9, GF25.ofNat 6, GF25.ofNat 22, GF25.ofNat 23],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 21, GF25.ofNat 24, GF25.ofNat 8, GF25.ofNat 7],
  ![GF25.ofNat 11, GF25.ofNat 8, GF25.ofNat 21, GF25.ofNat 9, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 22, GF25.ofNat 22],
  ![GF25.ofNat 16, GF25.ofNat 23, GF25.ofNat 24, GF25.ofNat 6, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 7, GF25.ofNat 7],
  ![GF25.ofNat 7, GF25.ofNat 19, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 20],
  ![GF25.ofNat 22, GF25.ofNat 14, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 23, GF25.ofNat 5, GF25.ofNat 1]
]

def class0861SecantCertificate :
    SecantCompositionCertificate class0861A class0861B class0861C class0861Allowed where
  lineNumber := class0861LineNumber
  scale := class0861Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0861FreshMaskSafe :
    FreshMaskSafe class0861A class0861B class0861C class0861Allowed := by
  decide

theorem class0861CarrierMaskSafe :
    CarrierMaskSafe class0861A class0861B class0861C class0861Allowed := by
  decide

def class0861RowCertificate :
    RowCompositionCertificate class0861A class0861B class0861C class0861Allowed where
  card_le := by decide
  fresh := class0861FreshMaskSafe
  secants := class0861SecantCertificate
  carrier := class0861CarrierMaskSafe

theorem class0861ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0861A class0861B class0861C) class0861Allowed :=
  class0861RowCertificate.toReflectedMaskCertificate

theorem class0861LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0861A class0861B class0861C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0861A class0861B class0861C)
    class0861ReflectedMaskCertificate

def class0862A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0862B : OrbitCode := orbitCodeOfNumber ⟨98, by decide⟩
def class0862C : OrbitCode := orbitCodeOfNumber ⟨111, by decide⟩

def class0862Allowed : OrbitMask :=
  ![5332271598860763136, 272, 2900418907077087368, 20654330761723907, 0]

def class0862LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 575, 200, 475, 350],
  ![0, 0, 10, 15, 11, 16, 23, 8],
  ![250, 10, 0, 629, 395, 351, 207, 616],
  ![375, 15, 629, 0, 476, 255, 236, 597],
  ![575, 11, 395, 476, 0, 54, 358, 649],
  ![200, 16, 351, 255, 54, 0, 634, 498],
  ![475, 23, 207, 236, 358, 634, 0, 27],
  ![350, 8, 616, 597, 649, 498, 27, 0]
]

def class0862Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 19, GF25.ofNat 14, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 11, GF25.ofNat 16],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 14, GF25.ofNat 11, GF25.ofNat 22, GF25.ofNat 23],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 16, GF25.ofNat 19, GF25.ofNat 8, GF25.ofNat 7],
  ![GF25.ofNat 11, GF25.ofNat 7, GF25.ofNat 16, GF25.ofNat 14, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 15, GF25.ofNat 7],
  ![GF25.ofNat 16, GF25.ofNat 22, GF25.ofNat 19, GF25.ofNat 11, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 22, GF25.ofNat 10],
  ![GF25.ofNat 7, GF25.ofNat 19, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 10, GF25.ofNat 8, GF25.ofNat 1, GF25.ofNat 20],
  ![GF25.ofNat 22, GF25.ofNat 14, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 23, GF25.ofNat 15, GF25.ofNat 5, GF25.ofNat 1]
]

def class0862SecantCertificate :
    SecantCompositionCertificate class0862A class0862B class0862C class0862Allowed where
  lineNumber := class0862LineNumber
  scale := class0862Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0862FreshMaskSafe :
    FreshMaskSafe class0862A class0862B class0862C class0862Allowed := by
  decide

theorem class0862CarrierMaskSafe :
    CarrierMaskSafe class0862A class0862B class0862C class0862Allowed := by
  decide

def class0862RowCertificate :
    RowCompositionCertificate class0862A class0862B class0862C class0862Allowed where
  card_le := by decide
  fresh := class0862FreshMaskSafe
  secants := class0862SecantCertificate
  carrier := class0862CarrierMaskSafe

theorem class0862ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0862A class0862B class0862C) class0862Allowed :=
  class0862RowCertificate.toReflectedMaskCertificate

theorem class0862LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0862A class0862B class0862C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0862A class0862B class0862C)
    class0862ReflectedMaskCertificate

def class0863A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0863B : OrbitCode := orbitCodeOfNumber ⟨111, by decide⟩
def class0863C : OrbitCode := orbitCodeOfNumber ⟨131, by decide⟩

def class0863Allowed : OrbitMask :=
  ![10088354673330225152, 26595034410, 3062572543329173504, 222127740379299972, 0]

def class0863LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 23, 8, 21, 6],
  ![250, 10, 0, 629, 207, 616, 279, 544],
  ![375, 15, 629, 0, 236, 597, 164, 404],
  ![475, 23, 207, 236, 0, 27, 442, 174],
  ![350, 8, 616, 597, 27, 0, 534, 312],
  ![325, 21, 279, 164, 442, 534, 0, 628],
  ![450, 6, 544, 404, 174, 312, 628, 0]
]

def class0863Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 11, GF25.ofNat 16, GF25.ofNat 6, GF25.ofNat 21],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 8, GF25.ofNat 7, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 7, GF25.ofNat 19, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 11],
  ![GF25.ofNat 22, GF25.ofNat 14, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 16, GF25.ofNat 19],
  ![GF25.ofNat 12, GF25.ofNat 24, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 16, GF25.ofNat 14, GF25.ofNat 1, GF25.ofNat 10],
  ![GF25.ofNat 17, GF25.ofNat 9, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 19, GF25.ofNat 11, GF25.ofNat 15, GF25.ofNat 1]
]

def class0863SecantCertificate :
    SecantCompositionCertificate class0863A class0863B class0863C class0863Allowed where
  lineNumber := class0863LineNumber
  scale := class0863Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0863FreshMaskSafe :
    FreshMaskSafe class0863A class0863B class0863C class0863Allowed := by
  decide

theorem class0863CarrierMaskSafe :
    CarrierMaskSafe class0863A class0863B class0863C class0863Allowed := by
  decide

def class0863RowCertificate :
    RowCompositionCertificate class0863A class0863B class0863C class0863Allowed where
  card_le := by decide
  fresh := class0863FreshMaskSafe
  secants := class0863SecantCertificate
  carrier := class0863CarrierMaskSafe

theorem class0863ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0863A class0863B class0863C) class0863Allowed :=
  class0863RowCertificate.toReflectedMaskCertificate

theorem class0863LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0863A class0863B class0863C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0863A class0863B class0863C)
    class0863ReflectedMaskCertificate

def class0864A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0864B : OrbitCode := orbitCodeOfNumber ⟨111, by decide⟩
def class0864C : OrbitCode := orbitCodeOfNumber ⟨132, by decide⟩

def class0864Allowed : OrbitMask :=
  ![14123571993764691968, 4580311056, 2350996195817553920, 75822326687547398, 0]

def class0864LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 23, 8, 19, 14],
  ![250, 10, 0, 629, 207, 616, 39, 231],
  ![375, 15, 629, 0, 236, 597, 621, 44],
  ![475, 23, 207, 236, 0, 27, 413, 358],
  ![350, 8, 616, 597, 27, 0, 498, 293],
  ![325, 19, 39, 621, 413, 498, 0, 79],
  ![450, 14, 231, 44, 358, 293, 79, 0]
]

def class0864Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 11, GF25.ofNat 16, GF25.ofNat 7, GF25.ofNat 22],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 3, GF25.ofNat 2],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 8, GF25.ofNat 7, GF25.ofNat 2, GF25.ofNat 3],
  ![GF25.ofNat 7, GF25.ofNat 19, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 16, GF25.ofNat 18],
  ![GF25.ofNat 22, GF25.ofNat 14, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 13, GF25.ofNat 11],
  ![GF25.ofNat 12, GF25.ofNat 23, GF25.ofNat 2, GF25.ofNat 3, GF25.ofNat 14, GF25.ofNat 17, GF25.ofNat 1, GF25.ofNat 20],
  ![GF25.ofNat 17, GF25.ofNat 8, GF25.ofNat 3, GF25.ofNat 2, GF25.ofNat 12, GF25.ofNat 19, GF25.ofNat 5, GF25.ofNat 1]
]

def class0864SecantCertificate :
    SecantCompositionCertificate class0864A class0864B class0864C class0864Allowed where
  lineNumber := class0864LineNumber
  scale := class0864Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0864FreshMaskSafe :
    FreshMaskSafe class0864A class0864B class0864C class0864Allowed := by
  decide

theorem class0864CarrierMaskSafe :
    CarrierMaskSafe class0864A class0864B class0864C class0864Allowed := by
  decide

def class0864RowCertificate :
    RowCompositionCertificate class0864A class0864B class0864C class0864Allowed where
  card_le := by decide
  fresh := class0864FreshMaskSafe
  secants := class0864SecantCertificate
  carrier := class0864CarrierMaskSafe

theorem class0864ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0864A class0864B class0864C) class0864Allowed :=
  class0864RowCertificate.toReflectedMaskCertificate

theorem class0864LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0864A class0864B class0864C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0864A class0864B class0864C)
    class0864ReflectedMaskCertificate

end Q25RowCompositionData
end RelativeConicArcs
