import RelativeConicArcs.Q25LineMaskComposition

/-!
# Generated C151 canonical row-composition certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-shared-line-composition.py`.

* payload: residual classes 960 through 964
* generator SHA256: `d569833d0340c3454299e4e6654d1fa9a67fc249db4f1e4102c59105c6292645`
* compact payload SHA256: `cf4d4903662c4f0cd0edb9a76c6c4427102304a1647df1c90340434ca769bf0a`
* shared line-data SHA256: `a67b4321bce4d034630b311ec249ae5e589a62fd57b580568d38326cc956231d`
* class order: lexicographic C150 internal-orbit canonical triples
-/

namespace RelativeConicArcs
namespace Q25RowCompositionData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open FiniteFields

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

def class0960A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0960B : OrbitCode := orbitCodeOfNumber ⟨36, by decide⟩
def class0960C : OrbitCode := orbitCodeOfNumber ⟨113, by decide⟩

def class0960Allowed : OrbitMask :=
  ![4899916394579099648, 44059984386, 756686719736436888, 148902468724752513, 0]

def class0960LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 125, 500, 475, 350],
  ![0, 0, 10, 15, 23, 8, 12, 17],
  ![250, 10, 0, 629, 351, 327, 472, 130],
  ![375, 15, 629, 0, 452, 476, 520, 332],
  ![125, 23, 351, 452, 0, 29, 218, 547],
  ![500, 8, 327, 476, 29, 0, 157, 588],
  ![475, 12, 472, 520, 218, 157, 0, 76],
  ![350, 17, 130, 332, 547, 588, 76, 0]
]

def class0960Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 11, GF25.ofNat 16, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 5, GF25.ofNat 5, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 20, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 10, GF25.ofNat 19, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 7, GF25.ofNat 19],
  ![GF25.ofNat 15, GF25.ofNat 14, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 14, GF25.ofNat 22],
  ![GF25.ofNat 7, GF25.ofNat 17, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 16, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 22, GF25.ofNat 12, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 11, GF25.ofNat 8, GF25.ofNat 10, GF25.ofNat 1]
]

def class0960SecantCertificate :
    SecantCompositionCertificate class0960A class0960B class0960C class0960Allowed where
  lineNumber := class0960LineNumber
  scale := class0960Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0960FreshMaskSafe :
    FreshMaskSafe class0960A class0960B class0960C class0960Allowed := by
  decide

theorem class0960CarrierMaskSafe :
    CarrierMaskSafe class0960A class0960B class0960C class0960Allowed := by
  decide

def class0960RowCertificate :
    RowCompositionCertificate class0960A class0960B class0960C class0960Allowed where
  card_le := by decide
  fresh := class0960FreshMaskSafe
  secants := class0960SecantCertificate
  carrier := class0960CarrierMaskSafe

theorem class0960ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0960A class0960B class0960C) class0960Allowed :=
  class0960RowCertificate.toReflectedMaskCertificate

theorem class0960LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0960A class0960B class0960C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0960A class0960B class0960C)
    class0960ReflectedMaskCertificate

def class0961A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0961B : OrbitCode := orbitCodeOfNumber ⟨37, by decide⟩
def class0961C : OrbitCode := orbitCodeOfNumber ⟨113, by decide⟩

def class0961Allowed : OrbitMask :=
  ![144115188075855872, 9698148868, 45124303218028952, 149479705844744340, 0]

def class0961LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 125, 500, 475, 350],
  ![0, 0, 10, 15, 13, 18, 12, 17],
  ![250, 10, 0, 629, 303, 351, 472, 130],
  ![375, 15, 629, 0, 476, 428, 520, 332],
  ![125, 13, 303, 476, 0, 77, 633, 219],
  ![500, 18, 351, 428, 77, 0, 589, 648],
  ![475, 12, 472, 520, 633, 589, 0, 76],
  ![350, 17, 130, 332, 219, 648, 76, 0]
]

def class0961Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 10, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 15, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 10, GF25.ofNat 18, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 4, GF25.ofNat 22],
  ![GF25.ofNat 15, GF25.ofNat 13, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 7, GF25.ofNat 4],
  ![GF25.ofNat 7, GF25.ofNat 17, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 22, GF25.ofNat 12, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 8, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 1]
]

def class0961SecantCertificate :
    SecantCompositionCertificate class0961A class0961B class0961C class0961Allowed where
  lineNumber := class0961LineNumber
  scale := class0961Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0961FreshMaskSafe :
    FreshMaskSafe class0961A class0961B class0961C class0961Allowed := by
  decide

theorem class0961CarrierMaskSafe :
    CarrierMaskSafe class0961A class0961B class0961C class0961Allowed := by
  decide

def class0961RowCertificate :
    RowCompositionCertificate class0961A class0961B class0961C class0961Allowed where
  card_le := by decide
  fresh := class0961FreshMaskSafe
  secants := class0961SecantCertificate
  carrier := class0961CarrierMaskSafe

theorem class0961ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0961A class0961B class0961C) class0961Allowed :=
  class0961RowCertificate.toReflectedMaskCertificate

theorem class0961LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0961A class0961B class0961C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0961A class0961B class0961C)
    class0961ReflectedMaskCertificate

def class0962A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0962B : OrbitCode := orbitCodeOfNumber ⟨39, by decide⟩
def class0962C : OrbitCode := orbitCodeOfNumber ⟨113, by decide⟩

def class0962Allowed : OrbitMask :=
  ![5044031582654955520, 43218501770, 540441037262053504, 163848125449011328, 0]

def class0962LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 125, 500, 475, 350],
  ![0, 0, 10, 15, 22, 7, 12, 17],
  ![250, 10, 0, 629, 279, 303, 472, 130],
  ![375, 15, 629, 0, 428, 404, 520, 332],
  ![125, 22, 279, 428, 0, 101, 556, 386],
  ![500, 7, 303, 404, 101, 0, 266, 196],
  ![475, 12, 472, 520, 556, 266, 0, 76],
  ![350, 17, 130, 332, 386, 196, 76, 0]
]

def class0962Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 19, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 20, GF25.ofNat 20, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 10, GF25.ofNat 16, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 16, GF25.ofNat 8],
  ![GF25.ofNat 15, GF25.ofNat 11, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 11],
  ![GF25.ofNat 7, GF25.ofNat 17, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 14, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 22, GF25.ofNat 12, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 19, GF25.ofNat 10, GF25.ofNat 1]
]

def class0962SecantCertificate :
    SecantCompositionCertificate class0962A class0962B class0962C class0962Allowed where
  lineNumber := class0962LineNumber
  scale := class0962Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0962FreshMaskSafe :
    FreshMaskSafe class0962A class0962B class0962C class0962Allowed := by
  decide

theorem class0962CarrierMaskSafe :
    CarrierMaskSafe class0962A class0962B class0962C class0962Allowed := by
  decide

def class0962RowCertificate :
    RowCompositionCertificate class0962A class0962B class0962C class0962Allowed where
  card_le := by decide
  fresh := class0962FreshMaskSafe
  secants := class0962SecantCertificate
  carrier := class0962CarrierMaskSafe

theorem class0962ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0962A class0962B class0962C) class0962Allowed :=
  class0962RowCertificate.toReflectedMaskCertificate

theorem class0962LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0962A class0962B class0962C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0962A class0962B class0962C)
    class0962ReflectedMaskCertificate

def class0963A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0963B : OrbitCode := orbitCodeOfNumber ⟨40, by decide⟩
def class0963C : OrbitCode := orbitCodeOfNumber ⟨113, by decide⟩

def class0963Allowed : OrbitMask :=
  ![4611686018427387904, 42958717476, 693634134518024456, 18039694931525664, 0]

def class0963LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 125, 500, 475, 350],
  ![0, 0, 10, 15, 20, 5, 12, 17],
  ![250, 10, 0, 629, 515, 395, 472, 130],
  ![375, 15, 629, 0, 255, 135, 520, 332],
  ![125, 20, 515, 255, 0, 626, 411, 124],
  ![500, 5, 395, 135, 626, 0, 109, 291],
  ![475, 12, 472, 520, 411, 109, 0, 76],
  ![350, 17, 130, 332, 124, 291, 76, 0]
]

def class0963Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 2, GF25.ofNat 3, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 3, GF25.ofNat 2, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 10, GF25.ofNat 10, GF25.ofNat 3, GF25.ofNat 2, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 2, GF25.ofNat 3],
  ![GF25.ofNat 15, GF25.ofNat 15, GF25.ofNat 2, GF25.ofNat 3, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 3, GF25.ofNat 2],
  ![GF25.ofNat 7, GF25.ofNat 17, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 3, GF25.ofNat 2, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 22, GF25.ofNat 12, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 2, GF25.ofNat 3, GF25.ofNat 10, GF25.ofNat 1]
]

def class0963SecantCertificate :
    SecantCompositionCertificate class0963A class0963B class0963C class0963Allowed where
  lineNumber := class0963LineNumber
  scale := class0963Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0963FreshMaskSafe :
    FreshMaskSafe class0963A class0963B class0963C class0963Allowed := by
  decide

theorem class0963CarrierMaskSafe :
    CarrierMaskSafe class0963A class0963B class0963C class0963Allowed := by
  decide

def class0963RowCertificate :
    RowCompositionCertificate class0963A class0963B class0963C class0963Allowed where
  card_le := by decide
  fresh := class0963FreshMaskSafe
  secants := class0963SecantCertificate
  carrier := class0963CarrierMaskSafe

theorem class0963ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0963A class0963B class0963C) class0963Allowed :=
  class0963RowCertificate.toReflectedMaskCertificate

theorem class0963LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0963A class0963B class0963C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0963A class0963B class0963C)
    class0963ReflectedMaskCertificate

def class0964A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class0964B : OrbitCode := orbitCodeOfNumber ⟨41, by decide⟩
def class0964C : OrbitCode := orbitCodeOfNumber ⟨113, by decide⟩

def class0964Allowed : OrbitMask :=
  ![1441151880758558720, 26845774474, 4764835346211426448, 22534497425785009, 0]

def class0964LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 125, 500, 475, 350],
  ![0, 0, 10, 15, 8, 23, 12, 17],
  ![250, 10, 0, 629, 159, 568, 472, 130],
  ![375, 15, 629, 0, 188, 549, 520, 332],
  ![125, 8, 159, 188, 0, 104, 246, 427],
  ![500, 23, 568, 549, 104, 0, 302, 606],
  ![475, 12, 472, 520, 246, 302, 0, 76],
  ![350, 17, 130, 332, 427, 606, 76, 0]
]

def class0964Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 8],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 16, GF25.ofNat 11, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 10, GF25.ofNat 14, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 20, GF25.ofNat 6],
  ![GF25.ofNat 15, GF25.ofNat 19, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 21, GF25.ofNat 5],
  ![GF25.ofNat 7, GF25.ofNat 17, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 5, GF25.ofNat 9, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 22, GF25.ofNat 12, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 24, GF25.ofNat 20, GF25.ofNat 10, GF25.ofNat 1]
]

def class0964SecantCertificate :
    SecantCompositionCertificate class0964A class0964B class0964C class0964Allowed where
  lineNumber := class0964LineNumber
  scale := class0964Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class0964FreshMaskSafe :
    FreshMaskSafe class0964A class0964B class0964C class0964Allowed := by
  decide

theorem class0964CarrierMaskSafe :
    CarrierMaskSafe class0964A class0964B class0964C class0964Allowed := by
  decide

def class0964RowCertificate :
    RowCompositionCertificate class0964A class0964B class0964C class0964Allowed where
  card_le := by decide
  fresh := class0964FreshMaskSafe
  secants := class0964SecantCertificate
  carrier := class0964CarrierMaskSafe

theorem class0964ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class0964A class0964B class0964C) class0964Allowed :=
  class0964RowCertificate.toReflectedMaskCertificate

theorem class0964LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class0964A class0964B class0964C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class0964A class0964B class0964C)
    class0964ReflectedMaskCertificate

end Q25RowCompositionData
end RelativeConicArcs
