import RelativeConicArcs.Q25LineMaskComposition

/-!
# Generated C151 canonical row-composition certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-shared-line-composition.py`.

* payload: residual classes 1045 through 1049
* generator SHA256: `d569833d0340c3454299e4e6654d1fa9a67fc249db4f1e4102c59105c6292645`
* compact payload SHA256: `cf4d4903662c4f0cd0edb9a76c6c4427102304a1647df1c90340434ca769bf0a`
* shared line-data SHA256: `a67b4321bce4d034630b311ec249ae5e589a62fd57b580568d38326cc956231d`
* class order: lexicographic C150 internal-orbit canonical triples
-/

namespace RelativeConicArcs
namespace Q25RowCompositionData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open FiniteFields

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

def class1045A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1045B : OrbitCode := orbitCodeOfNumber ⟨114, by decide⟩
def class1045C : OrbitCode := orbitCodeOfNumber ⟨134, by decide⟩

def class1045Allowed : OrbitMask :=
  ![2738691050255155200, 4590927898, 9655780566108209152, 21491056994746402, 0]

def class1045LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 22, 7, 24, 9],
  ![250, 10, 0, 629, 159, 279, 472, 351],
  ![375, 15, 629, 0, 404, 549, 476, 332],
  ![475, 22, 159, 404, 0, 627, 208, 294],
  ![350, 7, 279, 549, 627, 0, 414, 598],
  ![325, 24, 472, 476, 208, 414, 0, 28],
  ![450, 9, 351, 332, 294, 598, 28, 0]
]

def class1045Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 19, GF25.ofNat 9, GF25.ofNat 24],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 12, GF25.ofNat 13, GF25.ofNat 13, GF25.ofNat 12],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 17, GF25.ofNat 17, GF25.ofNat 18],
  ![GF25.ofNat 7, GF25.ofNat 16, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 24, GF25.ofNat 6],
  ![GF25.ofNat 22, GF25.ofNat 11, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 21, GF25.ofNat 9],
  ![GF25.ofNat 12, GF25.ofNat 21, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 6, GF25.ofNat 9, GF25.ofNat 1, GF25.ofNat 10],
  ![GF25.ofNat 17, GF25.ofNat 6, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 24, GF25.ofNat 21, GF25.ofNat 15, GF25.ofNat 1]
]

def class1045SecantCertificate :
    SecantCompositionCertificate class1045A class1045B class1045C class1045Allowed where
  lineNumber := class1045LineNumber
  scale := class1045Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1045FreshMaskSafe :
    FreshMaskSafe class1045A class1045B class1045C class1045Allowed := by
  decide

theorem class1045CarrierMaskSafe :
    CarrierMaskSafe class1045A class1045B class1045C class1045Allowed := by
  decide

def class1045RowCertificate :
    RowCompositionCertificate class1045A class1045B class1045C class1045Allowed where
  card_le := by decide
  fresh := class1045FreshMaskSafe
  secants := class1045SecantCertificate
  carrier := class1045CarrierMaskSafe

theorem class1045ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1045A class1045B class1045C) class1045Allowed :=
  class1045RowCertificate.toReflectedMaskCertificate

theorem class1045LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1045A class1045B class1045C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1045A class1045B class1045C)
    class1045ReflectedMaskCertificate

def class1046A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1046B : OrbitCode := orbitCodeOfNumber ⟨114, by decide⟩
def class1046C : OrbitCode := orbitCodeOfNumber ⟨135, by decide⟩

def class1046Allowed : OrbitMask :=
  ![11818435135156518912, 56799264792, 90082457235226624, 1767468700336352, 0]

def class1046LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 22, 7, 5, 20],
  ![250, 10, 0, 629, 159, 279, 87, 39],
  ![375, 15, 629, 0, 404, 549, 44, 92],
  ![475, 22, 159, 404, 0, 627, 316, 610],
  ![350, 7, 279, 549, 627, 0, 240, 436],
  ![325, 5, 87, 44, 316, 240, 0, 53],
  ![450, 20, 39, 92, 610, 436, 53, 0]
]

def class1046Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 19, GF25.ofNat 10, GF25.ofNat 15],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 12, GF25.ofNat 13, GF25.ofNat 15, GF25.ofNat 15],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 17, GF25.ofNat 10, GF25.ofNat 10],
  ![GF25.ofNat 7, GF25.ofNat 16, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 13, GF25.ofNat 1],
  ![GF25.ofNat 22, GF25.ofNat 11, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 18],
  ![GF25.ofNat 12, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 15, GF25.ofNat 17, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 10],
  ![GF25.ofNat 17, GF25.ofNat 10, GF25.ofNat 10, GF25.ofNat 15, GF25.ofNat 4, GF25.ofNat 12, GF25.ofNat 15, GF25.ofNat 1]
]

def class1046SecantCertificate :
    SecantCompositionCertificate class1046A class1046B class1046C class1046Allowed where
  lineNumber := class1046LineNumber
  scale := class1046Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1046FreshMaskSafe :
    FreshMaskSafe class1046A class1046B class1046C class1046Allowed := by
  decide

theorem class1046CarrierMaskSafe :
    CarrierMaskSafe class1046A class1046B class1046C class1046Allowed := by
  decide

def class1046RowCertificate :
    RowCompositionCertificate class1046A class1046B class1046C class1046Allowed where
  card_le := by decide
  fresh := class1046FreshMaskSafe
  secants := class1046SecantCertificate
  carrier := class1046CarrierMaskSafe

theorem class1046ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1046A class1046B class1046C) class1046Allowed :=
  class1046RowCertificate.toReflectedMaskCertificate

theorem class1046LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1046A class1046B class1046C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1046A class1046B class1046C)
    class1046ReflectedMaskCertificate

def class1047A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1047B : OrbitCode := orbitCodeOfNumber ⟨114, by decide⟩
def class1047C : OrbitCode := orbitCodeOfNumber ⟨136, by decide⟩

def class1047Allowed : OrbitMask :=
  ![10520773926311690240, 35233203226, 4845936558676639744, 147506083044556896, 0]

def class1047LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 22, 7, 23, 8],
  ![250, 10, 0, 629, 159, 279, 424, 448],
  ![375, 15, 629, 0, 404, 549, 308, 284],
  ![475, 22, 159, 404, 0, 627, 377, 343],
  ![350, 7, 279, 549, 627, 0, 463, 252],
  ![325, 23, 424, 308, 377, 463, 0, 101],
  ![450, 8, 448, 284, 343, 252, 101, 0]
]

def class1047Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 19, GF25.ofNat 11, GF25.ofNat 16],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 12, GF25.ofNat 13, GF25.ofNat 20, GF25.ofNat 20],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 17, GF25.ofNat 5, GF25.ofNat 5],
  ![GF25.ofNat 7, GF25.ofNat 16, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 15, GF25.ofNat 8],
  ![GF25.ofNat 22, GF25.ofNat 11, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 10],
  ![GF25.ofNat 12, GF25.ofNat 19, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 10, GF25.ofNat 7, GF25.ofNat 1, GF25.ofNat 5],
  ![GF25.ofNat 17, GF25.ofNat 14, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 15, GF25.ofNat 20, GF25.ofNat 1]
]

def class1047SecantCertificate :
    SecantCompositionCertificate class1047A class1047B class1047C class1047Allowed where
  lineNumber := class1047LineNumber
  scale := class1047Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1047FreshMaskSafe :
    FreshMaskSafe class1047A class1047B class1047C class1047Allowed := by
  decide

theorem class1047CarrierMaskSafe :
    CarrierMaskSafe class1047A class1047B class1047C class1047Allowed := by
  decide

def class1047RowCertificate :
    RowCompositionCertificate class1047A class1047B class1047C class1047Allowed where
  card_le := by decide
  fresh := class1047FreshMaskSafe
  secants := class1047SecantCertificate
  carrier := class1047CarrierMaskSafe

theorem class1047ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1047A class1047B class1047C) class1047Allowed :=
  class1047RowCertificate.toReflectedMaskCertificate

theorem class1047LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1047A class1047B class1047C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1047A class1047B class1047C)
    class1047ReflectedMaskCertificate

def class1048A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1048B : OrbitCode := orbitCodeOfNumber ⟨114, by decide⟩
def class1048C : OrbitCode := orbitCodeOfNumber ⟨138, by decide⟩

def class1048Allowed : OrbitMask :=
  ![1441996337900945408, 39060898946, 9655779607525195776, 163818987276566560, 0]

def class1048LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 22, 7, 12, 17],
  ![250, 10, 0, 629, 159, 279, 231, 207],
  ![375, 15, 629, 0, 404, 549, 597, 621],
  ![475, 22, 159, 404, 0, 627, 120, 98],
  ![350, 7, 279, 549, 627, 0, 83, 105],
  ![325, 12, 231, 597, 120, 83, 0, 29],
  ![450, 17, 207, 621, 98, 105, 29, 0]
]

def class1048Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 19, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 12, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 5],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 17, GF25.ofNat 20, GF25.ofNat 20],
  ![GF25.ofNat 7, GF25.ofNat 16, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 4, GF25.ofNat 17],
  ![GF25.ofNat 22, GF25.ofNat 11, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 12, GF25.ofNat 4],
  ![GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 1, GF25.ofNat 20],
  ![GF25.ofNat 17, GF25.ofNat 12, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 13, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 1]
]

def class1048SecantCertificate :
    SecantCompositionCertificate class1048A class1048B class1048C class1048Allowed where
  lineNumber := class1048LineNumber
  scale := class1048Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1048FreshMaskSafe :
    FreshMaskSafe class1048A class1048B class1048C class1048Allowed := by
  decide

theorem class1048CarrierMaskSafe :
    CarrierMaskSafe class1048A class1048B class1048C class1048Allowed := by
  decide

def class1048RowCertificate :
    RowCompositionCertificate class1048A class1048B class1048C class1048Allowed where
  card_le := by decide
  fresh := class1048FreshMaskSafe
  secants := class1048SecantCertificate
  carrier := class1048CarrierMaskSafe

theorem class1048ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1048A class1048B class1048C) class1048Allowed :=
  class1048RowCertificate.toReflectedMaskCertificate

theorem class1048LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1048A class1048B class1048C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1048A class1048B class1048C)
    class1048ReflectedMaskCertificate

def class1049A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1049B : OrbitCode := orbitCodeOfNumber ⟨114, by decide⟩
def class1049C : OrbitCode := orbitCodeOfNumber ⟨141, by decide⟩

def class1049Allowed : OrbitMask :=
  ![10377283252250476544, 38739902602, 90125890897313792, 164499587128950786, 0]

def class1049LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 22, 7, 8, 23],
  ![250, 10, 0, 629, 159, 279, 63, 395],
  ![375, 15, 629, 0, 404, 549, 255, 68],
  ![475, 22, 159, 404, 0, 627, 365, 316],
  ![350, 7, 279, 549, 627, 0, 436, 485],
  ![325, 8, 63, 255, 365, 436, 0, 78],
  ![450, 23, 395, 68, 316, 485, 78, 0]
]

def class1049Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 14, GF25.ofNat 19, GF25.ofNat 16, GF25.ofNat 11],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 12, GF25.ofNat 13, GF25.ofNat 22, GF25.ofNat 23],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 18, GF25.ofNat 17, GF25.ofNat 8, GF25.ofNat 7],
  ![GF25.ofNat 7, GF25.ofNat 16, GF25.ofNat 18, GF25.ofNat 12, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 2, GF25.ofNat 21],
  ![GF25.ofNat 22, GF25.ofNat 11, GF25.ofNat 17, GF25.ofNat 13, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 6, GF25.ofNat 2],
  ![GF25.ofNat 12, GF25.ofNat 14, GF25.ofNat 8, GF25.ofNat 22, GF25.ofNat 3, GF25.ofNat 24, GF25.ofNat 1, GF25.ofNat 10],
  ![GF25.ofNat 17, GF25.ofNat 19, GF25.ofNat 7, GF25.ofNat 23, GF25.ofNat 9, GF25.ofNat 3, GF25.ofNat 15, GF25.ofNat 1]
]

def class1049SecantCertificate :
    SecantCompositionCertificate class1049A class1049B class1049C class1049Allowed where
  lineNumber := class1049LineNumber
  scale := class1049Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1049FreshMaskSafe :
    FreshMaskSafe class1049A class1049B class1049C class1049Allowed := by
  decide

theorem class1049CarrierMaskSafe :
    CarrierMaskSafe class1049A class1049B class1049C class1049Allowed := by
  decide

def class1049RowCertificate :
    RowCompositionCertificate class1049A class1049B class1049C class1049Allowed where
  card_le := by decide
  fresh := class1049FreshMaskSafe
  secants := class1049SecantCertificate
  carrier := class1049CarrierMaskSafe

theorem class1049ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1049A class1049B class1049C) class1049Allowed :=
  class1049RowCertificate.toReflectedMaskCertificate

theorem class1049LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1049A class1049B class1049C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1049A class1049B class1049C)
    class1049ReflectedMaskCertificate

end Q25RowCompositionData
end RelativeConicArcs
