import RelativeConicArcs.Q25LineMaskComposition

/-!
# Generated C151 canonical row-composition certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-shared-line-composition.py`.

* payload: residual classes 1160 through 1164
* generator SHA256: `d569833d0340c3454299e4e6654d1fa9a67fc249db4f1e4102c59105c6292645`
* compact payload SHA256: `cf4d4903662c4f0cd0edb9a76c6c4427102304a1647df1c90340434ca769bf0a`
* shared line-data SHA256: `a67b4321bce4d034630b311ec249ae5e589a62fd57b580568d38326cc956231d`
* class order: lexicographic C150 internal-orbit canonical triples
-/

namespace RelativeConicArcs
namespace Q25RowCompositionData

open Q25Coordinates Q25PairCertificate Q25MinimumMask Q25LineMaskComposition
open FiniteFields

set_option maxHeartbeats 300000000
set_option maxRecDepth 100000

def class1160A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1160B : OrbitCode := orbitCodeOfNumber ⟨122, by decide⟩
def class1160C : OrbitCode := orbitCodeOfNumber ⟨138, by decide⟩

def class1160Allowed : OrbitMask :=
  ![4900762623395495936, 56908841127, 405394833692164096, 90670681612681221, 0]

def class1160LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 14, 19, 12, 17],
  ![250, 10, 0, 629, 327, 63, 231, 207],
  ![375, 15, 629, 0, 68, 452, 597, 621],
  ![475, 14, 327, 68, 0, 26, 642, 540],
  ![350, 19, 63, 452, 26, 0, 160, 637],
  ![325, 12, 231, 597, 642, 160, 0, 29],
  ![450, 17, 207, 621, 540, 637, 29, 0]
]

def class1160Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 13, GF25.ofNat 18],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 5, GF25.ofNat 5],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 20, GF25.ofNat 20],
  ![GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 14, GF25.ofNat 4],
  ![GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 19],
  ![GF25.ofNat 12, GF25.ofNat 17, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 16, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 20],
  ![GF25.ofNat 17, GF25.ofNat 12, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 1, GF25.ofNat 11, GF25.ofNat 5, GF25.ofNat 1]
]

def class1160SecantCertificate :
    SecantCompositionCertificate class1160A class1160B class1160C class1160Allowed where
  lineNumber := class1160LineNumber
  scale := class1160Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1160FreshMaskSafe :
    FreshMaskSafe class1160A class1160B class1160C class1160Allowed := by
  decide

theorem class1160CarrierMaskSafe :
    CarrierMaskSafe class1160A class1160B class1160C class1160Allowed := by
  decide

def class1160RowCertificate :
    RowCompositionCertificate class1160A class1160B class1160C class1160Allowed where
  card_le := by decide
  fresh := class1160FreshMaskSafe
  secants := class1160SecantCertificate
  carrier := class1160CarrierMaskSafe

theorem class1160ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1160A class1160B class1160C) class1160Allowed :=
  class1160RowCertificate.toReflectedMaskCertificate

theorem class1160LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1160A class1160B class1160C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1160A class1160B class1160C)
    class1160ReflectedMaskCertificate

def class1161A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1161B : OrbitCode := orbitCodeOfNumber ⟨122, by decide⟩
def class1161C : OrbitCode := orbitCodeOfNumber ⟨139, by decide⟩

def class1161Allowed : OrbitMask :=
  ![16717445405452795904, 21541946504, 5521519157981478912, 237011278514880514, 0]

def class1161LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 14, 19, 22, 7],
  ![250, 10, 0, 629, 327, 63, 568, 616],
  ![375, 15, 629, 0, 68, 452, 236, 188],
  ![475, 14, 327, 68, 0, 26, 409, 369],
  ![350, 19, 63, 452, 26, 0, 489, 299],
  ![325, 22, 568, 236, 409, 489, 0, 77],
  ![450, 7, 616, 188, 369, 299, 77, 0]
]

def class1161Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 14, GF25.ofNat 19],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 10, GF25.ofNat 10],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 15],
  ![GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 7, GF25.ofNat 6],
  ![GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 21, GF25.ofNat 22],
  ![GF25.ofNat 12, GF25.ofNat 16, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 23, GF25.ofNat 9, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 17, GF25.ofNat 11, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 24, GF25.ofNat 8, GF25.ofNat 10, GF25.ofNat 1]
]

def class1161SecantCertificate :
    SecantCompositionCertificate class1161A class1161B class1161C class1161Allowed where
  lineNumber := class1161LineNumber
  scale := class1161Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1161FreshMaskSafe :
    FreshMaskSafe class1161A class1161B class1161C class1161Allowed := by
  decide

theorem class1161CarrierMaskSafe :
    CarrierMaskSafe class1161A class1161B class1161C class1161Allowed := by
  decide

def class1161RowCertificate :
    RowCompositionCertificate class1161A class1161B class1161C class1161Allowed where
  card_le := by decide
  fresh := class1161FreshMaskSafe
  secants := class1161SecantCertificate
  carrier := class1161CarrierMaskSafe

theorem class1161ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1161A class1161B class1161C) class1161Allowed :=
  class1161RowCertificate.toReflectedMaskCertificate

theorem class1161LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1161A class1161B class1161C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1161A class1161B class1161C)
    class1161ReflectedMaskCertificate

def class1162A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1162B : OrbitCode := orbitCodeOfNumber ⟨122, by decide⟩
def class1162C : OrbitCode := orbitCodeOfNumber ⟨140, by decide⟩

def class1162Allowed : OrbitMask :=
  ![7782292749633454080, 52639040545, 324296584483307520, 167302239813189762, 0]

def class1162LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 14, 19, 20, 5],
  ![250, 10, 0, 629, 327, 63, 183, 279],
  ![375, 15, 629, 0, 68, 452, 404, 573],
  ![475, 14, 327, 68, 0, 26, 298, 310],
  ![350, 19, 63, 452, 26, 0, 440, 408],
  ![325, 20, 183, 404, 298, 440, 0, 52],
  ![450, 5, 279, 573, 310, 408, 52, 0]
]

def class1162Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 15, GF25.ofNat 10],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 17, GF25.ofNat 18],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 13, GF25.ofNat 12],
  ![GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 21, GF25.ofNat 1],
  ![GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 6],
  ![GF25.ofNat 12, GF25.ofNat 10, GF25.ofNat 13, GF25.ofNat 17, GF25.ofNat 9, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 17, GF25.ofNat 15, GF25.ofNat 12, GF25.ofNat 18, GF25.ofNat 4, GF25.ofNat 24, GF25.ofNat 10, GF25.ofNat 1]
]

def class1162SecantCertificate :
    SecantCompositionCertificate class1162A class1162B class1162C class1162Allowed where
  lineNumber := class1162LineNumber
  scale := class1162Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1162FreshMaskSafe :
    FreshMaskSafe class1162A class1162B class1162C class1162Allowed := by
  decide

theorem class1162CarrierMaskSafe :
    CarrierMaskSafe class1162A class1162B class1162C class1162Allowed := by
  decide

def class1162RowCertificate :
    RowCompositionCertificate class1162A class1162B class1162C class1162Allowed where
  card_le := by decide
  fresh := class1162FreshMaskSafe
  secants := class1162SecantCertificate
  carrier := class1162CarrierMaskSafe

theorem class1162ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1162A class1162B class1162C) class1162Allowed :=
  class1162RowCertificate.toReflectedMaskCertificate

theorem class1162LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1162A class1162B class1162C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1162A class1162B class1162C)
    class1162ReflectedMaskCertificate

def class1163A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1163B : OrbitCode := orbitCodeOfNumber ⟨122, by decide⟩
def class1163C : OrbitCode := orbitCodeOfNumber ⟨143, by decide⟩

def class1163Allowed : OrbitMask :=
  ![577307951782428672, 210370567, 873806307751100416, 220694525890347140, 0]

def class1163LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 14, 19, 17, 12],
  ![250, 10, 0, 629, 327, 63, 351, 111],
  ![375, 15, 629, 0, 68, 452, 116, 476],
  ![475, 14, 327, 68, 0, 26, 611, 298],
  ![350, 19, 63, 452, 26, 0, 408, 241],
  ![325, 17, 351, 116, 611, 408, 0, 626],
  ![450, 12, 111, 476, 298, 241, 626, 0]
]

def class1163Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 7, GF25.ofNat 8],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 23, GF25.ofNat 22],
  ![GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 12, GF25.ofNat 17],
  ![GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 12, GF25.ofNat 17],
  ![GF25.ofNat 12, GF25.ofNat 12, GF25.ofNat 23, GF25.ofNat 7, GF25.ofNat 18, GF25.ofNat 18, GF25.ofNat 1, GF25.ofNat 5],
  ![GF25.ofNat 17, GF25.ofNat 17, GF25.ofNat 22, GF25.ofNat 8, GF25.ofNat 13, GF25.ofNat 13, GF25.ofNat 20, GF25.ofNat 1]
]

def class1163SecantCertificate :
    SecantCompositionCertificate class1163A class1163B class1163C class1163Allowed where
  lineNumber := class1163LineNumber
  scale := class1163Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1163FreshMaskSafe :
    FreshMaskSafe class1163A class1163B class1163C class1163Allowed := by
  decide

theorem class1163CarrierMaskSafe :
    CarrierMaskSafe class1163A class1163B class1163C class1163Allowed := by
  decide

def class1163RowCertificate :
    RowCompositionCertificate class1163A class1163B class1163C class1163Allowed where
  card_le := by decide
  fresh := class1163FreshMaskSafe
  secants := class1163SecantCertificate
  carrier := class1163CarrierMaskSafe

theorem class1163ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1163A class1163B class1163C) class1163Allowed :=
  class1163RowCertificate.toReflectedMaskCertificate

theorem class1163LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1163A class1163B class1163C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1163A class1163B class1163C)
    class1163ReflectedMaskCertificate

def class1164A : OrbitCode := orbitCodeOfNumber ⟨5, by decide⟩
def class1164B : OrbitCode := orbitCodeOfNumber ⟨122, by decide⟩
def class1164C : OrbitCode := orbitCodeOfNumber ⟨146, by decide⟩

def class1164Allowed : OrbitMask :=
  ![12106529715179749376, 1233126410, 7277854823607697408, 222965571555229698, 0]

def class1164LineNumber : Fin 8 → Fin 8 → Fin 651 := ![
  ![0, 0, 250, 375, 475, 350, 325, 450],
  ![0, 0, 10, 15, 14, 19, 6, 21],
  ![250, 10, 0, 629, 327, 63, 395, 159],
  ![375, 15, 629, 0, 68, 452, 549, 255],
  ![475, 14, 327, 68, 0, 26, 503, 216],
  ![350, 19, 63, 452, 26, 0, 586, 128],
  ![325, 6, 395, 549, 503, 586, 0, 27],
  ![450, 21, 159, 255, 216, 128, 27, 0]
]

def class1164Scale : Fin 8 → Fin 8 → K25 := ![
  ![GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 23, GF25.ofNat 8, GF25.ofNat 18, GF25.ofNat 13],
  ![GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 22, GF25.ofNat 7, GF25.ofNat 21, GF25.ofNat 6],
  ![GF25.ofNat 5, GF25.ofNat 20, GF25.ofNat 1, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 24, GF25.ofNat 21],
  ![GF25.ofNat 20, GF25.ofNat 5, GF25.ofNat 15, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 6, GF25.ofNat 9],
  ![GF25.ofNat 7, GF25.ofNat 8, GF25.ofNat 4, GF25.ofNat 1, GF25.ofNat 1, GF25.ofNat 15, GF25.ofNat 10, GF25.ofNat 21],
  ![GF25.ofNat 22, GF25.ofNat 23, GF25.ofNat 1, GF25.ofNat 4, GF25.ofNat 10, GF25.ofNat 1, GF25.ofNat 6, GF25.ofNat 15],
  ![GF25.ofNat 12, GF25.ofNat 9, GF25.ofNat 6, GF25.ofNat 24, GF25.ofNat 15, GF25.ofNat 24, GF25.ofNat 1, GF25.ofNat 15],
  ![GF25.ofNat 17, GF25.ofNat 24, GF25.ofNat 9, GF25.ofNat 21, GF25.ofNat 9, GF25.ofNat 10, GF25.ofNat 10, GF25.ofNat 1]
]

def class1164SecantCertificate :
    SecantCompositionCertificate class1164A class1164B class1164C class1164Allowed where
  lineNumber := class1164LineNumber
  scale := class1164Scale
  witness := by decide
  symmetric := by decide
  avoids := by decide

theorem class1164FreshMaskSafe :
    FreshMaskSafe class1164A class1164B class1164C class1164Allowed := by
  decide

theorem class1164CarrierMaskSafe :
    CarrierMaskSafe class1164A class1164B class1164C class1164Allowed := by
  decide

def class1164RowCertificate :
    RowCompositionCertificate class1164A class1164B class1164C class1164Allowed where
  card_le := by decide
  fresh := class1164FreshMaskSafe
  secants := class1164SecantCertificate
  carrier := class1164CarrierMaskSafe

theorem class1164ReflectedMaskCertificate :
    ReflectedMaskCertificate (normalizedConfig class1164A class1164B class1164C) class1164Allowed :=
  class1164RowCertificate.toReflectedMaskCertificate

theorem class1164LegalOrbitSet_card_ge_32 :
    32 ≤ (legalOrbitSet (normalizedConfig class1164A class1164B class1164C)).card :=
  card_legalOrbitSet_ge_32
    (normalizedConfig_isConjInvariant class1164A class1164B class1164C)
    class1164ReflectedMaskCertificate

end Q25RowCompositionData
end RelativeConicArcs
