import RelativeConicArcs.SupportOrientationSymmetry

/-!
# Rational and integral commutants of the odd module

The odd six-dimensional action is described by signed monomial matrices from
left multiplication on the explicit `A₅/C₅` cover.  Golden equivariance is
checked on the sixty integral signed coset matrices and transported to the
rationals.  The only imported representation-theoretic input is isolated in a
proposition-valued interface: the conjugate `3+3'` splitting with Schur's
lemma and Galois descent bounds the rational commutant by `Q[B]`.

The reverse rational inclusion is proved algebraically from equivariance.  The
passage to the integral lattice is then entrywise: a diagonal entry detects the
coefficient of `I`, and one off-diagonal unit detects the coefficient of `B`.
-/

namespace RelativeConicArcs.SupportOrientationCommutant

open Matrix
open scoped Matrix
open SupportOrientationCover
open SupportOrientationPentagon

abbrev RationalOddOperator := Matrix (Fin 6) (Fin 6) ℚ
abbrev IntegralOddOperator := Matrix (Fin 6) (Fin 6) ℤ

/-- The integral golden operator viewed over the rationals. -/
def rationalGoldenOperator : RationalOddOperator :=
  fiberOddOrbitalMatrix.map (Int.castRingHom ℚ)

/-- Operators commuting with every matrix in a displayed rational `A₅`
action. -/
def rationalCommutant (rho : A5 → RationalOddOperator) : Set RationalOddOperator :=
  {T | ∀ g, T * rho g = rho g * T}

/-- The two-dimensional rational algebra generated by the golden operator. -/
def adjoinGoldenOperator : Set RationalOddOperator :=
  {T | ∃ a b : ℚ,
    T = a • (1 : RationalOddOperator) + b • rationalGoldenOperator}

/-- The oriented-coset incidence used by the fibre-odd action.  It holds when
left multiplication by `g` sends the chosen positive lift over axis `j` to the
lift of sign `b` over axis `i`, modulo the right action of `C₅`. -/
def OddCosetIncidence (g : A5) (i j : Fin 6) (b : Bool) : Prop :=
  ∃ r : Letter,
    g * rawAxisRepresentative j =
      supportRepresentative (i, b) * rotationA5 r

instance (g : A5) (i j : Fin 6) (b : Bool) :
    Decidable (OddCosetIncidence g i j b) := by
  unfold OddCosetIncidence
  infer_instance

/-- Integral signed monomial matrix in the raw cover gauge. -/
def rawIntegralOddA5ActionMatrix (g : A5) : IntegralOddOperator :=
  fun i j =>
    if OddCosetIncidence g i j false then 1
    else if OddCosetIncidence g i j true then -1
    else 0

/-- Integral signed monomial matrix in the conference gauge.  The axis
permutation and switching signs are the same transport that identifies the
raw orbital difference with the golden conference matrix. -/
def integralOddA5ActionMatrix (g : A5) : IntegralOddOperator :=
  fun i j =>
    let i' := coverAxisOrder.symm i
    let j' := coverAxisOrder.symm j
    coverAxisSign i' * rawIntegralOddA5ActionMatrix g i' j' *
      coverAxisSign j'

/-- Rational signed monomial matrix of left multiplication on the fibre-odd part of
the explicit `A₅/C₅ → A₅/D₅` cover. -/
def oddA5ActionMatrix (g : A5) : RationalOddOperator :=
  (integralOddA5ActionMatrix g).map (Int.castRingHom ℚ)

/-- The identity element acts by the identity matrix.  The finite reduction
checks the six chosen cosets and their two lift signs. -/
theorem oddA5ActionMatrix_one : oddA5ActionMatrix 1 = 1 := by
  decide +revert

set_option maxHeartbeats 10000000 in
set_option maxRecDepth 100000 in
/-- The integral golden orbital commutes with each of the sixty signed coset
matrices.  Kernel reduction checks the finite action-to-orbital
correspondence; it does not classify the commutant. -/
theorem integralGoldenOperator_commutes_oddA5Action (g : A5) :
    fiberOddOrbitalMatrix * integralOddA5ActionMatrix g =
      integralOddA5ActionMatrix g * fiberOddOrbitalMatrix := by
  revert g
  decide

/-- The rational golden orbital commutes with the displayed signed `A₅`
matrices. -/
theorem rationalGoldenOperator_commutes_oddA5Action :
    rationalGoldenOperator ∈ rationalCommutant oddA5ActionMatrix := by
  intro g
  simpa only [rationalGoldenOperator, oddA5ActionMatrix, Matrix.map_mul] using congrArg
    (fun M : IntegralOddOperator => M.map (Int.castRingHom ℚ))
    (integralGoldenOperator_commutes_oddA5Action g)

/-- Conditional interface for the classical representation-theoretic step.
The field is the upper-containment consequence of the nonisomorphic conjugate
`3+3'` splitting over `Q(sqrt 5)`, Schur's lemma on each summand, and Galois
descent.  It does not assume equality of the two commutants or equivariance of
the displayed golden operator. -/
structure ClassicalOddA5ThreePlusThreeSplitting : Prop where
  schur_galois_descent :
    rationalCommutant oddA5ActionMatrix ⊆ adjoinGoldenOperator

/-- The rational commutant is exactly the algebra generated by the golden operator, under
the classical `3+3'` decomposition interface taken as a hypothesis. -/
theorem oddModule_rationalCommutant_eq_adjoinGoldenOperator
    (classicalSplitting : ClassicalOddA5ThreePlusThreeSplitting) :
    rationalCommutant oddA5ActionMatrix = adjoinGoldenOperator := by
  apply Set.Subset.antisymm classicalSplitting.schur_galois_descent
  rintro T ⟨a, b, rfl⟩ g
  calc
    (a • (1 : RationalOddOperator) + b • rationalGoldenOperator) *
          oddA5ActionMatrix g =
        a • oddA5ActionMatrix g +
          b • (rationalGoldenOperator * oddA5ActionMatrix g) := by
            simp [add_mul]
    _ = a • oddA5ActionMatrix g +
          b • (oddA5ActionMatrix g * rationalGoldenOperator) := by
            rw [rationalGoldenOperator_commutes_oddA5Action g]
    _ = oddA5ActionMatrix g *
          (a • (1 : RationalOddOperator) + b • rationalGoldenOperator) := by
            simp [mul_add]

/-- A rational matrix preserves the displayed integral lattice exactly when
all of its entries are integers. -/
def PreservesOddLattice (T : RationalOddOperator) : Prop :=
  ∀ i j, ∃ z : ℤ, T i j = z

/-- The integral order `Z[sqrt 5]`, represented by `mI+nB`. -/
def ZsqrtFiveOperators : Set RationalOddOperator :=
  {T | ∃ m n : ℤ,
    T = (m : ℚ) • (1 : RationalOddOperator) +
      (n : ℚ) • rationalGoldenOperator}

/-- Diagonal/off-diagonal integrality test inside the rational algebra:
the integral points of `Q[B]` are exactly `Z[B] = Z[sqrt 5]`. -/
theorem adjoinGolden_integralPoints_eq_ZsqrtFive :
    {T | T ∈ adjoinGoldenOperator ∧ PreservesOddLattice T} =
      ZsqrtFiveOperators := by
  ext T
  constructor
  · rintro ⟨⟨a, b, rfl⟩, hint⟩
    obtain ⟨m, hm⟩ := hint 0 0
    obtain ⟨n, hn⟩ := hint 0 1
    have ha : a = m := by
      simpa [rationalGoldenOperator, fiberOddOrbitalMatrix,
        ClebschGoldenConference.conferenceMatrix]
        using hm
    have hb : b = n := by
      simpa [rationalGoldenOperator, fiberOddOrbitalMatrix,
        ClebschGoldenConference.conferenceMatrix]
        using hn
    exact ⟨m, n, by simp [ha, hb]⟩
  · rintro ⟨m, n, rfl⟩
    constructor
    · exact ⟨m, n, rfl⟩
    · intro i j
      refine ⟨m * (if i = j then 1 else 0) +
          n * fiberOddOrbitalMatrix i j, ?_⟩
      simp [rationalGoldenOperator, Matrix.one_apply]

/-- The integral commutant of the odd lattice is exactly
`Z[B] = Z[sqrt 5]`. -/
theorem oddLattice_integralCommutant_eq_ZsqrtFive
    (classicalSplitting : ClassicalOddA5ThreePlusThreeSplitting) :
    {T | T ∈ rationalCommutant oddA5ActionMatrix ∧ PreservesOddLattice T} =
      ZsqrtFiveOperators := by
  rw [oddModule_rationalCommutant_eq_adjoinGoldenOperator classicalSplitting]
  exact adjoinGolden_integralPoints_eq_ZsqrtFive

#print axioms oddModule_rationalCommutant_eq_adjoinGoldenOperator
#print axioms oddA5ActionMatrix_one
#print axioms integralGoldenOperator_commutes_oddA5Action
#print axioms rationalGoldenOperator_commutes_oddA5Action
#print axioms adjoinGolden_integralPoints_eq_ZsqrtFive
#print axioms oddLattice_integralCommutant_eq_ZsqrtFive

end RelativeConicArcs.SupportOrientationCommutant
