import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_037_C_238_287

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (37,238) through (37,249), aligned to R_037_C_238_287
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB037C238Payload : ValidRowPayload :=
  { c := ⟨238, by decide⟩, classIndex := ⟨728, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨108, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 42, orbitSize := 400 }

def residualTransportB037C238ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C238InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C238_transportValid :
    residualTransportB037C238Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C238ForwardIndex residualTransportB037C238InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C238Payload, residualTransportB037C238ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C238_payloadValidFor :
    (residualCoverRow037C238_287[0]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C238Payload] using
    residualTransportB037C238_transportValid

def residualTransportB037C240Payload : ValidRowPayload :=
  { c := ⟨240, by decide⟩, classIndex := ⟨1103, by decide⟩, canonicalB := ⟨121, by decide⟩, canonicalC := ⟨140, by decide⟩, y := GF25.ofNat 19, z := GF25.ofNat 10, legalCount := 40, orbitSize := 400 }

def residualTransportB037C240ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB037C240InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB037C240_transportValid :
    residualTransportB037C240Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C240ForwardIndex residualTransportB037C240InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C240Payload, residualTransportB037C240ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C240_payloadValidFor :
    (residualCoverRow037C238_287[2]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C240Payload] using
    residualTransportB037C240_transportValid

def residualTransportB037C241Payload : ValidRowPayload :=
  { c := ⟨241, by decide⟩, classIndex := ⟨1136, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨122, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 44, orbitSize := 400 }

def residualTransportB037C241ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C241InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C241_transportValid :
    residualTransportB037C241Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C241ForwardIndex residualTransportB037C241InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C241Payload, residualTransportB037C241ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C241_payloadValidFor :
    (residualCoverRow037C238_287[3]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C241Payload] using
    residualTransportB037C241_transportValid

def residualTransportB037C244Payload : ValidRowPayload :=
  { c := ⟨244, by decide⟩, classIndex := ⟨1083, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨121, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 39, orbitSize := 400 }

def residualTransportB037C244ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C244InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C244_transportValid :
    residualTransportB037C244Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C244ForwardIndex residualTransportB037C244InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C244Payload, residualTransportB037C244ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C244_payloadValidFor :
    (residualCoverRow037C238_287[6]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C244Payload] using
    residualTransportB037C244_transportValid

def residualTransportB037C246Payload : ValidRowPayload :=
  { c := ⟨246, by decide⟩, classIndex := ⟨902, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨112, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 35, orbitSize := 400 }

def residualTransportB037C246ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C246InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C246_transportValid :
    residualTransportB037C246Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C246ForwardIndex residualTransportB037C246InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C246Payload, residualTransportB037C246ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C246_payloadValidFor :
    (residualCoverRow037C238_287[8]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C246Payload] using
    residualTransportB037C246_transportValid

def residualTransportB037C247Payload : ValidRowPayload :=
  { c := ⟨247, by decide⟩, classIndex := ⟨790, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨110, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 41, orbitSize := 400 }

def residualTransportB037C247ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C247InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C247_transportValid :
    residualTransportB037C247Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C247ForwardIndex residualTransportB037C247InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C247Payload, residualTransportB037C247ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C247_payloadValidFor :
    (residualCoverRow037C238_287[9]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C247Payload] using
    residualTransportB037C247_transportValid

def residualTransportB037C248Payload : ValidRowPayload :=
  { c := ⟨248, by decide⟩, classIndex := ⟨962, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨113, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 38, orbitSize := 400 }

def residualTransportB037C248ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C248InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C248_transportValid :
    residualTransportB037C248Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C248ForwardIndex residualTransportB037C248InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C248Payload, residualTransportB037C248ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C248_payloadValidFor :
    (residualCoverRow037C238_287[10]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C248Payload] using
    residualTransportB037C248_transportValid

def residualTransportB037C249Payload : ValidRowPayload :=
  { c := ⟨249, by decide⟩, classIndex := ⟨846, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨111, by decide⟩, y := GF25.ofNat 10, z := GF25.ofNat 12, legalCount := 47, orbitSize := 400 }

def residualTransportB037C249ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 2, 3, 6, 7]
def residualTransportB037C249InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 3, 2, 6, 7]

theorem residualTransportB037C249_transportValid :
    residualTransportB037C249Payload.TransportValid ⟨37, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB037C249ForwardIndex residualTransportB037C249InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB037C249Payload, residualTransportB037C249ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB037C249_payloadValidFor :
    (residualCoverRow037C238_287[11]'(by decide)).ValidFor ⟨37, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow037C238_287, residualTransportB037C249Payload] using
    residualTransportB037C249_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
