import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_036_C_187_236

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 7 valid rows (36,221) through (36,234), aligned to R_036_C_187_236
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB036C221Payload : ValidRowPayload :=
  { c := ⟨221, by decide⟩, classIndex := ⟨584, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨90, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 21, legalCount := 42, orbitSize := 400 }

def residualTransportB036C221ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB036C221InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB036C221_transportValid :
    residualTransportB036C221Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C221ForwardIndex residualTransportB036C221InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C221Payload, residualTransportB036C221ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C221_payloadValidFor :
    (residualCoverRow036C187_236[34]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C221Payload] using
    residualTransportB036C221_transportValid

def residualTransportB036C223Payload : ValidRowPayload :=
  { c := ⟨223, by decide⟩, classIndex := ⟨645, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨72, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 42, orbitSize := 400 }

def residualTransportB036C223ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 5, 4, 7, 6]
def residualTransportB036C223InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 5, 4, 7, 6]

theorem residualTransportB036C223_transportValid :
    residualTransportB036C223Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C223ForwardIndex residualTransportB036C223InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C223Payload, residualTransportB036C223ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C223_payloadValidFor :
    (residualCoverRow036C187_236[36]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C223Payload] using
    residualTransportB036C223_transportValid

def residualTransportB036C224Payload : ValidRowPayload :=
  { c := ⟨224, by decide⟩, classIndex := ⟨572, by decide⟩, canonicalB := ⟨39, by decide⟩, canonicalC := ⟨71, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 42, orbitSize := 400 }

def residualTransportB036C224ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 5, 4, 7, 6]
def residualTransportB036C224InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 5, 4, 7, 6]

theorem residualTransportB036C224_transportValid :
    residualTransportB036C224Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C224ForwardIndex residualTransportB036C224InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C224Payload, residualTransportB036C224ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C224_payloadValidFor :
    (residualCoverRow036C187_236[37]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C224Payload] using
    residualTransportB036C224_transportValid

def residualTransportB036C231Payload : ValidRowPayload :=
  { c := ⟨231, by decide⟩, classIndex := ⟨813, by decide⟩, canonicalB := ⟨110, by decide⟩, canonicalC := ⟨146, by decide⟩, y := GF25.ofNat 19, z := GF25.ofNat 21, legalCount := 42, orbitSize := 400 }

def residualTransportB036C231ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB036C231InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB036C231_transportValid :
    residualTransportB036C231Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C231ForwardIndex residualTransportB036C231InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C231Payload, residualTransportB036C231ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C231_payloadValidFor :
    (residualCoverRow036C187_236[44]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C231Payload] using
    residualTransportB036C231_transportValid

def residualTransportB036C232Payload : ValidRowPayload :=
  { c := ⟨232, by decide⟩, classIndex := ⟨871, by decide⟩, canonicalB := ⟨111, by decide⟩, canonicalC := ⟨147, by decide⟩, y := GF25.ofNat 19, z := GF25.ofNat 22, legalCount := 38, orbitSize := 400 }

def residualTransportB036C232ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB036C232InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB036C232_transportValid :
    residualTransportB036C232Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C232ForwardIndex residualTransportB036C232InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C232Payload, residualTransportB036C232ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C232_payloadValidFor :
    (residualCoverRow036C187_236[45]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C232Payload] using
    residualTransportB036C232_transportValid

def residualTransportB036C233Payload : ValidRowPayload :=
  { c := ⟨233, by decide⟩, classIndex := ⟨931, by decide⟩, canonicalB := ⟨112, by decide⟩, canonicalC := ⟨148, by decide⟩, y := GF25.ofNat 19, z := GF25.ofNat 23, legalCount := 41, orbitSize := 400 }

def residualTransportB036C233ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB036C233InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB036C233_transportValid :
    residualTransportB036C233Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C233ForwardIndex residualTransportB036C233InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C233Payload, residualTransportB036C233ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C233_payloadValidFor :
    (residualCoverRow036C187_236[46]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C233Payload] using
    residualTransportB036C233_transportValid

def residualTransportB036C234Payload : ValidRowPayload :=
  { c := ⟨234, by decide⟩, classIndex := ⟨992, by decide⟩, canonicalB := ⟨113, by decide⟩, canonicalC := ⟨149, by decide⟩, y := GF25.ofNat 19, z := GF25.ofNat 24, legalCount := 42, orbitSize := 400 }

def residualTransportB036C234ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB036C234InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB036C234_transportValid :
    residualTransportB036C234Payload.TransportValid ⟨36, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB036C234ForwardIndex residualTransportB036C234InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB036C234Payload, residualTransportB036C234ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB036C234_payloadValidFor :
    (residualCoverRow036C187_236[47]'(by decide)).ValidFor ⟨36, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow036C187_236, residualTransportB036C234Payload] using
    residualTransportB036C234_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
