import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_041_C_042_091

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (41,58) through (41,67), aligned to R_041_C_042_091
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB041C058Payload : ValidRowPayload :=
  { c := ⟨58, by decide⟩, classIndex := ⟨73, by decide⟩, canonicalB := ⟨41, by decide⟩, canonicalC := ⟨58, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 38, orbitSize := 400 }

def residualTransportB041C058ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB041C058InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB041C058_transportValid :
    residualTransportB041C058Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C058ForwardIndex residualTransportB041C058InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C058Payload, residualTransportB041C058ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C058_payloadValidFor :
    (residualCoverRow041C042_091[16]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C058Payload] using
    residualTransportB041C058_transportValid

def residualTransportB041C059Payload : ValidRowPayload :=
  { c := ⟨59, by decide⟩, classIndex := ⟨120, by decide⟩, canonicalB := ⟨41, by decide⟩, canonicalC := ⟨59, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 40, orbitSize := 400 }

def residualTransportB041C059ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB041C059InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB041C059_transportValid :
    residualTransportB041C059Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C059ForwardIndex residualTransportB041C059InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C059Payload, residualTransportB041C059ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C059_payloadValidFor :
    (residualCoverRow041C042_091[17]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C059Payload] using
    residualTransportB041C059_transportValid

def residualTransportB041C060Payload : ValidRowPayload :=
  { c := ⟨60, by decide⟩, classIndex := ⟨180, by decide⟩, canonicalB := ⟨41, by decide⟩, canonicalC := ⟨60, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 38, orbitSize := 400 }

def residualTransportB041C060ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB041C060InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB041C060_transportValid :
    residualTransportB041C060Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C060ForwardIndex residualTransportB041C060InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C060Payload, residualTransportB041C060ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C060_payloadValidFor :
    (residualCoverRow041C042_091[18]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C060Payload] using
    residualTransportB041C060_transportValid

def residualTransportB041C062Payload : ValidRowPayload :=
  { c := ⟨62, by decide⟩, classIndex := ⟨346, by decide⟩, canonicalB := ⟨41, by decide⟩, canonicalC := ⟨62, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 37, orbitSize := 400 }

def residualTransportB041C062ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB041C062InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB041C062_transportValid :
    residualTransportB041C062Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C062ForwardIndex residualTransportB041C062InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C062Payload, residualTransportB041C062ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C062_payloadValidFor :
    (residualCoverRow041C042_091[20]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C062Payload] using
    residualTransportB041C062_transportValid

def residualTransportB041C063Payload : ValidRowPayload :=
  { c := ⟨63, by decide⟩, classIndex := ⟨424, by decide⟩, canonicalB := ⟨41, by decide⟩, canonicalC := ⟨63, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 38, orbitSize := 400 }

def residualTransportB041C063ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB041C063InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB041C063_transportValid :
    residualTransportB041C063Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C063ForwardIndex residualTransportB041C063InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C063Payload, residualTransportB041C063ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C063_payloadValidFor :
    (residualCoverRow041C042_091[21]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C063Payload] using
    residualTransportB041C063_transportValid

def residualTransportB041C064Payload : ValidRowPayload :=
  { c := ⟨64, by decide⟩, classIndex := ⟨499, by decide⟩, canonicalB := ⟨41, by decide⟩, canonicalC := ⟨64, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 40, orbitSize := 400 }

def residualTransportB041C064ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB041C064InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB041C064_transportValid :
    residualTransportB041C064Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C064ForwardIndex residualTransportB041C064InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C064Payload, residualTransportB041C064ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C064_payloadValidFor :
    (residualCoverRow041C042_091[22]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C064Payload] using
    residualTransportB041C064_transportValid

def residualTransportB041C065Payload : ValidRowPayload :=
  { c := ⟨65, by decide⟩, classIndex := ⟨188, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨83, by decide⟩, y := GF25.ofNat 21, z := GF25.ofNat 10, legalCount := 34, orbitSize := 400 }

def residualTransportB041C065ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 7, 6, 3, 2]
def residualTransportB041C065InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 3, 2, 5, 4]

theorem residualTransportB041C065_transportValid :
    residualTransportB041C065Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C065ForwardIndex residualTransportB041C065InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C065Payload, residualTransportB041C065ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C065_payloadValidFor :
    (residualCoverRow041C042_091[23]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C065Payload] using
    residualTransportB041C065_transportValid

def residualTransportB041C067Payload : ValidRowPayload :=
  { c := ⟨67, by decide⟩, classIndex := ⟨505, by decide⟩, canonicalB := ⟨64, by decide⟩, canonicalC := ⟨82, by decide⟩, y := GF25.ofNat 21, z := GF25.ofNat 12, legalCount := 40, orbitSize := 400 }

def residualTransportB041C067ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 7, 6, 3, 2]
def residualTransportB041C067InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 3, 2, 5, 4]

theorem residualTransportB041C067_transportValid :
    residualTransportB041C067Payload.TransportValid ⟨41, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB041C067ForwardIndex residualTransportB041C067InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB041C067Payload, residualTransportB041C067ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB041C067_payloadValidFor :
    (residualCoverRow041C042_091[25]'(by decide)).ValidFor ⟨41, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow041C042_091, residualTransportB041C067Payload] using
    residualTransportB041C067_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
