import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_060_C_211_260

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 7 valid rows (60,238) through (60,249), aligned to R_060_C_211_260
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB060C238Payload : ValidRowPayload :=
  { c := ⟨238, by decide⟩, classIndex := ⟨225, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨238, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 37, orbitSize := 400 }

def residualTransportB060C238ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C238InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C238_transportValid :
    residualTransportB060C238Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C238ForwardIndex residualTransportB060C238InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C238Payload, residualTransportB060C238ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C238_payloadValidFor :
    (residualCoverRow060C211_260[27]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C238Payload] using
    residualTransportB060C238_transportValid

def residualTransportB060C241Payload : ValidRowPayload :=
  { c := ⟨241, by decide⟩, classIndex := ⟨226, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨241, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 44, orbitSize := 400 }

def residualTransportB060C241ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C241InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C241_transportValid :
    residualTransportB060C241Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C241ForwardIndex residualTransportB060C241InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C241Payload, residualTransportB060C241ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C241_payloadValidFor :
    (residualCoverRow060C211_260[30]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C241Payload] using
    residualTransportB060C241_transportValid

def residualTransportB060C243Payload : ValidRowPayload :=
  { c := ⟨243, by decide⟩, classIndex := ⟨227, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨243, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 37, orbitSize := 400 }

def residualTransportB060C243ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C243InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C243_transportValid :
    residualTransportB060C243Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C243ForwardIndex residualTransportB060C243InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C243Payload, residualTransportB060C243ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C243_payloadValidFor :
    (residualCoverRow060C211_260[32]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C243Payload] using
    residualTransportB060C243_transportValid

def residualTransportB060C244Payload : ValidRowPayload :=
  { c := ⟨244, by decide⟩, classIndex := ⟨228, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨244, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 38, orbitSize := 400 }

def residualTransportB060C244ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C244InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C244_transportValid :
    residualTransportB060C244Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C244ForwardIndex residualTransportB060C244InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C244Payload, residualTransportB060C244ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C244_payloadValidFor :
    (residualCoverRow060C211_260[33]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C244Payload] using
    residualTransportB060C244_transportValid

def residualTransportB060C247Payload : ValidRowPayload :=
  { c := ⟨247, by decide⟩, classIndex := ⟨229, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨247, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 41, orbitSize := 400 }

def residualTransportB060C247ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C247InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C247_transportValid :
    residualTransportB060C247Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C247ForwardIndex residualTransportB060C247InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C247Payload, residualTransportB060C247ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C247_payloadValidFor :
    (residualCoverRow060C211_260[36]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C247Payload] using
    residualTransportB060C247_transportValid

def residualTransportB060C248Payload : ValidRowPayload :=
  { c := ⟨248, by decide⟩, classIndex := ⟨230, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨248, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 41, orbitSize := 400 }

def residualTransportB060C248ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C248InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C248_transportValid :
    residualTransportB060C248Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C248ForwardIndex residualTransportB060C248InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C248Payload, residualTransportB060C248ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C248_payloadValidFor :
    (residualCoverRow060C211_260[37]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C248Payload] using
    residualTransportB060C248_transportValid

def residualTransportB060C249Payload : ValidRowPayload :=
  { c := ⟨249, by decide⟩, classIndex := ⟨231, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨249, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 43, orbitSize := 400 }

def residualTransportB060C249ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB060C249InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB060C249_transportValid :
    residualTransportB060C249Payload.TransportValid ⟨60, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB060C249ForwardIndex residualTransportB060C249InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB060C249Payload, residualTransportB060C249ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB060C249_payloadValidFor :
    (residualCoverRow060C211_260[38]'(by decide)).ValidFor ⟨60, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow060C211_260, residualTransportB060C249Payload] using
    residualTransportB060C249_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
