import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_071_C_122_171

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (71,122) through (71,142), aligned to R_071_C_122_171
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB071C122Payload : ValidRowPayload :=
  { c := ⟨122, by decide⟩, classIndex := ⟨106, by decide⟩, canonicalB := ⟨59, by decide⟩, canonicalC := ⟨123, by decide⟩, y := GF25.ofNat 22, z := GF25.ofNat 7, legalCount := 37, orbitSize := 400 }

def residualTransportB071C122ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 3, 2]
def residualTransportB071C122InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 3, 2]

theorem residualTransportB071C122_transportValid :
    residualTransportB071C122Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C122ForwardIndex residualTransportB071C122InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C122Payload, residualTransportB071C122ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C122_payloadValidFor :
    (residualCoverRow071C122_171[0]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C122Payload] using
    residualTransportB071C122_transportValid

def residualTransportB071C123Payload : ValidRowPayload :=
  { c := ⟨123, by decide⟩, classIndex := ⟨57, by decide⟩, canonicalB := ⟨58, by decide⟩, canonicalC := ⟨122, by decide⟩, y := GF25.ofNat 22, z := GF25.ofNat 8, legalCount := 43, orbitSize := 400 }

def residualTransportB071C123ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 3, 2]
def residualTransportB071C123InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 3, 2]

theorem residualTransportB071C123_transportValid :
    residualTransportB071C123Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C123ForwardIndex residualTransportB071C123InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C123Payload, residualTransportB071C123ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C123_payloadValidFor :
    (residualCoverRow071C122_171[1]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C123Payload] using
    residualTransportB071C123_transportValid

def residualTransportB071C133Payload : ValidRowPayload :=
  { c := ⟨133, by decide⟩, classIndex := ⟨590, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨133, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 42, orbitSize := 400 }

def residualTransportB071C133ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB071C133InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB071C133_transportValid :
    residualTransportB071C133Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C133ForwardIndex residualTransportB071C133InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C133Payload, residualTransportB071C133ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C133_payloadValidFor :
    (residualCoverRow071C122_171[11]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C133Payload] using
    residualTransportB071C133_transportValid

def residualTransportB071C136Payload : ValidRowPayload :=
  { c := ⟨136, by decide⟩, classIndex := ⟨591, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨136, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 37, orbitSize := 400 }

def residualTransportB071C136ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB071C136InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB071C136_transportValid :
    residualTransportB071C136Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C136ForwardIndex residualTransportB071C136InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C136Payload, residualTransportB071C136ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C136_payloadValidFor :
    (residualCoverRow071C122_171[14]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C136Payload] using
    residualTransportB071C136_transportValid

def residualTransportB071C138Payload : ValidRowPayload :=
  { c := ⟨138, by decide⟩, classIndex := ⟨592, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨138, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 43, orbitSize := 400 }

def residualTransportB071C138ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB071C138InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB071C138_transportValid :
    residualTransportB071C138Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C138ForwardIndex residualTransportB071C138InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C138Payload, residualTransportB071C138ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C138_payloadValidFor :
    (residualCoverRow071C122_171[16]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C138Payload] using
    residualTransportB071C138_transportValid

def residualTransportB071C139Payload : ValidRowPayload :=
  { c := ⟨139, by decide⟩, classIndex := ⟨593, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨139, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 41, orbitSize := 400 }

def residualTransportB071C139ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB071C139InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB071C139_transportValid :
    residualTransportB071C139Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C139ForwardIndex residualTransportB071C139InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C139Payload, residualTransportB071C139ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C139_payloadValidFor :
    (residualCoverRow071C122_171[17]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C139Payload] using
    residualTransportB071C139_transportValid

def residualTransportB071C141Payload : ValidRowPayload :=
  { c := ⟨141, by decide⟩, classIndex := ⟨594, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨141, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 46, orbitSize := 400 }

def residualTransportB071C141ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB071C141InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB071C141_transportValid :
    residualTransportB071C141Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C141ForwardIndex residualTransportB071C141InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C141Payload, residualTransportB071C141ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C141_payloadValidFor :
    (residualCoverRow071C122_171[19]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C141Payload] using
    residualTransportB071C141_transportValid

def residualTransportB071C142Payload : ValidRowPayload :=
  { c := ⟨142, by decide⟩, classIndex := ⟨595, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨142, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 42, orbitSize := 400 }

def residualTransportB071C142ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB071C142InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB071C142_transportValid :
    residualTransportB071C142Payload.TransportValid ⟨71, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB071C142ForwardIndex residualTransportB071C142InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB071C142Payload, residualTransportB071C142ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB071C142_payloadValidFor :
    (residualCoverRow071C122_171[20]'(by decide)).ValidFor ⟨71, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow071C122_171, residualTransportB071C142Payload] using
    residualTransportB071C142_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
