import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_092_C_193_242

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (92,193) through (92,210), aligned to R_092_C_193_242
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB092C193Payload : ValidRowPayload :=
  { c := ⟨193, by decide⟩, classIndex := ⟨34, by decide⟩, canonicalB := ⟨57, by decide⟩, canonicalC := ⟨141, by decide⟩, y := GF25.ofNat 11, z := GF25.ofNat 17, legalCount := 41, orbitSize := 400 }

def residualTransportB092C193ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 2, 3, 4, 5]
def residualTransportB092C193InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 3, 2]

theorem residualTransportB092C193_transportValid :
    residualTransportB092C193Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C193ForwardIndex residualTransportB092C193InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C193Payload, residualTransportB092C193ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C193_payloadValidFor :
    (residualCoverRow092C193_242[0]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C193Payload] using
    residualTransportB092C193_transportValid

def residualTransportB092C194Payload : ValidRowPayload :=
  { c := ⟨194, by decide⟩, classIndex := ⟨130, by decide⟩, canonicalB := ⟨59, by decide⟩, canonicalC := ⟨141, by decide⟩, y := GF25.ofNat 11, z := GF25.ofNat 17, legalCount := 43, orbitSize := 400 }

def residualTransportB092C194ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 2, 3, 4, 5]
def residualTransportB092C194InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 3, 2]

theorem residualTransportB092C194_transportValid :
    residualTransportB092C194Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C194ForwardIndex residualTransportB092C194InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C194Payload, residualTransportB092C194ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C194_payloadValidFor :
    (residualCoverRow092C193_242[1]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C194Payload] using
    residualTransportB092C194_transportValid

def residualTransportB092C197Payload : ValidRowPayload :=
  { c := ⟨197, by decide⟩, classIndex := ⟨221, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨233, by decide⟩, y := GF25.ofNat 18, z := GF25.ofNat 7, legalCount := 40, orbitSize := 400 }

def residualTransportB092C197ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB092C197InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB092C197_transportValid :
    residualTransportB092C197Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C197ForwardIndex residualTransportB092C197InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C197Payload, residualTransportB092C197ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C197_payloadValidFor :
    (residualCoverRow092C193_242[4]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C197Payload] using
    residualTransportB092C197_transportValid

def residualTransportB092C198Payload : ValidRowPayload :=
  { c := ⟨198, by decide⟩, classIndex := ⟨540, by decide⟩, canonicalB := ⟨64, by decide⟩, canonicalC := ⟨232, by decide⟩, y := GF25.ofNat 18, z := GF25.ofNat 8, legalCount := 42, orbitSize := 400 }

def residualTransportB092C198ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB092C198InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB092C198_transportValid :
    residualTransportB092C198Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C198ForwardIndex residualTransportB092C198InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C198Payload, residualTransportB092C198ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C198_payloadValidFor :
    (residualCoverRow092C193_242[5]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C198Payload] using
    residualTransportB092C198_transportValid

def residualTransportB092C199Payload : ValidRowPayload :=
  { c := ⟨199, by decide⟩, classIndex := ⟨464, by decide⟩, canonicalB := ⟨63, by decide⟩, canonicalC := ⟨231, by decide⟩, y := GF25.ofNat 18, z := GF25.ofNat 9, legalCount := 42, orbitSize := 400 }

def residualTransportB092C199ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 5, 4, 3, 2]
def residualTransportB092C199InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 2, 3]

theorem residualTransportB092C199_transportValid :
    residualTransportB092C199Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C199ForwardIndex residualTransportB092C199InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C199Payload, residualTransportB092C199ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C199_payloadValidFor :
    (residualCoverRow092C193_242[6]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C199Payload] using
    residualTransportB092C199_transportValid

def residualTransportB092C206Payload : ValidRowPayload :=
  { c := ⟨206, by decide⟩, classIndex := ⟨130, by decide⟩, canonicalB := ⟨59, by decide⟩, canonicalC := ⟨141, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 6, legalCount := 43, orbitSize := 400 }

def residualTransportB092C206ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB092C206InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB092C206_transportValid :
    residualTransportB092C206Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C206ForwardIndex residualTransportB092C206InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C206Payload, residualTransportB092C206ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C206_payloadValidFor :
    (residualCoverRow092C193_242[13]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C206Payload] using
    residualTransportB092C206_transportValid

def residualTransportB092C207Payload : ValidRowPayload :=
  { c := ⟨207, by decide⟩, classIndex := ⟨84, by decide⟩, canonicalB := ⟨58, by decide⟩, canonicalC := ⟨140, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 7, legalCount := 42, orbitSize := 400 }

def residualTransportB092C207ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB092C207InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB092C207_transportValid :
    residualTransportB092C207Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C207ForwardIndex residualTransportB092C207InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C207Payload, residualTransportB092C207ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C207_payloadValidFor :
    (residualCoverRow092C193_242[14]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C207Payload] using
    residualTransportB092C207_transportValid

def residualTransportB092C210Payload : ValidRowPayload :=
  { c := ⟨210, by decide⟩, classIndex := ⟨227, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨243, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 37, orbitSize := 400 }

def residualTransportB092C210ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB092C210InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB092C210_transportValid :
    residualTransportB092C210Payload.TransportValid ⟨92, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB092C210ForwardIndex residualTransportB092C210InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB092C210Payload, residualTransportB092C210ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB092C210_payloadValidFor :
    (residualCoverRow092C193_242[17]'(by decide)).ValidFor ⟨92, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow092C193_242, residualTransportB092C210Payload] using
    residualTransportB092C210_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
