import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_098_C_149_198

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (98,149) through (98,166), aligned to R_098_C_149_198
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB098C149Payload : ValidRowPayload :=
  { c := ⟨149, by decide⟩, classIndex := ⟨713, by decide⟩, canonicalB := ⟨106, by decide⟩, canonicalC := ⟨182, by decide⟩, y := GF25.ofNat 16, z := GF25.ofNat 8, legalCount := 43, orbitSize := 400 }

def residualTransportB098C149ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 3, 2, 5, 4]
def residualTransportB098C149InverseIndex : Fin 8 → Fin 8 := ![0, 1, 5, 4, 7, 6, 2, 3]

theorem residualTransportB098C149_transportValid :
    residualTransportB098C149Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C149ForwardIndex residualTransportB098C149InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C149Payload, residualTransportB098C149ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C149_payloadValidFor :
    (residualCoverRow098C149_198[0]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C149Payload] using
    residualTransportB098C149_transportValid

def residualTransportB098C156Payload : ValidRowPayload :=
  { c := ⟨156, by decide⟩, classIndex := ⟨782, by decide⟩, canonicalB := ⟨109, by decide⟩, canonicalC := ⟨197, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 6, legalCount := 38, orbitSize := 400 }

def residualTransportB098C156ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB098C156InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB098C156_transportValid :
    residualTransportB098C156Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C156ForwardIndex residualTransportB098C156InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C156Payload, residualTransportB098C156ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C156_payloadValidFor :
    (residualCoverRow098C149_198[7]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C156Payload] using
    residualTransportB098C156_transportValid

def residualTransportB098C157Payload : ValidRowPayload :=
  { c := ⟨157, by decide⟩, classIndex := ⟨751, by decide⟩, canonicalB := ⟨108, by decide⟩, canonicalC := ⟨196, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 7, legalCount := 40, orbitSize := 400 }

def residualTransportB098C157ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB098C157InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB098C157_transportValid :
    residualTransportB098C157Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C157ForwardIndex residualTransportB098C157InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C157Payload, residualTransportB098C157ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C157_payloadValidFor :
    (residualCoverRow098C149_198[8]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C157Payload] using
    residualTransportB098C157_transportValid

def residualTransportB098C160Payload : ValidRowPayload :=
  { c := ⟨160, by decide⟩, classIndex := ⟨839, by decide⟩, canonicalB := ⟨110, by decide⟩, canonicalC := ⟨247, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 44, orbitSize := 400 }

def residualTransportB098C160ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB098C160InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB098C160_transportValid :
    residualTransportB098C160Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C160ForwardIndex residualTransportB098C160InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C160Payload, residualTransportB098C160ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C160_payloadValidFor :
    (residualCoverRow098C149_198[11]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C160Payload] using
    residualTransportB098C160_transportValid

def residualTransportB098C163Payload : ValidRowPayload :=
  { c := ⟨163, by decide⟩, classIndex := ⟨954, by decide⟩, canonicalB := ⟨112, by decide⟩, canonicalC := ⟨247, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 38, orbitSize := 400 }

def residualTransportB098C163ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB098C163InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB098C163_transportValid :
    residualTransportB098C163Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C163ForwardIndex residualTransportB098C163InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C163Payload, residualTransportB098C163ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C163_payloadValidFor :
    (residualCoverRow098C149_198[14]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C163Payload] using
    residualTransportB098C163_transportValid

def residualTransportB098C164Payload : ValidRowPayload :=
  { c := ⟨164, by decide⟩, classIndex := ⟨894, by decide⟩, canonicalB := ⟨111, by decide⟩, canonicalC := ⟨247, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 38, orbitSize := 400 }

def residualTransportB098C164ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB098C164InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB098C164_transportValid :
    residualTransportB098C164Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C164ForwardIndex residualTransportB098C164InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C164Payload, residualTransportB098C164ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C164_payloadValidFor :
    (residualCoverRow098C149_198[15]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C164Payload] using
    residualTransportB098C164_transportValid

def residualTransportB098C165Payload : ValidRowPayload :=
  { c := ⟨165, by decide⟩, classIndex := ⟨823, by decide⟩, canonicalB := ⟨110, by decide⟩, canonicalC := ⟨191, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 15, legalCount := 39, orbitSize := 400 }

def residualTransportB098C165ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB098C165InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB098C165_transportValid :
    residualTransportB098C165Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C165ForwardIndex residualTransportB098C165InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C165Payload, residualTransportB098C165ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C165_payloadValidFor :
    (residualCoverRow098C149_198[16]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C165Payload] using
    residualTransportB098C165_transportValid

def residualTransportB098C166Payload : ValidRowPayload :=
  { c := ⟨166, by decide⟩, classIndex := ⟨1002, by decide⟩, canonicalB := ⟨113, by decide⟩, canonicalC := ⟨194, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 16, legalCount := 32, orbitSize := 400 }

def residualTransportB098C166ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB098C166InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB098C166_transportValid :
    residualTransportB098C166Payload.TransportValid ⟨98, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB098C166ForwardIndex residualTransportB098C166InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB098C166Payload, residualTransportB098C166ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB098C166_payloadValidFor :
    (residualCoverRow098C149_198[17]'(by decide)).ValidFor ⟨98, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow098C149_198, residualTransportB098C166Payload] using
    residualTransportB098C166_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
