import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_118_C_169_218

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (118,206) through (118,216), aligned to R_118_C_169_218
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB118C206Payload : ValidRowPayload :=
  { c := ⟨206, by decide⟩, classIndex := ⟨110, by decide⟩, canonicalB := ⟨59, by decide⟩, canonicalC := ⟨167, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 6, legalCount := 41, orbitSize := 200 }

def residualTransportB118C206ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB118C206InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB118C206_transportValid :
    residualTransportB118C206Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C206ForwardIndex residualTransportB118C206InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C206Payload, residualTransportB118C206ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C206_payloadValidFor :
    (residualCoverRow118C169_218[37]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C206Payload] using
    residualTransportB118C206_transportValid

def residualTransportB118C207Payload : ValidRowPayload :=
  { c := ⟨207, by decide⟩, classIndex := ⟨64, by decide⟩, canonicalB := ⟨58, by decide⟩, canonicalC := ⟨166, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 7, legalCount := 38, orbitSize := 400 }

def residualTransportB118C207ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB118C207InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB118C207_transportValid :
    residualTransportB118C207Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C207ForwardIndex residualTransportB118C207InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C207Payload, residualTransportB118C207ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C207_payloadValidFor :
    (residualCoverRow118C169_218[38]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C207Payload] using
    residualTransportB118C207_transportValid

def residualTransportB118C208Payload : ValidRowPayload :=
  { c := ⟨208, by decide⟩, classIndex := ⟨14, by decide⟩, canonicalB := ⟨57, by decide⟩, canonicalC := ⟨165, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 8, legalCount := 41, orbitSize := 400 }

def residualTransportB118C208ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB118C208InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB118C208_transportValid :
    residualTransportB118C208Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C208ForwardIndex residualTransportB118C208InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C208Payload, residualTransportB118C208ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C208_payloadValidFor :
    (residualCoverRow118C169_218[39]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C208Payload] using
    residualTransportB118C208_transportValid

def residualTransportB118C210Payload : ValidRowPayload :=
  { c := ⟨210, by decide⟩, classIndex := ⟨160, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨167, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 38, orbitSize := 400 }

def residualTransportB118C210ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB118C210InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB118C210_transportValid :
    residualTransportB118C210Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C210ForwardIndex residualTransportB118C210InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C210Payload, residualTransportB118C210ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C210_payloadValidFor :
    (residualCoverRow118C169_218[41]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C210Payload] using
    residualTransportB118C210_transportValid

def residualTransportB118C211Payload : ValidRowPayload :=
  { c := ⟨211, by decide⟩, classIndex := ⟨484, by decide⟩, canonicalB := ⟨64, by decide⟩, canonicalC := ⟨167, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 44, orbitSize := 400 }

def residualTransportB118C211ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB118C211InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB118C211_transportValid :
    residualTransportB118C211Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C211ForwardIndex residualTransportB118C211InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C211Payload, residualTransportB118C211ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C211_payloadValidFor :
    (residualCoverRow118C169_218[42]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C211Payload] using
    residualTransportB118C211_transportValid

def residualTransportB118C212Payload : ValidRowPayload :=
  { c := ⟨212, by decide⟩, classIndex := ⟨407, by decide⟩, canonicalB := ⟨63, by decide⟩, canonicalC := ⟨167, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 40, orbitSize := 400 }

def residualTransportB118C212ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB118C212InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB118C212_transportValid :
    residualTransportB118C212Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C212ForwardIndex residualTransportB118C212InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C212Payload, residualTransportB118C212ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C212_payloadValidFor :
    (residualCoverRow118C169_218[43]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C212Payload] using
    residualTransportB118C212_transportValid

def residualTransportB118C214Payload : ValidRowPayload :=
  { c := ⟨214, by decide⟩, classIndex := ⟨244, by decide⟩, canonicalB := ⟨61, by decide⟩, canonicalC := ⟨167, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 40, orbitSize := 400 }

def residualTransportB118C214ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB118C214InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB118C214_transportValid :
    residualTransportB118C214Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C214ForwardIndex residualTransportB118C214InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C214Payload, residualTransportB118C214ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C214_payloadValidFor :
    (residualCoverRow118C169_218[45]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C214Payload] using
    residualTransportB118C214_transportValid

def residualTransportB118C216Payload : ValidRowPayload :=
  { c := ⟨216, by decide⟩, classIndex := ⟨402, by decide⟩, canonicalB := ⟨63, by decide⟩, canonicalC := ⟨159, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 16, legalCount := 38, orbitSize := 400 }

def residualTransportB118C216ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB118C216InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB118C216_transportValid :
    residualTransportB118C216Payload.TransportValid ⟨118, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB118C216ForwardIndex residualTransportB118C216InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB118C216Payload, residualTransportB118C216ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB118C216_payloadValidFor :
    (residualCoverRow118C169_218[47]'(by decide)).ValidFor ⟨118, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow118C169_218, residualTransportB118C216Payload] using
    residualTransportB118C216_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
