import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_114_C_215_264

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (114,215) through (114,233), aligned to R_114_C_215_264
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB114C215Payload : ValidRowPayload :=
  { c := ⟨215, by decide⟩, classIndex := ⟨163, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨173, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 15, legalCount := 38, orbitSize := 400 }

def residualTransportB114C215ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB114C215InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB114C215_transportValid :
    residualTransportB114C215Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C215ForwardIndex residualTransportB114C215InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C215Payload, residualTransportB114C215ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C215_payloadValidFor :
    (residualCoverRow114C215_264[0]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C215Payload] using
    residualTransportB114C215_transportValid

def residualTransportB114C217Payload : ValidRowPayload :=
  { c := ⟨217, by decide⟩, classIndex := ⟨248, by decide⟩, canonicalB := ⟨61, by decide⟩, canonicalC := ⟨174, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 17, legalCount := 40, orbitSize := 400 }

def residualTransportB114C217ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB114C217InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB114C217_transportValid :
    residualTransportB114C217Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C217ForwardIndex residualTransportB114C217InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C217Payload, residualTransportB114C217ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C217_payloadValidFor :
    (residualCoverRow114C215_264[2]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C217Payload] using
    residualTransportB114C217_transportValid

def residualTransportB114C221Payload : ValidRowPayload :=
  { c := ⟨221, by decide⟩, classIndex := ⟨562, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨167, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 21, legalCount := 41, orbitSize := 400 }

def residualTransportB114C221ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB114C221InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB114C221_transportValid :
    residualTransportB114C221Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C221ForwardIndex residualTransportB114C221InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C221Payload, residualTransportB114C221ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C221_payloadValidFor :
    (residualCoverRow114C215_264[6]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C221Payload] using
    residualTransportB114C221_transportValid

def residualTransportB114C222Payload : ValidRowPayload :=
  { c := ⟨222, by decide⟩, classIndex := ⟨634, by decide⟩, canonicalB := ⟨72, by decide⟩, canonicalC := ⟨168, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 22, legalCount := 41, orbitSize := 400 }

def residualTransportB114C222ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB114C222InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB114C222_transportValid :
    residualTransportB114C222Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C222ForwardIndex residualTransportB114C222InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C222Payload, residualTransportB114C222ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C222_payloadValidFor :
    (residualCoverRow114C215_264[7]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C222Payload] using
    residualTransportB114C222_transportValid

def residualTransportB114C223Payload : ValidRowPayload :=
  { c := ⟨223, by decide⟩, classIndex := ⟨628, by decide⟩, canonicalB := ⟨72, by decide⟩, canonicalC := ⟨161, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 43, orbitSize := 400 }

def residualTransportB114C223ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB114C223InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB114C223_transportValid :
    residualTransportB114C223Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C223ForwardIndex residualTransportB114C223InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C223Payload, residualTransportB114C223ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C223_payloadValidFor :
    (residualCoverRow114C215_264[8]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C223Payload] using
    residualTransportB114C223_transportValid

def residualTransportB114C231Payload : ValidRowPayload :=
  { c := ⟨231, by decide⟩, classIndex := ⟨1064, by decide⟩, canonicalB := ⟨114, by decide⟩, canonicalC := ⟨231, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 42, orbitSize := 400 }

def residualTransportB114C231ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB114C231InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB114C231_transportValid :
    residualTransportB114C231Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C231ForwardIndex residualTransportB114C231InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C231Payload, residualTransportB114C231ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C231_payloadValidFor :
    (residualCoverRow114C215_264[16]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C231Payload] using
    residualTransportB114C231_transportValid

def residualTransportB114C232Payload : ValidRowPayload :=
  { c := ⟨232, by decide⟩, classIndex := ⟨1065, by decide⟩, canonicalB := ⟨114, by decide⟩, canonicalC := ⟨232, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 41, orbitSize := 400 }

def residualTransportB114C232ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB114C232InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB114C232_transportValid :
    residualTransportB114C232Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C232ForwardIndex residualTransportB114C232InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C232Payload, residualTransportB114C232ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C232_payloadValidFor :
    (residualCoverRow114C215_264[17]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C232Payload] using
    residualTransportB114C232_transportValid

def residualTransportB114C233Payload : ValidRowPayload :=
  { c := ⟨233, by decide⟩, classIndex := ⟨1066, by decide⟩, canonicalB := ⟨114, by decide⟩, canonicalC := ⟨233, by decide⟩, y := GF25.ofNat 5, z := GF25.ofNat 5, legalCount := 40, orbitSize := 400 }

def residualTransportB114C233ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
def residualTransportB114C233InverseIndex : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]

theorem residualTransportB114C233_transportValid :
    residualTransportB114C233Payload.TransportValid ⟨114, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB114C233ForwardIndex residualTransportB114C233InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB114C233Payload, residualTransportB114C233ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB114C233_payloadValidFor :
    (residualCoverRow114C215_264[18]'(by decide)).ValidFor ⟨114, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow114C215_264, residualTransportB114C233Payload] using
    residualTransportB114C233_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
