import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_156_C_207_256

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (156,219) through (156,235), aligned to R_156_C_207_256
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB156C219Payload : ValidRowPayload :=
  { c := ⟨219, by decide⟩, classIndex := ⟨249, by decide⟩, canonicalB := ⟨61, by decide⟩, canonicalC := ⟨213, by decide⟩, y := GF25.ofNat 24, z := GF25.ofNat 14, legalCount := 42, orbitSize := 400 }

def residualTransportB156C219ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 3, 2]
def residualTransportB156C219InverseIndex : Fin 8 → Fin 8 := ![0, 1, 7, 6, 5, 4, 3, 2]

theorem residualTransportB156C219_transportValid :
    residualTransportB156C219Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C219ForwardIndex residualTransportB156C219InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C219Payload, residualTransportB156C219ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C219_payloadValidFor :
    (residualCoverRow156C207_256[12]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C219Payload] using
    residualTransportB156C219_transportValid

def residualTransportB156C222Payload : ValidRowPayload :=
  { c := ⟨222, by decide⟩, classIndex := ⟨554, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 6, legalCount := 37, orbitSize := 400 }

def residualTransportB156C222ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB156C222InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB156C222_transportValid :
    residualTransportB156C222Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C222ForwardIndex residualTransportB156C222InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C222Payload, residualTransportB156C222ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C222_payloadValidFor :
    (residualCoverRow156C207_256[15]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C222Payload] using
    residualTransportB156C222_transportValid

def residualTransportB156C223Payload : ValidRowPayload :=
  { c := ⟨223, by decide⟩, classIndex := ⟨624, by decide⟩, canonicalB := ⟨72, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 6, legalCount := 35, orbitSize := 200 }

def residualTransportB156C223ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB156C223InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB156C223_transportValid :
    residualTransportB156C223Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C223ForwardIndex residualTransportB156C223InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C223Payload, residualTransportB156C223ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C223_payloadValidFor :
    (residualCoverRow156C207_256[16]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C223Payload] using
    residualTransportB156C223_transportValid

def residualTransportB156C224Payload : ValidRowPayload :=
  { c := ⟨224, by decide⟩, classIndex := ⟨554, by decide⟩, canonicalB := ⟨71, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 37, orbitSize := 400 }

def residualTransportB156C224ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB156C224InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB156C224_transportValid :
    residualTransportB156C224Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C224ForwardIndex residualTransportB156C224InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C224Payload, residualTransportB156C224ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C224_payloadValidFor :
    (residualCoverRow156C207_256[17]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C224Payload] using
    residualTransportB156C224_transportValid

def residualTransportB156C232Payload : ValidRowPayload :=
  { c := ⟨232, by decide⟩, classIndex := ⟨765, by decide⟩, canonicalB := ⟨81, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 6, legalCount := 37, orbitSize := 400 }

def residualTransportB156C232ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB156C232InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB156C232_transportValid :
    residualTransportB156C232Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C232ForwardIndex residualTransportB156C232InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C232Payload, residualTransportB156C232ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C232_payloadValidFor :
    (residualCoverRow156C207_256[25]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C232Payload] using
    residualTransportB156C232_transportValid

def residualTransportB156C233Payload : ValidRowPayload :=
  { c := ⟨233, by decide⟩, classIndex := ⟨766, by decide⟩, canonicalB := ⟨82, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 8, z := GF25.ofNat 6, legalCount := 37, orbitSize := 200 }

def residualTransportB156C233ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB156C233InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB156C233_transportValid :
    residualTransportB156C233Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C233ForwardIndex residualTransportB156C233InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C233Payload, residualTransportB156C233ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C233_payloadValidFor :
    (residualCoverRow156C207_256[26]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C233Payload] using
    residualTransportB156C233_transportValid

def residualTransportB156C234Payload : ValidRowPayload :=
  { c := ⟨234, by decide⟩, classIndex := ⟨765, by decide⟩, canonicalB := ⟨81, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 37, orbitSize := 400 }

def residualTransportB156C234ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB156C234InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB156C234_transportValid :
    residualTransportB156C234Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C234ForwardIndex residualTransportB156C234InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C234Payload, residualTransportB156C234ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C234_payloadValidFor :
    (residualCoverRow156C207_256[27]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C234Payload] using
    residualTransportB156C234_transportValid

def residualTransportB156C235Payload : ValidRowPayload :=
  { c := ⟨235, by decide⟩, classIndex := ⟨767, by decide⟩, canonicalB := ⟨85, by decide⟩, canonicalC := ⟨109, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 38, orbitSize := 400 }

def residualTransportB156C235ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB156C235InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB156C235_transportValid :
    residualTransportB156C235Payload.TransportValid ⟨156, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB156C235ForwardIndex residualTransportB156C235InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB156C235Payload, residualTransportB156C235ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB156C235_payloadValidFor :
    (residualCoverRow156C207_256[28]'(by decide)).ValidFor ⟨156, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow156C207_256, residualTransportB156C235Payload] using
    residualTransportB156C235_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
