import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_181_C_182_231

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 8 valid rows (181,207) through (181,215), aligned to R_181_C_182_231
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB181C207Payload : ValidRowPayload :=
  { c := ⟨207, by decide⟩, classIndex := ⟨81, by decide⟩, canonicalB := ⟨58, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 41, orbitSize := 400 }

def residualTransportB181C207ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C207InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C207_transportValid :
    residualTransportB181C207Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C207ForwardIndex residualTransportB181C207InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C207Payload, residualTransportB181C207ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C207_payloadValidFor :
    (residualCoverRow181C182_231[25]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C207Payload] using
    residualTransportB181C207_transportValid

def residualTransportB181C208Payload : ValidRowPayload :=
  { c := ⟨208, by decide⟩, classIndex := ⟨30, by decide⟩, canonicalB := ⟨57, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 38, orbitSize := 400 }

def residualTransportB181C208ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C208InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C208_transportValid :
    residualTransportB181C208Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C208ForwardIndex residualTransportB181C208InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C208Payload, residualTransportB181C208ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C208_payloadValidFor :
    (residualCoverRow181C182_231[26]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C208Payload] using
    residualTransportB181C208_transportValid

def residualTransportB181C210Payload : ValidRowPayload :=
  { c := ⟨210, by decide⟩, classIndex := ⟨200, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 41, orbitSize := 400 }

def residualTransportB181C210ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C210InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C210_transportValid :
    residualTransportB181C210Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C210ForwardIndex residualTransportB181C210InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C210Payload, residualTransportB181C210ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C210_payloadValidFor :
    (residualCoverRow181C182_231[28]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C210Payload] using
    residualTransportB181C210_transportValid

def residualTransportB181C211Payload : ValidRowPayload :=
  { c := ⟨211, by decide⟩, classIndex := ⟨519, by decide⟩, canonicalB := ⟨64, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 42, orbitSize := 400 }

def residualTransportB181C211ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C211InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C211_transportValid :
    residualTransportB181C211Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C211ForwardIndex residualTransportB181C211InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C211Payload, residualTransportB181C211ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C211_payloadValidFor :
    (residualCoverRow181C182_231[29]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C211Payload] using
    residualTransportB181C211_transportValid

def residualTransportB181C212Payload : ValidRowPayload :=
  { c := ⟨212, by decide⟩, classIndex := ⟨440, by decide⟩, canonicalB := ⟨63, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 36, orbitSize := 400 }

def residualTransportB181C212ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C212InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C212_transportValid :
    residualTransportB181C212Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C212ForwardIndex residualTransportB181C212InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C212Payload, residualTransportB181C212ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C212_payloadValidFor :
    (residualCoverRow181C182_231[30]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C212Payload] using
    residualTransportB181C212_transportValid

def residualTransportB181C213Payload : ValidRowPayload :=
  { c := ⟨213, by decide⟩, classIndex := ⟨365, by decide⟩, canonicalB := ⟨62, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 41, orbitSize := 400 }

def residualTransportB181C213ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C213InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C213_transportValid :
    residualTransportB181C213Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C213ForwardIndex residualTransportB181C213InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C213Payload, residualTransportB181C213ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C213_payloadValidFor :
    (residualCoverRow181C182_231[31]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C213Payload] using
    residualTransportB181C213_transportValid

def residualTransportB181C214Payload : ValidRowPayload :=
  { c := ⟨214, by decide⟩, classIndex := ⟨283, by decide⟩, canonicalB := ⟨61, by decide⟩, canonicalC := ⟨134, by decide⟩, y := GF25.ofNat 20, z := GF25.ofNat 20, legalCount := 40, orbitSize := 400 }

def residualTransportB181C214ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]
def residualTransportB181C214InverseIndex : Fin 8 → Fin 8 := ![0, 1, 3, 2, 7, 6, 5, 4]

theorem residualTransportB181C214_transportValid :
    residualTransportB181C214Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C214ForwardIndex residualTransportB181C214InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C214Payload, residualTransportB181C214ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C214_payloadValidFor :
    (residualCoverRow181C182_231[32]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C214Payload] using
    residualTransportB181C214_transportValid

def residualTransportB181C215Payload : ValidRowPayload :=
  { c := ⟨215, by decide⟩, classIndex := ⟨224, by decide⟩, canonicalB := ⟨60, by decide⟩, canonicalC := ⟨237, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 15, legalCount := 43, orbitSize := 400 }

def residualTransportB181C215ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]
def residualTransportB181C215InverseIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]

theorem residualTransportB181C215_transportValid :
    residualTransportB181C215Payload.TransportValid ⟨181, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB181C215ForwardIndex residualTransportB181C215InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB181C215Payload, residualTransportB181C215ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB181C215_payloadValidFor :
    (residualCoverRow181C182_231[33]'(by decide)).ValidFor ⟨181, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow181C182_231, residualTransportB181C215Payload] using
    residualTransportB181C215_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
