import RelativeConicArcs.Q25ResidualCoverBridge
import RelativeConicArcs.Q25ResidualCoverData.R_208_C_209_258

/-!
# Generated C151 residual-transport certificates

DO NOT EDIT: generated by `notes/2026-07-15-c151-residual-transport-generator.py`.

* payload: 3 valid rows (208,242) through (208,249), aligned to R_208_C_209_258
* canonical CSV SHA256: `62aa26c98deb98cb786fa1b21957b91ec16b1e2bd2a6319129c31449eb0effe3`
* cover-generator SHA256: `10bfb5f446eec17ef1cb2543f9ff7c3581c25b3e41d4a5b0b2ccd99314e9c388`
* transport-generator SHA256: `23d8e88ed37070867e2fe8964f25ec58556b8d69434765cb291f49a9ef6005c0`
* transport FNV-1a-64: `4e503df3c383731d`
-/

namespace RelativeConicArcs
namespace Q25ResidualTransportData

open Q25Coordinates Q25PairCertificate Q25Normalization Q25ResidualAction
  Q25ResidualCoverData FiniteFields

def residualTransportB208C242Payload : ValidRowPayload :=
  { c := ⟨242, by decide⟩, classIndex := ⟨25, by decide⟩, canonicalB := ⟨44, by decide⟩, canonicalC := ⟨57, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 8, legalCount := 43, orbitSize := 400 }

def residualTransportB208C242ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB208C242InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB208C242_transportValid :
    residualTransportB208C242Payload.TransportValid ⟨208, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB208C242ForwardIndex residualTransportB208C242InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB208C242Payload, residualTransportB208C242ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB208C242_payloadValidFor :
    (residualCoverRow208C209_258[33]'(by decide)).ValidFor ⟨208, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow208C209_258, residualTransportB208C242Payload] using
    residualTransportB208C242_transportValid

def residualTransportB208C247Payload : ValidRowPayload :=
  { c := ⟨247, by decide⟩, classIndex := ⟨27, by decide⟩, canonicalB := ⟨49, by decide⟩, canonicalC := ⟨57, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 8, legalCount := 42, orbitSize := 400 }

def residualTransportB208C247ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB208C247InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB208C247_transportValid :
    residualTransportB208C247Payload.TransportValid ⟨208, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB208C247ForwardIndex residualTransportB208C247InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB208C247Payload, residualTransportB208C247ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB208C247_payloadValidFor :
    (residualCoverRow208C209_258[38]'(by decide)).ValidFor ⟨208, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow208C209_258, residualTransportB208C247Payload] using
    residualTransportB208C247_transportValid

def residualTransportB208C249Payload : ValidRowPayload :=
  { c := ⟨249, by decide⟩, classIndex := ⟨26, by decide⟩, canonicalB := ⟨46, by decide⟩, canonicalC := ⟨57, by decide⟩, y := GF25.ofNat 9, z := GF25.ofNat 8, legalCount := 38, orbitSize := 400 }

def residualTransportB208C249ForwardIndex : Fin 8 → Fin 8 := ![0, 1, 6, 7, 2, 3, 4, 5]
def residualTransportB208C249InverseIndex : Fin 8 → Fin 8 := ![0, 1, 4, 5, 6, 7, 2, 3]

theorem residualTransportB208C249_transportValid :
    residualTransportB208C249Payload.TransportValid ⟨208, by decide⟩ := by
  apply ValidRowPayload.transportValid_of_pointTransport
    residualTransportB208C249ForwardIndex residualTransportB208C249InverseIndex (by decide) (by decide)
  · unfold ValidRowPayload.PointTransport
    intro i
    fin_cases i <;>
      simp [residualTransportB208C249Payload, residualTransportB208C249ForwardIndex, configPoint, orbitCodeOfNumber,
        codeFin5, codeFin2, smallNonfixed, orbitIdx, Q25Coordinates.conjIdx,
        Q25Coordinates.conj, residualApply, Q25Normalization.shift,
        Q25Normalization.scale, Q25Normalization.realPart, Q25Normalization.imagPart,
        GF25.ofNat, GF25.encode] <;> decide
  · intro i
    fin_cases i <;> decide

theorem residualTransportB208C249_payloadValidFor :
    (residualCoverRow208C209_258[40]'(by decide)).ValidFor ⟨208, by decide⟩ := by
  simpa [ResidualRowPayload.ValidFor, residualCoverRow208C209_258, residualTransportB208C249Payload] using
    residualTransportB208C249_transportValid

end Q25ResidualTransportData
end RelativeConicArcs
